### ISSUE TITLE
ChatGPT 被禁

### ISSUE THREAD

**Issue by roostinghawk** [yihong0618/xiaogpt#10]
大家有没有遇到这个错误？之前好使的 ChatGPT 账号，现在开 VPN 后出现这个错误
<img width="322" alt="image" src="https://user-images.githubusercontent.com/5466611/220111392-922a3096-c737-476a-beb5-74d5d13623d4.png">

**Comment by yihong0618** [comment]
梯子供应商问题。。。

**Comment by yihong0618** [comment]
先关了。。。

**Comment by roostinghawk** [comment]
嗯，账号没问题，应该是IP被封了，新买的 server 没问题
