### ISSUE TITLE
已经安装了openai，运行还是报 no module name 'openai'

### ISSUE THREAD

**Issue by joisonwk** [yihong0618/xiaogpt#103]
哪位大佬知道这是什么原因吗？
已经在当前python环境通过pip install openai，运行最终命令还是提示没有名为openai的模块
pip list 已安装openai 0.27.1

> openai             0.27.1
pip                19.2.3
prompt-toolkit     3.0.38
pycryptodomex      3.17
Pygments           2.14.0
PySocks            1.7.1
regex              2022.10.31
requests           2.28.2
revChatGPT         3.2.0
rfc3986            1.5.0
rich               13.3.2
setuptools         41.2.0
sniffio            1.3.0
socksio            1.0.0
tiktoken           0.3.0
tqdm               4.65.0
typing-extensions  4.5.0
urllib3            1.26.14
wcwidth            0.2.6
yarl               1.8.2
WARNING: You are using pip version 19.2.3, however version 23.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
(venv) PS E:\stable-diffusion\gpt_application\xiaogpt> python3 xiaogpt.py --hardware S12A --use_chatgpt_api --mute_xiaoai
Traceback (most recent call last):
  File "E:\stable-diffusion\gpt_application\xiaogpt\xiaogpt.py", line 12, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by yihong0618** [comment]
pip install -U openai

**Comment by joisonwk** [comment]
谢谢  两位 ，虚拟环境里的python我写成了python3了，用的是我系统环境里的python
