### ISSUE TITLE
KeyError: 'choices' 请问下这个报错要怎么处理

### ISSUE THREAD

**Issue by litsen** [yihong0618/xiaogpt#118]
型号LX05, 没返回GPT的回答 

File "C:\Program Files\Python310\lib\site-packages\xiaogpt\bot\chatgptapi_bot.py", line 24, in ask
    completion["choices"][0]
KeyError: 'choices'
![image](https://user-images.githubusercontent.com/3929213/225058557-17ed58f8-5b2b-43a1-b7ac-477386d79bdb.png)

**Comment by yihong0618** [comment]
确保你的 api token 能跑

**Comment by chao325** [comment]
每日上限200 已经超额啊
