### ISSUE TITLE
新增一个 “Redmi小爱音箱 Play” 型号 L07A

### ISSUE THREAD

**Issue by SiMONTYC** [yihong0618/xiaogpt#123]
型号：L07A

**设备信息**
`  {
    "name": "Redmi小爱音箱 Play",
    "model": "xiaomi.wifispeaker.l7a"
  },`

**支持的命令**
`# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l7a:1

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rwn
    Mute = 2  # bool  # rwn

Microphone = 3
    Mute = 1  # bool  # rwn

Play_Control = 4
    Playing_State = 1  # uint8  # rn

    _Pause = 1
    _Play = 2
    _Next = 3
    _Previous = 4

Intelligent_Speaker = 5
    _Text_Content = 1
    _Silent_Execution = 2  # uint8

    _Play_Text = 1  # in=[1]
    _Wake_Up = 2
    _Play_Radio = 3
    _Play_Music = 4
    _Execute_Text_Directive = 5  # in=[1, 2]

Clock = 6

    _Stop_Alarm = 1

Speaker_Volume
    MIN = 3
    MAX = 100

Play_Control_Playing_State
    Idle = 0
    Playing = 1

Intelligent_Speaker_Silent_Execution
    On = 0
    Off = 1`

**Comment by yihong0618** [comment]
也是 5-1 么？

**Comment by Eloco** [comment]
有时间的话请支持lx5a，谢谢
http://paste.c-net.org/DwightPlayful

**Comment by yihong0618** [comment]
好，我们看一下

**Comment by SiMONTYC** [comment]
> 也是 5-1 么？

是的

**Comment by cnrock** [comment]
感谢大佬的代码，同款红米小爱音箱跑起来了。

前面测试了一下，最新版已经支持L07A这个机器了，我对 xiaogpt/config.py 文件做了如下修改：
HARDWARE_COMMAND_DICT下面新增
"L07A": ("5-1", "5-5"),

然后是 class Config: 下面 ，修改hardware 对应的 LX06  为 L07A
可以参考如下部分代码：

`HARDWARE_COMMAND_DICT = {
     # hardware: (tts_command, wakeup_command)
     "LX06": ("5-1", "5-5"),
     "L07A": ("5-1", "5-5"),
........

 @dataclass
 class Config:
     hardware: str = "L07A"
    # hardware: str = "LX06"
     account: str = os.getenv("MI_USER", "")`

**Comment by yihong0618** [comment]
@cnrock 有兴趣提个 pr 给加上吗

**Comment by Eloco** [comment]
> 好，我们看一下

可以看看lx5a嘛，谢谢
http://paste.c-net.org/DwightPlayful
