### ISSUE TITLE
xiaogpt --hardware LX05  --mute_xiaoai --use_gpt3  运行这个命令后报错了。

### ISSUE THREAD

**Issue by 90tech** [yihong0618/xiaogpt#124]
![image](https://user-images.githubusercontent.com/8855966/225498028-cf48ce24-e6d8-4e30-b932-4b5e53a8d8d4.png)

xiaogpt --hardware LX05  --mute_xiaoai --use_gpt3  运行这个命令后报错了。什么原因呢？

**Comment by yihong0618** [comment]
pip install rich
可以用 —use_chatgpt_api

**Comment by yihong0618** [comment]
@90tech 更新了

pip install -U xiaogpt

**Comment by 90tech** [comment]
运行后可以了，回答问题出现报错，这个什么原因？
![image](https://user-images.githubusercontent.com/8855966/225504314-e52cdd5f-4035-4c12-bc85-bfa2c575e65c.png)

**Comment by yihong0618** [comment]
@90tech 
pip unisntall miservice
pip install -U miservice_fork
