### ISSUE TITLE
Running xiaogpt now, 用`帮我/请回答`开头来提问 》》后出现错误

### ISSUE THREAD

**Issue by 90tech** [yihong0618/xiaogpt#125]
运行后可以了，回答问题出现报错，这个什么原因？
![image](https://user-images.githubusercontent.com/8855966/225505606-c0c8d40d-cc0b-4b68-9490-314846fb710e.png)

**Comment by yihong0618** [comment]
pip uninstall miservice

then
pip install miservice_fork

**Comment by 90tech** [comment]
pip install miservice_fork 运行完这个后是否要按之前的步骤再配置一次？

**Comment by yihong0618** [comment]
不用，直接跑就行

**Comment by 90tech** [comment]
可以了，感谢
