### ISSUE TITLE
请问可以支持小米电视么？

### ISSUE THREAD

**Issue by Nxcegit** [yihong0618/xiaogpt#126]
minaService的device_list方法是获取不到的，master参数是表示获取音箱设备么？
在_init_data_hardware方法里写死了我的电视的device_id，device_profile/v2/conversation的endpoint也一直无法返回···

请问有大佬连接电视成功么？

**Comment by yihong0618** [comment]
小米电视理论不行（

**Comment by DiscardZhebin** [comment]
> 小米电视理论不行（

请问比如LATEST_ASK_API这些开放的API在哪里能看到呢？看了下小米开放平台的文档中心（https://dev.mi.com/distribute/doc/home）看了一段时间感觉没什么有价值的接入文档额···

**Comment by yihong0618** [comment]
无法 tts 应该支持不了，先关了哈
