### ISSUE TITLE
Exception: we have no hardware: LX01 please check

### ISSUE THREAD

**Issue by gsscsd** [yihong0618/xiaogpt#130]
有没有大佬能帮忙看一下呀，报错信息如下，看上去，调用miService以后，未获取到对应`hardware_data`数据
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/12953213/225685461-4e8170cd-1b3a-4669-bec8-bc5584abd368.png">

**Comment by yihong0618** [comment]
下载个米家把设备加进去

**Comment by gsscsd** [comment]
米家加入设备还是没能成功呢，micli能列出下面所有的设备
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/12953213/226156121-3810438e-2a5b-4609-a7ed-fb4cf49837d2.png">

**Comment by yihong0618** [comment]
micli mina 呢？

**Comment by gsscsd** [comment]
这个是空，这是表明，我的账号没有绑定小米设备是吗
<img width="279" alt="image" src="https://user-images.githubusercontent.com/12953213/226176568-358099ed-6f6e-480a-b0ff-4c2a61e16ca3.png">

**Comment by yihong0618** [comment]
是，下个小米音箱 app

**Comment by gsscsd** [comment]
大佬，辛苦问一下，我这里米家和小爱音箱app里面，都绑定了小爱同学，但是micli mina返回还是空数组
![image](https://user-images.githubusercontent.com/12953213/226179028-781f7ee8-4d42-4089-a3e8-d0871d811217.png)

**Comment by yihong0618** [comment]
好像是这个 mini 不支持你需要用 --use_command

**Comment by gsscsd** [comment]
好的，感谢大佬，有空整个完整版的小爱同学吧

**Comment by yihong0618** [comment]
—use_command 除了不能 mute 别的应该行
