### ISSUE TITLE
型號LX01，報錯object has no attribute 'player_get_status

### ISSUE THREAD

**Issue by Ethan4928** [yihong0618/xiaogpt#132]
機器型號LX01，

使用--mute_xiaoai參數下，執行後必發下面錯誤
xiaogpt/xiaogpt.py", line 195, in get_if_xiaoai_is_playing playing_info = await self.mina_service.player_get_status(self.device_id) AttributeError: 'MiNAService' object has no attribute 'player_get_status'

去掉--mute_xiaoai參數後，改為偶發報錯。

**Comment by yihong0618** [comment]
pip uninstall miservice
pip install miservice_fork
