### ISSUE TITLE
型号报错

### ISSUE THREAD

**Issue by yuan8831191** [yihong0618/xiaogpt#133]
cannot find did for hardware: S12A please set it via MI_DID env
 mi_did  我也输入了还是不行啊

**Comment by yuan8831191** [comment]
cannot find did for hardware: S12A please set it via MI_DID env
 这是报错原文  ，还是说型号这里不是 S12A

**Comment by yuan8831191** [comment]
已经解决，重新设置了MI_did.

**Comment by yihong0618** [comment]
@frostming 我感觉我木讷 MI_DID 这步也可以让用户省了。。
