### ISSUE TITLE
SSLCertVerificationError问题

### ISSUE THREAD

**Issue by AirHua-byte** [yihong0618/xiaogpt#141]
环境：
mac + LX05

---

使用openai_api_key后，执行最后命令，最后报的是这个错，打印 帮我/请回答开头来提问 后出现的，有解决方案吗

raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api2.mina.mi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]

**Comment by yihong0618** [comment]
参考最后一个 comment 

https://github.com/yihong0618/xiaogpt/issues/41

**Comment by AirHua-byte** [comment]
> 参考最后一个 comment
> 
> #41

我已经拉取的是最新的代码了

**Comment by yihong0618** [comment]
参考这个 -> https://github.com/aio-libs/aiohttp/issues/955#issuecomment-509119559
