### ISSUE TITLE
问完小爱之后大约1-2分钟问题才出现在我的PC端上然后显示开始正在询问GPT请等待

### ISSUE THREAD

**Issue by moonbreeze4** [yihong0618/xiaogpt#142]
为什么视频里回答的那么流畅，有什么办法加速吗？

小爱的蓝牙我打开了，电脑是否也必须要有蓝牙功能？蓝牙功能的作用是什么

**Comment by yihong0618** [comment]
1. 拉一下最新代码
2. 加上 —mute_xiaoai
3. 确认自己网络的速度

**Comment by roostinghawk** [comment]
1-2 分钟出现，应该是因为从小爱平台获取最新聊天记录太慢，看下是不是 vpn 打开全局。网络没问题的话再看下“micli.py list” 这个命令返回的速度怎么样

**Comment by moonbreeze4** [comment]
> @moonbreeze4 拉最新代码试试

用了最新的1.1依然没变化，需要1分钟小爱才会把自己的答案返回程序这边，然后开始问GPT，加上--mute_xiaoai了，好像和梯子没什么关系，我完全不开梯子小爱那边的回复过来也要将近一分钟（当然不开的话后面gpt的回答就进行不下去了）
