### ISSUE TITLE
关于去掉唤醒词  作者可以写一个短教程吗

### ISSUE THREAD

**Issue by eavin7456** [yihong0618/xiaogpt#150]
看了代码看不懂啊0 0

**Comment by yihong0618** [comment]
TODO
我们可以把唤醒次加到 args?
@frostming @pjq

**Comment by frostming** [comment]
所有用户可以改变的东西都在`config.json.example` 里面可以看到，你可以从这个生成一个自己的配置文件，用`--config <config_path>` 读取它，这些都在README里有提到

**Comment by yihong0618** [comment]
好滴。
