### ISSUE TITLE
为什么我请求小米返回的内容体是这个， 也没报错， 查了一下貌似也不是风控， 我昨天换了一个ip也不行。也换账号了

### ISSUE THREAD

**Issue by Mr1994** [yihong0618/xiaogpt#152]
{'notificationUrl': '/identity/authStart?sid=xiaomiio&context=YPBaJrB74SQKXkKOpjUxxC3l5UbAo41TROpGQU_YaSanlJg1gohfGUyZ_x7XjazhS-oyP_dAy6ZV2mEBLajMqwrHnqEPBDnai7yCjlxPmGovsMlVS5rV3xIYdyNpt9y-imn4PaLiNIpZzRtFwOLg2pe-EFvhd1ROtNk5F94wi6-yvWACjvYUoDiWhnO68UyL-BpfTunzvebV3Ojz4iR1bGxuMGos0RRZihgmYRzJCRbnyxk1ILYs1rvaeXPrxOA8yDfGkdRCehk5jFQI4MPZeIUOs3VhT1SL5gubM41unyTfP9VRUn2PK7X_kDSNA2FF8_hPWhxdkAfKD-eExOxeYYUzpRbT0dy2o3z54-VdOIREuCM7D7nQyiE0fo6mo8Y7S0E2itm7BDpB035LXb_4c4h0HW35gXO2ORGeX5hgvCfFXC3rauuN5qeuLEQ_-6TlDlKk4VCgWaeDxZ-oNK0OStw_fVo6TPXBGKG2txLAxDRFRGdS1ywitfyJjc60Z6TaJrbRsgbyCvJwKPqFjdAgLqz-YOd37MW5N1NdSSQk1kQFFRIqDHWQRqaOUVE7Op7GkGSfPCmVrKFgjl6sBoMIRMxRfa3Me4BZftN-Eqrofv1hDRkCbKmciIPkuIrC9f_4FpxJ6LtN_U2RbPG3Y1jPgZA3Qz8r3HC4byf80RKsZ2z-LwL_Lbk1HWIKIqoioKFnDDQyWEqQ0kJQbUOKAo3qHA&_locale=zh_HK', 'result': 'ok', 'code': 0, 'captchaUrl': None, 'description': '成功', 'location': '', 'securityStatus': 16, 'pwd': 0, 'child': 0, 'desc': '成功'}

**Comment by yihong0618** [comment]
@Mr1994 换个网络试试？比如用手机做热点？

**Comment by Deanwfy** [comment]
碰到了同样的问题，应该是网络原因。
同一个账号，本机请求OK，腾讯云上NG，不知道规则是怎样的。。

**Comment by yihong0618** [comment]
@Deanwfy 腾讯云会触发小米的风控

**Comment by Deanwfy** [comment]
@yihong0618 啊，果然如此。感谢
