### ISSUE TITLE
Self-managed docker image

### ISSUE THREAD

**Issue by frostming** [yihong0618/xiaogpt#154]
是否可以把 Docker 镜像构建收归到这个项目下，这样可以利用github action自动构建上传，免去手动上传的工作

cc @pjq 
cc @yihong0618 需要有 hub.docker.com 的账号

**Comment by yihong0618** [comment]
可以，添加 secret 就行。但这个不是 org 项目我不确定协助者能添加 secret 么

**Comment by yihong0618** [comment]
我可以放我的账号上去。我研究下

**Comment by frostming** [comment]
This is solved by #156
