### ISSUE TITLE
支持socks5代理么

### ISSUE THREAD

**Issue by zyw516** [yihong0618/xiaogpt#155]
国内网络原因请求不了
手上有socks5代理 目前好像无法配置

**Comment by yihong0618** [comment]
目前可以改 api_base 实现。

**Comment by zyw516** [comment]
了解  api_base 需要公网服务器 貌似不是很安全
我研究一下源码  看看能不能提个PR

**Comment by yihong0618** [comment]
@zyw516 always welcome!

**Comment by PJovy** [comment]
我看了一下 openai python 库的实现，是基于 aiohttp 的 ClientSession 实现的网络请求管理，这个是能够配置和实现 SOCKS5 代理的，我刚才本地用脚本做了验证可行。
我看看晚一些整理下 PR
