### ISSUE TITLE
克隆之后执行pip install安装报错，求解

### ISSUE THREAD

**Issue by luoly601** [yihong0618/xiaogpt#157]
ERROR: Could not find a version that satisfies the requirement xiaogpt (from versions: none)
ERROR: No matching distribution found for xiaogpt

**Comment by yihong0618** [comment]
你的环境是？

**Comment by frostming** [comment]
请注意Python最低版本要求 >=3.7.1

**Comment by yihong0618** [comment]
@luoly601 先关了哈～
