### ISSUE TITLE
player_get_status 错误

### ISSUE THREAD

**Issue by zxerqw** [yihong0618/xiaogpt#16]
我看了下MiService，他也没有这个player_get_status/player_pause啊，老哥你是调用的哪个

**Comment by yihong0618** [comment]
升级一下 pip install -U git+https://github.com/yihong0618/MiService
启动时候用 --mute_xiaomi

**Comment by yihong0618** [comment]
提示词和 sleep 时间可以自己 DIY 但不建议长时间跑。

**Comment by zxerqw** [comment]
我也发现了，实现方式有点猛，要是能给音箱设置个代理啥的hook请求就好了
