### ISSUE TITLE
出现一个错误，请教一下是什么原因

### ISSUE THREAD

**Issue by tomdbtel** [yihong0618/xiaogpt#160]
AttributeError: 'MiNAService' object has no attribute 'player_get_status'

**Comment by frostming** [comment]
Duplicate #137

**Comment by tomdbtel** [comment]
感谢，问题已解决

**Comment by tomdbtel** [comment]
以下是GPT的回答: GPT回答出错 Error communicating with OpenAI，这是什么原因呢？

**Comment by frostming** [comment]
报错的话稍等重试下，如果一直报这个错，请检查网络环境到openai是通的

**Comment by tomdbtel** [comment]
电脑端可以正常反问chatGPT的

**Comment by yihong0618** [comment]
访问 chatGPT 和能用 api 不太一样，可以用 python repl 试试你的 token 能通么
