### ISSUE TITLE
读取对话的延迟问题

### ISSUE THREAD

**Issue by MarioZZJ** [yihong0618/xiaogpt#163]
在 PC 上体验了一下，能用，但是延迟很大。

我这里向音箱说话之后，要过 30s 左右程序才会显示我说的话，这时候才去请求 OPENAI API。

打开 verbose 之后发现

```
Now listening xiaoai new message timestamp: 1679586622211
```

这里的 timestamp 会延迟停留在上一条的时间，过大概半分钟才刷新。所以应该是运行程序的机器请求最近一条对话产生的延迟。不知道是不是我的网络/账号被风控了有延迟，还是服务端那边给出了限制？

**Comment by yihong0618** [comment]
- 昨天 openai 特别慢。
- 有可能是你电脑设置了 proxy
- 尝试拉取最新的代码

**Comment by MarioZZJ** [comment]
好像不是我和 openai 的问题，是我这边读取小米平台的对话记录就会慢一拍，这个有什么办法可以排查吗

**Comment by yihong0618** [comment]
@MarioZZJ  --mute_xiaoai

**Comment by MarioZZJ** [comment]
这个参数我已经加上了，感觉就是和小米平台那边通讯有问题。

您看最上面我也试过打开 `verbose`，这个会一秒刷新一次最新的 `message_timestamp`，按理来说是不是我说完话这边显示的 `timestamp` 就能更新？但是我这里要等个半分钟才能更新（即读取到最新的对话），然后程序才去查询 OpenAI

**Comment by yihong0618** [comment]
关掉所有代理试试？

**Comment by MarioZZJ** [comment]
关闭了。换了个不同地区的 Linux 机器也是这样……是不是我的账号有问题了？
