### ISSUE TITLE
xiaogpt.py已经跑起来了，但呼唤小爱同学xiaogpt.py没有任何反应

### ISSUE THREAD

**Issue by lsdjqwq** [yihong0618/xiaogpt#166]
尝试在xiaogpt.py里加了print，但是呼唤小爱同学后也没print啥
这可能是啥原因？
有点好奇为啥叫了小爱同学，电脑上的程序可以捕获到

**Comment by yihong0618** [comment]
请给出更详细的信息，比如截图？

**Comment by TyTheLoser** [comment]
hardware: str = "L05B"
    account: str = os.getenv("MI_USER", "x")
    password: str = os.getenv("MI_PASS", "x")
    openai_key: str = os.getenv("OPENAI_API_KEY", "x")
    proxy: str | None = None
    mi_did: str = os.getenv("MI_DID", "x")
    keyword: Iterable[str] = KEY_WORD
    change_prompt_keyword: Iterable[str] = CHANGE_PROMPT_KEY_WORD
    prompt: str = PROMPT
    mute_xiaoai: bool = True
    bot: str = "chatgpt"
    cookie: str = ""
    api_base: str | None = None
    deployment_id: str | None = None
    use_command: bool = True
    verbose: bool = False
    start_conversation: str = "开始持续对话"
    end_conversation: str = "结束持续对话"
    stream: bool = False
    enable_edge_tts: bool = False
    localhost: bool = True
    edge_tts_voice: str = "zh-CN-XiaoxiaoNeural"
    gpt_options: dict[str, Any] = field(default_factory=dict)
    bing_cookie_path: str = ""
    bing_cookies: dict | None = None
大佬我也是正常运行xiaogpt.py，但是没有任何反应，型号是l05b

**Comment by TyTheLoser** [comment]
> 请给出更详细的信息，比如截图？
hardware: str = "L05B"
account: str = os.getenv("MI_USER", "x")
password: str = os.getenv("MI_PASS", "x")
openai_key: str = os.getenv("OPENAI_API_KEY", "x")
proxy: str | None = None
mi_did: str = os.getenv("MI_DID", "x")
keyword: Iterable[str] = KEY_WORD
change_prompt_keyword: Iterable[str] = CHANGE_PROMPT_KEY_WORD
prompt: str = PROMPT
mute_xiaoai: bool = True
bot: str = "chatgpt"
cookie: str = ""
api_base: str | None = None
deployment_id: str | None = None
use_command: bool = True
verbose: bool = False
start_conversation: str = "开始持续对话"
end_conversation: str = "结束持续对话"
stream: bool = False
enable_edge_tts: bool = False
localhost: bool = True
edge_tts_voice: str = "zh-CN-XiaoxiaoNeural"
gpt_options: dict[str, Any] = field(default_factory=dict)
bing_cookie_path: str = ""
bing_cookies: dict | None = None
大佬我也是正常运行xiaogpt.py，但是没有任何反应，型号是l05b

**Comment by ZhangJony** [comment]
L05C 运行起来，也没有任何报错，呼叫小爱，控制台也没有任何反应。

**Comment by yihong0618** [comment]
先关了，有更多信息随时打开
