### ISSUE TITLE
希望能够自定义PROMPT

### ISSUE THREAD

**Issue by 848244210** [yihong0618/xiaogpt#167]
希望能够自定义PROMPT，如图这样：
![1679678865471](https://user-images.githubusercontent.com/28977537/227597844-ee5ca30e-795a-4cc5-ba0d-b5ed1ded5e45.png)
默认的PROMPT是100字回答感觉太啰嗦了

**Comment by frostming** [comment]
已经支持了，这个config下面的所有key都是可以写在config.json里面的：
https://github.com/yihong0618/xiaogpt/blob/fb8d07c8c64d322ed63535cbb043edbefb06a258/xiaogpt/config.py#L52-L70

example里面漏写了，欢迎PR

**Comment by 848244210** [comment]
建议（补充）注释一下每一条实现的功能呢，谢谢

**Comment by yihong0618** [comment]
> 建议（补充）注释一下每一条实现的功能呢，谢谢

可以，PR welcome

**Comment by 848244210** [comment]
补充一点：config.json的文字格式和[config.py]不一样我，我不知道如何使用它们，寻求帮助

**Comment by frostming** [comment]
> 建议（补充）注释一下每一条实现的功能呢，谢谢
json不支持在里面塞注释，为了方便大家copy就能用，不能在里面加注释
