### ISSUE TITLE
（文档）关于配置注释并使用配置文件启动xiaogpt

### ISSUE THREAD

**Issue by 848244210** [yihong0618/xiaogpt#169]
## 配置 （测试版本：1.10） 注意请不要直接复制#以及#后面的注释

关于自定义唤醒词以及自定义prompt，可以通过--config 指定一个配置文件，你可以把xiao_config.json.example重命名为xiao_config.json

并使用shell启动：

xiaogpt --config xiao_config.json --api_base https://xxx.com/v1

xiao_config.json 常用配置信息注释，如没有可自行添加：

    "hardware": "",              #设备型号
    "account": "",               #小爱账户
    "password": "",              #小爱账户密码
    "openai_key": "",            #openai的apikey
    "cookie": "",                #小爱账户cookie （如果用上面密码登录可以不填）
    "mi_did": "",       #设备did
    "use_command": false,        
    "mute_xiaoai": true,         #快速停掉小爱自己的回答
    "verbose": false,
    "bot": "chatgptapi",
    "enable_edge_tts": false,    #使用更好的tts引擎
    "edge_tts_voice": "zh-CN-XiaoxiaoNeural", 
    "prompt": "请用猫娘的语气回答",               #自定义prompt
    "keyword": ["请问"],                         #自定义请求词
    "start_conversation": "开始持续对话",
    "end_conversation": "结束持续对话",
    "stream": false               #使用流式响应

以上，仅供参考

**Comment by frostming** [comment]
这反而增加了使用的难度，不建议在json里加注释，可以换成其他配置格式

**Comment by yihong0618** [comment]
建议放在 README 里提示
或者放在 arg -h li

**Comment by 848244210** [comment]
> 建议放于 README 里提示 或放于 arg -h 里

请开发者复制粘贴一下，我没有权限写入README

**Comment by yihong0618** [comment]
that is why you can open pull request～
可以 ChatGPT 搜索如何提 PR

**Comment by 848244210** [comment]
> 这就是为什么你可以打开pull request～ 可以ChatGPT 搜索如何提PR

好的，已提交
https://github.com/yihong0618/xiaogpt/pull/172

**Comment by s544838371** [comment]
想问一下，我这么写看日志提示找不到配置文件是为什么？
```
-v /opt/docker/xiaogpt/config:/config yihong0618/xiaogpt  --config=/config/config.json
```

**Comment by frostming** [comment]
@s544838371 你宿主机上的 `/opt/docker/xiaogpt/config/config.json` 这个文件存在吗
