### ISSUE TITLE
ask_gpt 耗时接近一分钟，是否有办法优化

### ISSUE THREAD

**Issue by tars-sh** [yihong0618/xiaogpt#17]
问题一：
你好，我本地测试，让小爱同学执行命令：“讲一下愚公移山的故事，请用100字以内回答”
单独看了一下ask_gpt的耗时，看了下需要一分多钟，请问为什么这么久呢？有办法优化吗？

<img width="777" alt="image" src="https://user-images.githubusercontent.com/103025229/220916321-fe84f966-c286-4e66-bd75-17737077e0d2.png">

问题二：
代码里执行 playing_info = await self.mina_service.player_get_status(self.device_id) 时，报错了，是否符合预期呢？
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_xUz8X05JCDWlbAt9TG6hMQSy4RmEdP'}}

**Comment by yihong0618** [comment]
(--mute_xiaoai + 用英文问能快一些 + 购买 chatgpt plus )== 快很多。

2. 不符合预期。

**Comment by tars-sh** [comment]
嗯，我目前统计的时间，是单独ask_gpt的耗时。

另外我想问下：
1. 在get_last_timestamp_and_record之前；执行了await self.stop_if_xiaoai_is_playing() 为什么要执行这个stop动作呢？
2. 另外在执行完gpt任务后，会持续查询 self.get_if_xiaoai_is_playing() 并sleep，这里的作用是？
3. 是否能够完全禁掉小爱同学自己的回答，只回答我调用 do_tts 的内容呢？

**Comment by yihong0618** [comment]
--mute_xiaoai  就是做 3 的你可以试试。
这些都是为了完全禁掉小爱回答。。。。

**Comment by tars-sh** [comment]
禁掉小爱同学的原理，就是调用 stop_if_xiaoai_is_playing 吗？我自己在改造这块的逻辑，不打算用 mute_xiaoai，所以想了解下

**Comment by yihong0618** [comment]
我在电脑 terminal里直接调用 revChatGPT.V1 是很快的
的原因是，他是一个字一个字打出来，你改改代码也能实现，其实时间是一样的。。。

---

但是像 terminal 那样，小爱一个字一个字念，你也特难受是吧。


> 禁掉小爱回答的原理，就是调用 stop_if_xiaoai_is_playing 吗？我自己在改造这块的逻辑，不打算用 mute_xiaoai，所以想了解下

对的，可以，去掉这块逻辑你往前切 commit 就行然后自己改。

**Comment by tars-sh** [comment]
他是一个字一个字打出来，你改改代码也能实现
---
这个了解了；或者可以改造为，出一句读一句这种形式

**Comment by yihong0618** [comment]
当然如果有更好的方式或者改代码，PR welcome 这个 issue 先关了哈。

**Comment by tars-sh** [comment]
> 嗯，我目前统计的时间，是单独ask_gpt的耗时。主要的问题是，我在电脑 terminal里直接调用 revChatGPT.V1 是很快的，但是通过小爱这里的脚本，就很慢，是不是内部有sleep之类的逻辑呢？
> 
> 另外我想问下：
> 
> 1. 在get_last_timestamp_and_record之前；执行了await self.stop_if_xiaoai_is_playing() 为什么要执行这个stop动作呢？
> 2. 另外在执行完gpt任务后，会持续查询 self.get_if_xiaoai_is_playing() 并sleep，这里的作用是？
> 3. 是否能够完全禁掉小爱同学自己的回答，只回答我调用 do_tts 的内容呢？

这里的问题还没完全答复哈😂

**Comment by yihong0618** [comment]
答完了，都是mute 小爱和打开用的，这个逻辑需要你自己理解
