### ISSUE TITLE
we have no hardware

### ISSUE THREAD

**Issue by Gloria0929** [yihong0618/xiaogpt#175]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/93187500/227761121-62e54489-05cf-4781-a1e8-09da9595806a.png">
mei没有找到型号

**Comment by yihong0618** [comment]
这个是闹钟的型号？

**Comment by Gloria0929** [comment]
> 这个是闹钟的型号吗？
音箱底部型号写的就是这个

**Comment by Gloria0929** [comment]
![IMG_0669](https://user-images.githubusercontent.com/93187500/227761924-9f24d1cf-6357-46ec-837e-6e383d3c714a.jpg)

**Comment by yihong0618** [comment]
`micli mina` 
看看里面显示的什么型号

**Comment by Gloria0929** [comment]
> `micli mina` 看看里面显示的什么型号

<img width="847" alt="image" src="https://user-images.githubusercontent.com/93187500/227763223-eb66e382-b7fc-4323-a0c3-895db1683b56.png">
S12支持吗

**Comment by Gloria0929** [comment]
好了，谢谢作者

**Comment by yihong0618** [comment]
我在 README 里也加下
