### ISSUE TITLE
小爱音箱pro运行成功了，发现2个最大的问题

### ISSUE THREAD

**Issue by gygy** [yihong0618/xiaogpt#176]
1.  使用命令行：python xiaogpt.py --config config.json --use_chatgpt_api --enable_edge_tts
    config.json 文件内容如下：
{
    "hardware": "LX06",
    "account": "XXXX",
    "password": "xxxxx",
    "openai_key": "sk-xxxx",
    "cookie": "",
    "mi_did": "",
    "use_command": true,
    "mute_xiaoai": true,
    "verbose": false,
    "bot": "gpt3",
    "enable_edge_tts": true,
    "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
    "keyword": ["帮我", "请回答"],
    "start_conversation": "开始持续对话",
    "end_conversation": "结束持续对话",
    "stream": true
}

使用以上命令，运行成功了，最大的2个问题：

1. GPT 使用了use_chatgpt_api，GPT 应该版本是3.5. 但实际测试：这个GPT 太弱，感觉就是2.0的水平，甚至1.0水平。和网页对比，目前音箱这个GPT有点弱智。 看看是我设置的问题吗？
   另外，建议通过ChatGPTUnofficialProxyAPI支持 OPENAI_ACCESS_TOKEN，这个和GPT网页版体验是一样的。 
3. 小爱音箱pro 硬件不支持连续对话。

**Comment by gygy** [comment]
ChatGPTAPI(gpt-3.5-turbo-0301)   
ChatGPTUnofficialProxyAPI(网页 accessToken)
建议能支持以上2种模式。初步使用，GPT还没有达到gpt-3.5-turbo-0301的水平。

**Comment by yihong0618** [comment]
1. 不会支持，因为可能封号（曾经是支持的，你可以切到之前的 commit)
2. 你可以使用开始持续对话。

**Comment by gygy** [comment]
> 

2. 应该是硬件不支持。每次使用：请回答 + 开始持续对话， 失去了音箱方便的意义了。
1. 在web项目上面，我一直用ChatGPTUnofficialProxyAPI，没封号。这种方式是最聪明的，其次是ChatGPTAPI(gpt-3.5-turbo-0301)  。习惯了这个聪明的方式，再用目前音箱这种方式，显得回答太笨了，差距有点大。
