### ISSUE TITLE
程序能正常运行，但无法监听到对话

### ISSUE THREAD

**Issue by janewu77** [yihong0618/xiaogpt#179]
micli list 
micli mina 
可以正常运行。

程序也显示它在监听，但什么也没捕获到。 

大概2小时之前是能正常使用的。 中间我好象手欠在小米APP里点了一下升级。
再后来，它就只是在监听，再也没捕获到聊天了。

设备是LX06.

**Comment by yihong0618** [comment]
重启加上 --verbose 看看有报错么

**Comment by yhwymy** [comment]
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api2.mina.mi.com:443 ssl:default [Network is unreachable]
Exception on login {username}: Cannot connect to host api2.mina.mi.com:443 ssl:default [Connection reset by peer]

**Comment by yhwymy** [comment]
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api2.mina.mi.com:443 ssl:default [Network is unreachable] Exception on login {username}: Cannot connect to host api2.mina.mi.com:443 ssl:default [Connection reset by peer]

我把那个异步创建的 poll_latest_ask任务改成直接执行了，就报这个错了。

**Comment by yhwymy** [comment]
直接ping 端口是没问题的。

**Comment by janewu77** [comment]
> 
我开了verbose的。一直在监听，很正常，没有其他抛错。
 看上去就是没有拿到对话记录。

**Comment by yihong0618** [comment]
@janewu77 打开小爱音箱的 app 看看里面是否有？

**Comment by yhwymy** [comment]
有的，我和他一样的症状，也是周六上午还测试好使，下午就不行了，后来调试代码见我上面那个报错，dockerfile方式部署也是报这个 minaservice 报错。

**Comment by yihong0618** [comment]
有可能是小米增加了风控，@janewu77 你是在 cli 跑的么？

**Comment by janewu77** [comment]
> 

对。我用命令行跑的。
python3 xiaogpt.py --config xiao_config.json
看上去一切正常。这中间我也没改动过什么， 唯一变化的，就是我中间把音箱升了一下级。

**Comment by yihong0618** [comment]
手动参考 miservice README（这个项目 Readme 里有链接 看看能 tts 么

**Comment by yihong0618** [comment]
如果还是不行得尝试抓包了

**Comment by Sswordq** [comment]
我家里两个小爱音响pro，一开始我用音响A，死活没反应，就是拿不到对话数据，结果化成问音响B，did还是A的居然回答了，我把did改成B的也会回答，感觉有bug，A和B的都取读取B的了；猜测是不是did根本就没用，直接读取的一个类似默认设备之类的

**Comment by yihong0618** [comment]
> 我家里两个小爱音响pro，一开始我用音响A，死活没反应，就是拿不到对话数据，结果化成问音响B，did还是A的居然回答了，我把did改成B的也会回答，感觉有bug，A和B的都取读取B的了；猜测是不是did根本就没用，直接读取的一个类似默认设备之类的

是。。。did 确实在这里没用到，我程序拿的是型号相同的第一个，明天改一下

**Comment by stenlylee** [comment]
遇到一样的问题，我有两个lx06，都不在一个地理位置，默认获取的是第一个，没有反应。代码改成强制获取另外一个后正常。

**Comment by yihong0618** [comment]
@stenlylee 今晚试试修复。。。

**Comment by yihong0618** [comment]
@all 大概率是两个同型号的小爱，我这里没做好。
PR 这个版本会修复
