### ISSUE TITLE
关于 stop_if_xiaoai_is_playing 逻辑的疑问

### ISSUE THREAD

**Issue by tars-sh** [yihong0618/xiaogpt#18]
1. 在get_last_timestamp_and_record之前；执行了await self.stop_if_xiaoai_is_playing() 为什么要执行这个stop动作呢？
2. 另外在执行完gpt任务后，会持续查询 self.get_if_xiaoai_is_playing() 并sleep，这里的作用是？

**Comment by yihong0618** [comment]
需要你自己研究

**Comment by tars-sh** [comment]
嗯，主要我现在小爱同学不在身边，不知道它是不是在说话😂，等到时回家再试试这里的逻辑

**Comment by yihong0618** [comment]
代码逻辑问题需要你自己搞懂，我没有太多精力回答抱歉。
