### ISSUE TITLE
程序运行正常，但效果与参数不匹配

### ISSUE THREAD

**Issue by deadjoker** [yihong0618/xiaogpt#181]
我用的`python3 xiaogpt.py --hardware L05C  --mute_xiaoai --use_gpt3`启动的，期望只得到gpt的回答，但事实是只得到了小爱的回答，程序没有任何报错，console里显示了我的提问，以及小爱和gpt3的回答。
这个是我的用法不正确么

**Comment by yihong0618** [comment]
@deadjoker 先确保 micli 能 tts
你可能需要加上 --use_command

**Comment by deadjoker** [comment]
1. 如何确定micli能tts，是用那个miservice的micli么，help里没有看到相关的参数。是不是直接操作音箱说话，如果能说就是支持tts？
2. 无论是否支持tts，是不是在xiaogpt.py启动时，加上`--use_command`都可行了。需要等周末才能再测试了

**Comment by deadjoker** [comment]
嗯，我看他那个里提到tts的就是直接命令行操作音箱说话 `micli.py 5 您好`
只要能说话就是支持吧

**Comment by yihong0618** [comment]
是的

**Comment by deadjoker** [comment]
ok thanks
我回去试一下先
