### ISSUE TITLE
Edge TTS not available inside a container

### ISSUE THREAD

**Issue by frostming** [yihong0618/xiaogpt#182]
现在Edge TTS的实现方式是暴露一个本地静态文件服务，把URL传给小爱播放。如果在容器中，这个随机端口不一定映射出来了。

**Comment by yihong0618** [comment]
> 这个服务按理也是跑在container里面

但端口不一定映射出来

**Comment by frostming** [comment]
> 这个服务按理也是跑在container里面

有两个问题：
1. 端口映射
2. 容器内构造URL时得用host IP，现在的get local ip的方式不适用于容器内
