### ISSUE TITLE
代理一直显示不支持是什么原因

### ISSUE THREAD

**Issue by winsongg** [yihong0618/xiaogpt#185]
按照教程，连接gpt代理那里一直不行，我写了个程序测试那个端口是没问题的，可以访问到外网，是什么原因呢

显示：HTTPS proxies https://127.0.0.1:33210 are not supported, ignoring

**Comment by PJovy** [comment]
尝试一下 `http` 作为 scheme。如  `http//127.0.0.1:33210/`

@winsongg
