### ISSUE TITLE
执行pip install -U xiaogpt报错

### ISSUE THREAD

**Issue by luoly601** [yihong0618/xiaogpt#188]
![image](https://user-images.githubusercontent.com/96689189/228485634-38d70c3b-b54a-42ca-8d22-e667f0a54f36.png)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement xiaogpt (from versions: none)
ERROR: No matching distribution found for xiaogpt

**Comment by yihong0618** [comment]
you are using python2.7

try;
install python3 
then
pip3 install -U xiaogpt
