### ISSUE TITLE
关于 conversation_id 的疑问

### ISSUE THREAD

**Issue by tars-sh** [yihong0618/xiaogpt#19]
1. conversation_id 这是可以自己任意指定一个值吗？还是需要去哪里生成呢？
2. 如果一直使用相同的 conversation_id，会不会导致会话记录越来越长，消耗的token也越来越多呢？这里建议如何维护呢？定期更换吗，比如用当天的日期作 conversation_id，每天变一个？

**Comment by yihong0618** [comment]
1. 去网页找
2. 你可以自己 DIY

**Comment by yihong0618** [comment]
chatgpt 网页里找，2. 不会。

**Comment by yihong0618** [comment]
另外有些 issue 以外的问题我不会那么及时的回答，精力有限，抱歉。

**Comment by tars-sh** [comment]
哦哦，没事哈，理解理解，感谢！
