### ISSUE TITLE
小爱音箱型号疑问

### ISSUE THREAD

**Issue by feijibang** [yihong0618/xiaogpt#192]
请问是否支持L15A（小米ai音箱二代）？config.py没有该型号，但看过有视频用L15A，小白不是很懂

**Comment by yihong0618** [comment]
micli nina

**Comment by yihong0618** [comment]
我今天尝试加下，但是我没有设备，没法测试。

**Comment by yihong0618** [comment]
@feijibang 加了，你用 --hardware L15A 试试？

**Comment by feijibang** [comment]
> @feijibang 加了，你用 --hardware L15A 试试？

好的，谢谢，请问是要重新安装一次xiaogpt吗

**Comment by yihong0618** [comment]
pip install -U xiaogpt
