### ISSUE TITLE
GPT回答出错 'NoneType' object has no attribute 'get_extra_info'

### ISSUE THREAD

**Issue by jiangkunoa** [yihong0618/xiaogpt#193]
收到了这个错误，代理应该是可以的 用网页能打开gpt窗口正常对话

**Comment by yihong0618** [comment]
应该是 openai 那边的问题
pip install -U openai 试试

**Comment by jiangkunoa** [comment]
> 应该是 openai 那边的问题 pip install -U openai 试试

感谢建议，但这目前没有用。我看看其他方法
