### ISSUE TITLE
一切正常，没任何报错， 但是也没任何效果

### ISSUE THREAD

**Issue by tanaer** [yihong0618/xiaogpt#194]
![image](https://user-images.githubusercontent.com/3828685/229132046-61bd4910-7d31-439c-8c48-7ea7bd90586e.png)

一切正常，没任何报错， 但是也没任何效果。。 

windows 环境。

{
    "hardware": "L07A",
    "account": "6666666",
    "password": "xxxx",
    "openai_key": "sk-1xxxxxxxxxxxxxxxx",
    "cookie": "",
    "mi_did": "247559999",
    "use_command": true,
    "mute_xiaoai": true,
    "verbose": true,
    "bot": "chatgptapi",
    "enable_edge_tts": true,
    "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
    "keyword": ["帮我", "请回答"],
    "start_conversation": "开始持续对话",
    "end_conversation": "结束持续对话",
    "stream": true,
    "proxy": "127.0.0.1:7891",
    "gpt_options": {}
}

 是我做错了什么？

**Comment by yihong0618** [comment]
很可能最新版拿不到历史了，我研究一下。

**Comment by tanaer** [comment]
我用micli.py

micli.py list
micli.py spec xiaomi.wifispeaker.lx04

都可以
但是Do Action ， set props get props 都不行

比如
python micli.py 2=#60

python micli.py 5-4 查询天气

执行就会把默认的帮助提示打印一遍

**Comment by yihong0618** [comment]
你跟他说帮我回答今天天气怎样是没效果的？

**Comment by yihong0618** [comment]
@tanaer 我这边刚刚测了下，没问题。

@frostming 好像不少人遇到，没拿到小爱的历史
![image](https://user-images.githubusercontent.com/15976103/229136782-b5dc2ad8-448c-4afb-b5b1-aa7847ac3fd7.png)

**Comment by tanaer** [comment]
> 
一会行 ，一会不行  刚才有两次行了。  python 停掉再启动，又不行了。  有点懵~

**Comment by yihong0618** [comment]
就是成功过？

**Comment by yihong0618** [comment]
看起来是网络问题，我们也查一下这两天。

**Comment by yihong0618** [comment]
@tanaer 如果你找到问题所在和解决方案，PR welcome 哈

**Comment by yihong0618** [comment]
现在猜测是有多个同型号的小爱
@qssq1 你拉下最新代码试试？

**Comment by yihong0618** [comment]
没关系
你 export did (参考 README)
为你当前的小爱，再跑。

**Comment by yihong0618** [comment]
然后别忘了改 hardware

**Comment by zhusjfaker** [comment]
@lozn00 
``` sh
$: ./micli.py -v 5-5 关闭开关
https://api.io.mi.com/app/miotspec/action {'_nonce': 'khQkeIMj9z0BrxLx', 'data': '{"params": {"did": "545137194", "siid": 5, "aiid": 5, "in": ["\\u5173\\u95ed\\u5f00\\u5173"]}}', 'signature': '7JSbkpTeWgGjSVCStuCddV5fU3hakAnqWBmZREJRQ/I='}
-704220025 
```
@yihong0618 
能问下这个问题怎么解吗

**Comment by zhusjfaker** [comment]
我也报 这个 错误码 查不到 解决办法 
```sh
$:  ./micli.py spec xiaomi.wifispeaker.lx06

# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:2

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rw
    Mute = 2  # bool  # rw

Play_Control = 3
    _Playing_State = 1  # uint8  # n

    _Play = 1
    _Pause = 2
    _Next = 3
    _Previous = 4

Microphone = 4
    Mute = 1  # bool  # rw

Intelligent_Speaker = 5
    _Text_Content = 1
    _Silent_Execution = 2  # bool
    Sleep_Mode = 3  # bool  # rwn
    Audio_Id = 4  # rn

    _Play_Text = 1  # in=[1]
    _Play_Music = 2
    _Wake_Up = 3
    _Play_Radio = 4
    _Execute_Text_Directive = 5  # in=[1, 2]

Clock = 6

    _Stop_Alarm = 1

Speaker_Volume
    MIN = 6
    MAX = 100

Play_Control_Playing_State
    Stop = 0
    Playing = 1
    Pause = 2
```

另外我在 nodred 里调用 miot call_service  -> Execute_Text_Directive  小爱同学 是可以直接唤醒音箱的 不知道 为啥换个皮就不行了。。

**Comment by yihong0618** [comment]
> 我也报 这个 错误码 查不到 解决办法 
> 
> ```sh
> 
> $:  ./micli.py spec xiaomi.wifispeaker.lx06
> 
> 
> 
> # Generated by https://github.com/Yonsm/MiService
> 
> # http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:2
> 
> 
> 
> Device_Information = 1
> 
>     Device_Manufacturer = 1
> 
>     Device_Model = 2
> 
>     Device_Serial_Number = 3
> 
>     Current_Firmware_Version = 4
> 
> 
> 
> Speaker = 2
> 
>     Volume = 1  # uint8  # rw
> 
>     Mute = 2  # bool  # rw
> 
> 
> 
> Play_Control = 3
> 
>     _Playing_State = 1  # uint8  # n
> 
> 
> 
>     _Play = 1
> 
>     _Pause = 2
> 
>     _Next = 3
> 
>     _Previous = 4
> 
> 
> 
> Microphone = 4
> 
>     Mute = 1  # bool  # rw
> 
> 
> 
> Intelligent_Speaker = 5
> 
>     _Text_Content = 1
> 
>     _Silent_Execution = 2  # bool
> 
>     Sleep_Mode = 3  # bool  # rwn
> 
>     Audio_Id = 4  # rn
> 
> 
> 
>     _Play_Text = 1  # in=[1]
> 
>     _Play_Music = 2
> 
>     _Wake_Up = 3
> 
>     _Play_Radio = 4
> 
>     _Execute_Text_Directive = 5  # in=[1, 2]
> 
> 
> 
> Clock = 6
> 
> 
> 
>     _Stop_Alarm = 1
> 
> 
> 
> Speaker_Volume
> 
>     MIN = 6
> 
>     MAX = 100
> 
> 
> 
> Play_Control_Playing_State
> 
>     Stop = 0
> 
>     Playing = 1
> 
>     Pause = 2
> 
> ```
> 
> 
> 
> 另外我在 nodred 里调用 miot call_service  -> Execute_Text_Directive  小爱同学 是可以直接唤醒音箱的 不知道 为啥换个皮就不行了。。

你之前不是好用么
