### ISSUE TITLE
关于型号L05C无法禁止小爱发音、问题都变为"?"

### ISSUE THREAD

**Issue by codingbylch** [yihong0618/xiaogpt#196]
1. 无法禁止小爱发音，以下代码设置为True无效：
```python
mute_xiaoai: bool = True
```
2. 设置`use_command`为`True`后，问题变为"?"：
![image](https://user-images.githubusercontent.com/17738529/229198021-0daa1e7a-d8ce-4b0a-82ea-f838c31f568a.png)

**Comment by yihong0618** [comment]
L05C 好像法 mute 小爱，参考 readme

**Comment by codingbylch** [comment]
> L05C 好像法 mute 小爱，参考 readme

我已经修改了默认项：`mute_xiaoai=True`为True

**Comment by yihong0618** [comment]
我指的是硬件不能
