### ISSUE TITLE
使用 EdgeGPT 写 bing chat 的 bot，不知道 ask_stream 该如何实现。

### ISSUE THREAD

**Issue by hanxi** [yihong0618/xiaogpt#197]
代码： https://github.com/hanxi/xiaogpt/blob/main/xiaogpt/bot/edgegpt_bot.py

已经可以使用 ask ，但是 ask_stream 没跑通。能否帮忙看看 ask_stream 改如何实现？ 

EdgeGPT 地址： https://github.com/acheong08/EdgeGPT

**Comment by yihong0618** [comment]
我。。。还没 edge 的资格
@frostming can you help～(^-^)

**Comment by frostming** [comment]
edge gpt 本身支持 stream mode: https://github.com/acheong08/EdgeGPT/blob/da5a8f9bacad51513fa6a07fe7e40def49e16572/src/EdgeGPT.py#LL364C22-L364C22

把这个generator对接到ask_stream就可以，具体需要你自己尝试和研究，抱歉无法一一指导，如果遇到困难可以先留空，先把现有的整理PR
