### ISSUE TITLE
型号S12设备不支持，提示：Do not support chatgpt

### ISSUE THREAD

**Issue by flyubuntu** [yihong0618/xiaogpt#198]
设备型号S12，一通配置结果不支持，查了config配置文件，好像不支持。
支持型号如下：
 "LX06": ("5-1", "5-5"),
    "L05B": ("5-3", "5-4"),
    "S12A": ("5-1", "5-5"),
    "LX01": ("5-1", "5-5"),
    "L06A": ("5-1", "5-5"),
    "LX04": ("5-1", "5-4"),
    "L05C": ("5-3", "5-4"),
    "L17A": ("7-3", "5-4"),
    "X08E": ("7-3", "5-4"),
    "LX05A": ("5-1", "5-5"),  # 小爱红外版
    "LX5A": ("5-1", "5-5"),  # 小爱红外版
    "L07A": ("5-1", "5-5"),  # Redmi小爱音箱Play(l7a)
    "L07A": ("5-1", "5-5"),  # Redmi小爱音箱Play(l7a)
    "L15A": ("7-1", "7-4"),

**Comment by yihong0618** [comment]
你可以查下 spec 然后加在 config 里

**Comment by flyubuntu** [comment]
能说具体点嘛？怎么查询

**Comment by yihong0618** [comment]
参考这个 readme

https://github.com/yihong0618/MiService

**Comment by flyubuntu** [comment]
mcl@Blackly:~$ micli spec xiaomi.wifispeaker.lx04
# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx04:2

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rw
    Mute = 2  # bool  # rw

Play_Control = 3
    _Playing_State = 1  # uint8  # n

    _Play = 1
    _Pause = 2
    _Next = 3
    _Previous = 4

Microphone = 4
    Mute = 1  # bool  # rw

Intelligent_Speaker = 5
    _Text_Content = 1
    _Silent_Execution = 2  # uint8
    Sleep_Mode = 3  # bool  # rwn
    Audio_Id = 4  # rn

    _Play_Text = 1  # in=[1]
    _Wake_Up = 2  # in=[1]
    _Play_Radio = 3
    _Execute_Text_Directive = 4  # in=[1, 2]

Clock = 6

    _Stop_Alarm = 1

Speaker_Volume
    MIN = 5
    MAX = 100

Play_Control_Playing_State
    Stop = 0
    Playing = 1
    Pause = 2

Intelligent_Speaker_Silent_Execution
    On = 0
    Off = 1

**Comment by flyubuntu** [comment]
数据如下，怎么提取呢？
mcl@Blackly:~$ micli spec xiaomi.wifispeaker.lx04
# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx04:2

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rw
    Mute = 2  # bool  # rw

Play_Control = 3
    _Playing_State = 1  # uint8  # n

    _Play = 1
    _Pause = 2
    _Next = 3
    _Previous = 4

Microphone = 4
    Mute = 1  # bool  # rw

Intelligent_Speaker = 5
    _Text_Content = 1
    _Silent_Execution = 2  # uint8
    Sleep_Mode = 3  # bool  # rwn
    Audio_Id = 4  # rn

    _Play_Text = 1  # in=[1]
    _Wake_Up = 2  # in=[1]
    _Play_Radio = 3
    _Execute_Text_Directive = 4  # in=[1, 2]

Clock = 6

    _Stop_Alarm = 1

Speaker_Volume
    MIN = 5
    MAX = 100

Play_Control_Playing_State
    Stop = 0
    Playing = 1
    Pause = 2

Intelligent_Speaker_Silent_Execution
    On = 0
    Off = 1

**Comment by frostming** [comment]
> mcl@Blackly:~$ micli spec xiaomi.wifispeaker.lx04

这个命令里最后一部分lx04是型号，你要换成自己的型号

**Comment by flyubuntu** [comment]
最新数据如下：
mcl@Blackly:~/.local/lib/python3.8/site-packages/xiaogpt$ micli spec xiaomi.wifispeaker.s12
# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-s12:2

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rw
    Mute = 2  # bool  # rw

Microphone = 3
    Mute = 1  # bool  # rw

Play_Control = 4
    _Playing_State = 1  # uint8  # n

    _Pause = 1
    _Play = 2
    _Next = 3
    _Previous = 4

Intelligent_Speaker = 5
    _Text_Content = 1
    _Silent_Execution = 2  # bool
    Sleep_Mode = 3  # bool  # rwn
    Audio_Id = 4  # rn

    _Play_Text = 1  # in=[1]
    _Play_Music = 2
    _Wake_Up = 3
    _Play_Radio = 4
    _Execute_Text_Directive = 5  # in=[1, 2]

Clock = 6

    _Stop_Alarm = 1

Speaker_Volume
    MIN = 1
    MAX = 100

Play_Control_Playing_State
    Stop = 0
    Playing = 1
    Pause = 2

**Comment by frostming** [comment]
这个错误和你分析的原因不匹配，Do not support chatgpt不是设备问题，是你的 bot没选对，只能是 gpt3 或者 chatgptapi

设备应该是支持的，不需要改任何东西

**Comment by yihong0618** [comment]
先关了哈，有问题随时再打开

**Comment by gaidan1983** [comment]
> 设备型号S12，一通配置结果不支持，查了config配置文件，好像不支持。 支持型号如下： "LX06": ("5-1", "5-5"), "L05B": ("5-3", "5-4"), "S12A": ("5-1", "5-5"), "LX01": ("5-1", "5-5"), "L06A": ("5-1", "5-5"), "LX04": ("5-1", "5-4"), "L05C": ("5-3", "5-4"), "L17A": ("7-3", "5-4"), "X08E": ("7-3", "5-4"), "LX05A": ("5-1", "5-5"), # 小爱红外版 "LX5A": ("5-1", "5-5"), # 小爱红外版 "L07A": ("5-1", "5-5"), # Redmi小爱音箱Play(l7a) "L07A": ("5-1", "5-5"), # Redmi小爱音箱Play(l7a) "L15A": ("7-1", "7-4"),

在config.py中list后面加上"S12": ("5-1", "5-5"), 即可，注意别忘了再输入一下 export MI_DID=XXXX 然后再 python3 xiaogpt.py --hardware S12 --mute_xiaoai --use_chatgpt_api

**Comment by yihong0618** [comment]
@gaidan1983 谢谢
