### ISSUE TITLE
使用问题交流

### ISSUE THREAD

**Issue by iamsk** [yihong0618/xiaogpt#2]
1. 循环监听mi.com记录是否存在被ban?
2. 是否存在重复响应，小米自己响应一次，chatgpt再响应一次？
3. 实现开发者技能是否可行？缺点是需要先进入技能

**Comment by yihong0618** [comment]
1. 目前不会，有些 hass 在用，但是我觉得不应该滥用（而且目前抓包方案其实跑不了多久，cookie 会过期）
2. 是的，我觉得合理，还能对比，我想到的方案是可以控制 xiaoai 声音其实小爱响应了但声音是 0 然后我们加大音量只听 chatgpt 的
3. 可行，但是本质上 chatgpt 需要梯子，小米理论不会通过，其它方式接入技能没问题。

**Comment by yihong0618** [comment]
我在尝试不用抓包搞，有可能能搞定。

**Comment by iamsk** [comment]
> 1. 目前不会，有些 hass 在用，但是我觉得不应该滥用（而且目前抓包方案其实跑不了多久，cookie 会过期）
过期的话，hass体验会很差，国内服务还是不够开放
> 2. 是的，我觉得合理，还能对比，我想到的方案是可以控制 xiaoai 声音其实小爱响应了但声音是 0 然后我们加大音量只听 chatgpt 的
天才，只针对需要chatgpt回答的，先在请求前置零，哈哈
> 3. 可行，但是本质上 chatgpt 需要梯子，小米理论不会通过，其它方式接入技能没问题。
可以包装成国内服务，转发

**Comment by yihong0618** [comment]
不用抓包了

**Comment by yihong0618** [comment]
@iamsk 用我设想的实现了 mute xiaoai 回答

1. 升级一下 `pip install -U git+https://github.com/yihong0618/MiService`
2. 启动时候用 --mute_xiaomi
