### ISSUE TITLE
add hardware model

### ISSUE THREAD

**Issue by micele00l** [yihong0618/xiaogpt#20]
L06A

**Comment by yihong0618** [comment]
能提供更多细节么？
它的 tts 指令是？

**Comment by micele00l** [comment]
应该是添加这个
"L06A": "5-1"

**Comment by fengyie007** [comment]
再增加一个     "LX04": "5-1"

**Comment by yihong0618** [comment]
> 再增加一个 "LX04": "5-1"，但这个发音用text_to_speech好像不行，micli命令可以

这块逻辑我可能得改下。

**Comment by yihong0618** [comment]
> 再增加一个 "LX04": "5-1"，但这个发音用text_to_speech好像不行，micli命令可以

你现在能运行么 用 LX04

**Comment by yihong0618** [comment]
> 再增加一个     "LX04": "5-1"，但这个发音用text_to_speech好像不行，micli命令可以

你有兴趣提个 PR 把这俩加上么
