### ISSUE TITLE
无法彻底禁言小爱的回答

### ISSUE THREAD

**Issue by theharveyz** [yihong0618/xiaogpt#200]
实际用下来，发现无法快速禁止小爱的回答，总是会读一段，这里有什么办法吗？

**Comment by yihong0618** [comment]
有办法，改代码里的 sleep 但不建议，会频繁请求。你可以自己 DIY 但本项目代码不会更改，抱歉

**Comment by yihong0618** [comment]
关了哈先
可以参考这个 https://github.com/yihong0618/xiaogpt/blob/main/xiaogpt/xiaogpt.py#L101 让它不 sleep
但不建议一直跑（可能被封号）
