### ISSUE TITLE
只能使用config型号字典里面的小爱型号吗？京东的小爱play lx05 型号的支持吗？

### ISSUE THREAD

**Issue by PeiZhangNEU** [yihong0618/xiaogpt#202]

**Comment by frostming** [comment]
这个字典并非穷尽的，并且我们提供了一个缺省值，支持大部分未列出的设备：
https://github.com/yihong0618/xiaogpt/blob/0810891df66ec1f358ae39aa9b5af6796dc9d464/xiaogpt/config.py#L43

比如你的LX05，用这个默认配置就足够了，你应该先试过，再提问
