### ISSUE TITLE
有什么办法不让小爱同学原生回复，而是直接调用GPT回复

### ISSUE THREAD

**Issue by SalterYu** [yihong0618/xiaogpt#205]
1. 有什么办法不让小爱同学原生回复，而是直接调用GPT回复？
2. 使用mute_xiaoai指令也是有延迟的，小爱会先说一句话但话说到一半就不说话了。
3. use_commad不知道是什么意思，也不知道怎么使用，有没有相关指令的文档呀？

**Comment by yihong0618** [comment]
1. 有办法但不建议彻底禁止
2. 跟网络有关
3. use_command 目前是针对特定型号的

https://github.com/yihong0618/xiaogpt/issues/200

**Comment by yihong0618** [comment]
和 200 重复，并且本项目不会提供彻底禁止小爱回答的方式，先关了哈
