### ISSUE TITLE
小爱音箱的账号和密码，是指小爱开放平台的APIKEY吗

### ISSUE THREAD

**Issue by jjiikkkk** [yihong0618/xiaogpt#207]
小爱音箱的账号和密码，是指小爱开放平台的APIKEY吗

**Comment by yihong0618** [comment]
就是账号和密码。

**Comment by jjiikkkk** [comment]
可是我测试了 怎么老是说我的账号和密码不对呢

**Comment by jjiikkkk** [comment]
账号是那个右上方的头像ID，密码不是登陆的密码吗，总是说不对，奇怪了

**Comment by yihong0618** [comment]
邮箱或 id 密码就是你的密码。登陆小米账号的。

**Comment by jjiikkkk** [comment]
那ID，是手机号，还是邮箱，还是小米分配的那个数字呢

**Comment by frostming** [comment]
> 那ID，是手机号，还是邮箱，还是小米分配的那个数字呢

都尝试一下，我经验优先试数字账号。总之是登录小米平台用的账号密码。

**Comment by jjiikkkk** [comment]
确定不是小爱的API KEY?

**Comment by Timoshao** [comment]
我的账号有特殊字符@ # 一直验证不通过

**Comment by yihong0618** [comment]
有特殊字符的话整个密码用单引号包裹

**Comment by jjiikkkk** [comment]
我没有特殊字符，就是=直接写的，是不是也用单引号包裹

**Comment by Timoshao** [comment]
> 有特殊字符的话整个密码用单引号包裹

docker run -e OPENAI_API_KEY=abc yihong0618/xiaogpt --account=13501 --password="wang###" --hardware=LX05 --use_chatgpt_api
大概这样的 替换了正确的账号和密码 但是还是提示账号错误。

**Comment by jjiikkkk** [comment]
不是这么写的吧，我觉得应该是=""  这样子试试，=‘’

**Comment by jjiikkkk** [comment]
请问一下 小米小爱的随身迷你音箱可以吗

**Comment by frostming** [comment]
无法语音唤醒的不行

**Comment by jjiikkkk** [comment]
小爱的APP有两个，一个是小爱同学，一个是小爱音箱，小爱音箱唤醒不了，但是小爱同学可以，小米小爱随身迷你音箱，这样是可以用的吗

**Comment by frostming** [comment]
我说的语音唤醒是你叫「小爱同学」音箱会响应，随身迷你音箱应该是不行的因为它不是随时待机（电池续航也不允许）

**Comment by jjiikkkk** [comment]
我看公众号上有个视频 有个人 是没有输入密码的，直接就是ID

**Comment by frostming** [comment]
> 我看公众号上有个视频 有个人 是没有输入密码的，直接就是ID

友情提示，登录账号密码后是有缓存的，其实下次是不用提供账号密码的

**Comment by jjiikkkk** [comment]
哦 懂了

**Comment by jjiikkkk** [comment]
我说的语音唤醒是你叫「小爱同学」音箱会响应，随身迷你音箱应该是不行的因为它不是随时待机（电池续航也不允许）。  但是喊他小爱同学，迷你音响是会响应 哎我在

**Comment by yihong0618** [comment]
@jjiikkkk 
你用 micli mina 能看到你的 mini 小爱么？

**Comment by jjiikkkk** [comment]
Exception on login None: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Error https://api.io.mi.com/app/home/device_list: Login failed
root@iZbp1fl3af51xt5mw5zz61Z:~/xiaogpt/MiService#  总是这样  是不是官方把接口堵死了

**Comment by jjiikkkk** [comment]
从国外的服务器换到国内的服务器 各种挖空心思，晕

**Comment by jjiikkkk** [comment]
哎，总是这样错 Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/miservice/miaccount.py", line 69, in login raise Exception(resp)

**Comment by jjiikkkk** [comment]
国内服务器，试了一整夜，还是这个样子，你们的方法是不是被和谐了啊  {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/home/lighthouse/.local/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Error https://api.io.mi.com/app/home/device_list: Login failed

**Comment by jjiikkkk** [comment]
换了三个人的代码来搞 就是过不去，而且我看到装了micli，太难搞了

**Comment by jjiikkkk** [comment]
这个账号和密码 不会要到小米手机里去认证的那种吧

**Comment by yihong0618** [comment]
你是国内注册的小米么

**Comment by frostming** [comment]
你登录过 https://account.xiaomi.com/ 吗？换IP或很久没登录会触发二次验证

**Comment by jjiikkkk** [comment]
肯定国内注册的小米啊，都是在国内的IP下登陆小米账户的，不会注册二次验证啊

**Comment by jjiikkkk** [comment]
啊疯掉了。腾讯云国内服务器，小米账号放手机里看到了 全部认证过来，身份证银行卡都绑定了，结果还是 Exception on login None: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/home/lighthouse/.local/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Error https://api.io.mi.com/app/home/device_list: Login failed           micli是安装的，天啦，这个真的没法搞了

**Comment by yihong0618** [comment]
有可能是腾讯云服务器的事儿。。。
你在本机上试试？

**Comment by jjiikkkk** [comment]
windows桌面啊 我用Ubuntu装的，windows桌面 我要看看自己会不会搞

**Comment by yihong0618** [comment]
可以试试 wsl

**Comment by jjiikkkk** [comment]
好像非常麻烦，如果是服务器的问题，那么国内那些比较有名的云服务器，基本都会出现这个账号验证的问题，是这个意思吧

**Comment by yihong0618** [comment]
是。其实 windows 也是行的，你本地也可以用 docker

**Comment by jjiikkkk** [comment]
那样太麻烦了 我不会用docker，还是wls吧 我试试
这个声音的跑流量，在云端服务器上，不消耗太多流量的吧

**Comment by jjiikkkk** [comment]
还要搞定从微软商店上下载 真的是一个套加一个套，好累

**Comment by jjiikkkk** [comment]
ssh和wls应该是不一样的吧，ssh仍然会账号密码通不过验证吧

**Comment by jjiikkkk** [comment]
本地的SSH 还是一样的报错

**Comment by jjiikkkk** [comment]
如果腾讯云后台在线验证拒绝，一样的IP和密码到了window上去就不受限吗？我再换个小米账号试试看
真的感觉你们的方法，是不是被限制了

**Comment by jjiikkkk** [comment]
我用了三个人github上的方法，基本上也是互相改造的，主要的问题都是小米账号过不去，而且有多个人也是过不去
从国外的云服务器换到了国内的云服务器，过不去
忙活了好几天了，线上的SSH，到本地的SSH，现在让我换linux for windows
都会出现micli的问题，都会出现path的问题，解决掉了，但是还是验证过去不，小米的账号都去小米手机里认证实名拍照和加了银行卡

**Comment by jjiikkkk** [comment]
已经用了四个人的代码，不是micli找不到，就是验证过不去，晕死

**Comment by jjiikkkk** [comment]
我想放弃了 太麻烦了

**Comment by jjiikkkk** [comment]
https://www.wutaijie.top/?p=422&load_id=1&share_token=f0f1fd2e-2145-4fcb-ad73-d9c3abc020df  这个人的是每次都少mcili，用那个PATH来改，没用还是缺，我都不记得我是怎么补上的了，好像是去python上安装的，晕乎乎的

**Comment by CrassusX** [comment]
安全吗？会泄密吗？
