### ISSUE TITLE
 配置GPT4后提示：multiple values for keyword argument  'model'

### ISSUE THREAD

**Issue by ChuangLee** [yihong0618/xiaogpt#208]
```
以下是GPT的回答: [04/05/23 08:57:38] ERROR    openai.api_resources.chat_completion xiaogpt.py:370
                             .ChatCompletion.acreate() got
                             multiple values for keyword argument
                             'model'
```
配置为：
`    "gpt_options": {"model":"gpt-4","temperature": 0.9,"top_p": 0.9}
`

**Comment by yihong0618** [comment]
不支持 gpt4 目前

**Comment by yihong0618** [comment]
不过 gpt-4 的 model 命名感觉不是这个吧

**Comment by ChuangLee** [comment]
> 不过 gpt-4 的 model 命名感觉不是这个吧
是得呀，gpt-4。 
我理解不是透传给OpenAI的么，为啥会不支持某个model。
“gpt-3.5-turbo” 支持么？

**Comment by ChuangLee** [comment]
> 不过 gpt-4 的 model 命名感觉不是这个吧

不过 gpt-4 的 model 命名感觉不是这个吧
是得呀，gpt-4。
我理解不是透传给OpenAI的么，为啥会不支持某个model。
“gpt-3.5-turbo” 支持么？

**Comment by frostming** [comment]
> > 不过 gpt-4 的 model 命名感觉不是这个吧
> 
> 是得呀，gpt-4。 我理解不是透传给OpenAI的么，为啥会不支持某个model。 “gpt-3.5-turbo” 支持么？

新版本已经修复了
