### ISSUE TITLE
登录验证失败

### ISSUE THREAD

**Issue by tars-sh** [yihong0618/xiaogpt#21]
请问这个如何解决呢？下午还能登录，密码这块没有动

Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}

**Comment by yihong0618** [comment]
看起来小米封了这个我明天再看一下。

**Comment by extraordinaryq** [comment]
Exception on login 182**: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "C:\Application\Anaconda\envs\miservice\lib\site-packages\miservice\miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}

用户名带不带双引号都试了，无论如何都登陆不上，关闭防火箱和vpn，请问这个是需要现申请开发者权限吗

**Comment by yihong0618** [comment]
请参照 README 确保 micli list 和 micli mina 可用

**Comment by tars-sh** [comment]
> 我这里测试了没问题。 可以试试用 `--account {account} --password {password}` 启动

好的，已解决
