### ISSUE TITLE
账号和密码的错误总是这样，无语

### ISSUE THREAD

**Issue by jjiikkkk** [yihong0618/xiaogpt#215]
Exception on login None: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/home/linux1/.local/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Error https://api.io.mi.com/app/home/device_list: Login failed
linux1@gongzhonghao-xiaomi:~/MiService$

**Comment by yihong0618** [comment]
#162

**Comment by wangsmile** [comment]
得用小米ID吧。
