### ISSUE TITLE
./‘'[p90[koik;lA“，；‘S；六个porkitpoqi-+’

### ISSUE THREAD

**Issue by yashuawu** [yihong0618/xiaogpt#22]

**Comment by yashuawu** [comment]
![image](https://user-images.githubusercontent.com/46616820/221349014-be5d0142-7a06-4b08-800b-3c6ac8869ce1.png)

**Comment by yihong0618** [comment]
@yashuawu 请检查 revChatGPT 的 config 格式，看看是不是多了个逗号
