### ISSUE TITLE
做了个chatgpt-api的proxy在config.json里应该怎么填？

### ISSUE THREAD

**Issue by huomqh** [yihong0618/xiaogpt#227]
按照项目https://github.com/x-dr/chatgptProxyAPI，自己通过CF搭了一个api的proxy，那么在config.json里是不是可以不配置代理的http，而把api的地址给改成自己的？具体应该怎么设置？

**Comment by Ya-chunJen** [comment]
有同样的问题，是proxy这个参数吗？

**Comment by frostming** [comment]
是 api_base
