### ISSUE TITLE
是不是国外的服务器 不能用这个项目啊

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#233]
是不是国外的服务器不能用这个项目啊，在国外的服务器用这个就报错
本地服务器就没问题

**Comment by ericshirs** [comment]
我在国外服务器上部署的，可以用。报错应该是其他原因导致的。
但是哪位大神能教教“如何守护进程”？

**Comment by yihong0618** [comment]
@ericshirs 搜索 nohup

@joe12801 不一定，有些会风控
