### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#234]
执行这个命令报错，不能识别这个命令 ecognized arguments: -p 9527:9527 -e XIAOGPT_HOSTNAME=192.168.2.112

docker run -v /root/xiaogpt:/config yihong0618/xiaogpt -p 9527:9527 -e XIAOGPT_HOSTNAME=192.168.2.112 --config=/config/config.json
![image](https://user-images.githubusercontent.com/70465495/233186959-14fdc9c3-2663-42c2-894f-54ee0808b404.png)

**Comment by joe12801** [comment]
问下chatgpt,他帮我改好，改成这样就可以

docker run -v /root/xiaogpt:/config --publish 9527:9527 --env XIAOGPT_HOSTNAME=192.168.2.112 yihong0618/xiaogpt --config=/config/config.json

**Comment by yihong0618** [comment]
chatgpt 牛逼！
