### ISSUE TITLE
报错： Error communicating with OpenAI

### ISSUE THREAD

**Issue by danranmmm** [yihong0618/xiaogpt#235]
问题：请回答天气
以下是小爱的回答: 西安雁塔明天小雨转阴，要带伞哦，10度到21度，降温5度，西风1级转西风3级，空气质量良。
以下是GPT的回答: GPT回答出错 Error communicating with OpenAI
为什么我的一直GPT报错链接不上啊，我美国服务器的节点，可以正常访问openAI和ChatGPT，我用的windows，把代理端口也改成允许的了，然后使用就一直报错 GPT回答出错 Error communicating with OpenAI，也没其他任何提示了

**Comment by yihong0618** [comment]
请确定 terminal 能访问
比如 curl google.com

**Comment by danranmmm** [comment]
> 请确定 terminal 能访问 比如 curl google.com

我是可以访问的

**Comment by danranmmm** [comment]
> 请确定 terminal 能访问 比如 curl google.com

刚才试了一下 挂着代理也访问不到，什么原因如何解决大佬

**Comment by yihong0618** [comment]
进入 python repl 
看看是否能调用 openai 接口试试？

**Comment by danranmmm** [comment]
> 进入 python repl 看看是否能调用 openai 接口试试？

已经尝试可以调用，一开始我使用小爱的时候报错
--------------------
问题：你是谁？
以下是小爱的回答:  你大哥
以下是GPT的回答: HTTPS proxies https://127.0.0.1:10809 are not supported, ignoring
GPT回答出错 Error communicating with OpenAI

然后我改了代理 set http_proxy=http://127.0.0.1:7890 & set https_proxy=http://127.0.0.1:7890 再用的时候就直接
GPT回答出错 Error communicating with OpenAI ，然后没有其他信息了

**Comment by yihong0618** [comment]
看起来是你的 ip 被 openai block 了

**Comment by longwayfather** [comment]
> 看起来是你的 ip 被 openai block 了

我出现同样的问题 但是测试了我自己用openai.ChatCompletion.create可以拿到答复

**Comment by woiweb** [comment]
问题：写一首诗？
以下是小爱的回答:  嗯哼~我先写首普通的诗热热身
以下是GPT的回答: 

GPT回答出错 Error communicating with OpenAI

直接 curl https://api.openai.com/v1/completions 是有反应的

`
 xiaogpt git:(main) curl https://api.openai.com/v1/completions -x socks5h://127.0.0.1:13659 -H Content-Type:application/json -H Authorization:"Bearer kkkkkkkkkkkkkkkk" -d '{"model":"text-davinci-003","prompt":"Say this is a test","temperature":0,"max_tokens":7}'

{"id":"cmpl-7NzDYtLHbEY53MSZ7CQXuXkYAcNFs","object":"text_completion","created":1685951220,"model":"text-davinci-003","choices":[{"text":"\n\nThis is indeed a test","index":0,"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":5,"completion_tokens":7,"total_tokens":12}}
`

**Comment by jokereven** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/73232691/f1241322-d683-47c5-945d-24a97d1786eb)

在 wsl 跑 proxy 得设置成 wsl 的 ip

**Comment by yihong0618** [comment]
> ![image](https://user-images.githubusercontent.com/73232691/248628675-f1241322-d683-47c5-945d-24a97d1786eb.png)
> 
> 在 wsl 跑 proxy 得设置成 wsl 的 ip

有兴趣提个 PR 加在 README 里么？

**Comment by jokereven** [comment]
正好没啥事，好。

**Comment by jokereven** [comment]
> > ![image](https://user-images.githubusercontent.com/73232691/248628675-f1241322-d683-47c5-945d-24a97d1786eb.png)
> > 在 wsl 跑 proxy 得设置成 wsl 的 ip
> 
> 有兴趣提个 PR 加在 README 里么？

![image](https://github.com/yihong0618/xiaogpt/assets/73232691/aba276d6-14d6-4a79-a4c9-a540759487f1)

加载注意这个位置吗?

**Comment by yihong0618** [comment]
可以。加在这没问题

**Comment by jokereven** [comment]
pr 已提
