### ISSUE TITLE
红米触屏小爱音响8接入后无法发出声音，查看config.py中并没有X08C的tts_command, wakeup_command代码，micli.py spec 情况如下

### ISSUE THREAD

**Issue by zhou51320** [yihong0618/xiaogpt#239]
这是x08c的spec结果
![1682105309115(1)](https://user-images.githubusercontent.com/37415456/233719118-c415543e-3389-4bec-8a0a-eb8f1461ddf9.jpg)
可以看到tts_command应该是3-1，实测可以发出声音，但是我在config.py添加"X08C": ("3-1", "3-2"),  还是无法发出声音
![1682105482559](https://user-images.githubusercontent.com/37415456/233719562-9c4e8a43-9b35-457a-a43b-ff08d6283440.jpg)
程序可以正常运行，但是X08C无法发出声音，请大佬帮忙看看
![1682105587744(1)](https://user-images.githubusercontent.com/37415456/233719991-6a385cf9-9bf1-470e-b5c3-9da397b35968.jpg)

**Comment by frostming** [comment]
是 ("3-1", "3-4")

用 `--use_command` 试试看

**Comment by zhou51320** [comment]
> 是 ("3-1", "3-5")
> 
> 用 `--use_command` 试试看

感谢，昨天后续测试忘了添加--use_command参数了，config.py添加"X08C": ("3-1", "3-2")，config.json设置了  "use_command": true,就可以了
