### ISSUE TITLE
小白 有点问题，安装requirements.txt  其他的都能安，miservice 提示不知道文件格式 失败了。

### ISSUE THREAD

**Issue by zlc000190** [yihong0618/xiaogpt#24]

**Comment by yihong0618** [comment]
请给出报错信息

**Comment by zlc000190** [comment]
ERROR: Command errored out with exit status 128: git clone -q https://github.com/yihong0618/MiService 'C:\Users\Administrator\AppData\Local\Temp\pip-req
-build-wh7_ut2h' Check the logs for full command output.
Check the logs for full command output.

**Comment by yihong0618** [comment]
需要安装 git 请搜索 git 怎么安装

**Comment by zlc000190** [comment]
哦， 我再搜搜，git都已经安装了，路径配了好几遍了，环境变量也配置了，报错也少了。刚开始报git 是否安装。 现在报这个。 按照描述应该是安装都没有问题了。

**Comment by yihong0618** [comment]
先确保能运行 git 
然后重新安装 reuirments

**Comment by zlc000190** [comment]
git 是正常的，能clone 
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
 
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 207: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by yihong0618** [comment]
我晚上看看，可能是 windows 有点问题

**Comment by zlc000190** [comment]
太感谢了

**Comment by zlc000190** [comment]
看来是miservice里面的这个 long_description=Path('README.md').read_text(),   readme.md 这个编码问题 

Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-jm_cvzn9\miservice_b3f0d6cff3c74927924e5e1cb9b26272\setup.py", line 25, in <module>
          long_description=Path('README.md').read_text(),
        File "d:\software\python3.8.9\lib\pathlib.py", line 1236, in read_text
          return f.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 194: illegal multibyte sequenc

**Comment by yihong0618** [comment]
OK 我晚上改改看，感觉 9点半能到家

**Comment by yihong0618** [comment]
@zlc000190  现在再试试？

**Comment by zlc000190** [comment]
好的 重新clone 吗

**Comment by zlc000190** [comment]
Running setup.py install for miservice ... done
Successfully installed miservice-2.0.2

**Comment by zlc000190** [comment]
成功

**Comment by yihong0618** [comment]
@zlc000190 现在没问题了，我这个 issue 关了哈

**Comment by zlc000190** [comment]
好的 大佬，非常感谢  抱拳抱拳
