### ISSUE TITLE
这套代码是否可以部署在服务器上？

### ISSUE THREAD

**Issue by sakyachen** [yihong0618/xiaogpt#240]
这样就不必我一直要开着电脑。

**Comment by frostming** [comment]
可以，也提供了docker image

但对服务器网络环境有要求，它要能直接访问到小米账户中心，必须不能被小米风控。

**Comment by sakyachen** [comment]
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_yKOqps4gU21xidmhAjol7IWeJ38nMT: Login failed

这是不是被小米屏蔽了...同样的部署在本地mac可以，在腾讯云windows服务器上就不行了。

**Comment by joe12801** [comment]
> Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_yKOqps4gU21xidmhAjol7IWeJ38nMT: Login failed
> 
> 这是不是被小米屏蔽了...同样的部署在本地mac可以，在腾讯云windows服务器上就不行了。

不可以的，我测试没有一个可以用的

**Comment by yihong0618** [comment]
你在本地可用就是没被屏蔽，但在腾讯云等地方会触发风控。

**Comment by yihong0618** [comment]
是的，按 issue 的评论来看，阿里云腾讯云都会触发风控

**Comment by ggwgit** [comment]
海外aws云可以吗？

**Comment by yihong0618** [comment]
应该不行得走代理

**Comment by arbraham** [comment]
> 应该不行得走代理
怎么走代理呢？跟你README里写得这个有关系吗?这个指得是什么意思呢?
"如果你遇到了墙需要用 Cloudflare Workers 替换 api_base 请使用 --api_base ${url} 来替换。 请注意，此处你输入的api应该是'https://xxxx/v1'的字样，域名需要用引号包裹"

**Comment by yihong0618** [comment]
不是，是一般的服务器会触发小米的风控

**Comment by arbraham** [comment]
如何判断到底是不是被小米风控了呢？ping小米的这几个域名都是通的。

在我本地浏览器打开https://account.xiaomi.com/pass/serviceLogin?sid=micoapi&_json=true可以直接看到一个jason返回，当有token时里面的结果是成功，删除了token后是登陆验证失败。

我在服务器上curl上面的URL的结果是
The URL has moved <a href="https://account.xiaomi.com/fe/service/login?sid=micoapi&qs=%253Fsid%253Dmicoapi&callback=https%3A%2F%2Fapi2.mina.mi.com%2Fsts&_sign=Eb5a9yiqv%2FBlDblYQpJn44d1Xv8%3D&serviceParam=%7B%22checkSafePhone%22%3Afalse%2C%22checkSafeAddress%22%3Afalse%2C%22lsrp_score%22%3A0.0%7D&showActiveX=false&theme=&needTheme=false&bizDeviceType=">here</a>
把这个URL拿到我本地浏览器打开，就到了小米登陆界面，点击登陆后，就出现HTTP ERROR 401界面。
这就是被风控了吗？

**Comment by yihong0618** [comment]
是

**Comment by arbraham** [comment]
好惨。

**Comment by sandae** [comment]
我用新加坡VPS也被拒绝，Exception: Error https://api2.mina.mi.com/admin/v2/devicxxxxxxxxxxxx: Login failed
Unclosed client session

**Comment by watchpoints** [comment]
不放在服务器上 ，本地电脑 不如直接使用相关搜索呢 。需要服务器
