### ISSUE TITLE
docker部署后正常延迟多秒回答，我的怎么有30秒左右啊

### ISSUE THREAD

**Issue by kk1906** [yihong0618/xiaogpt#241]
是不是只需要这一条命令

docker run -e OPENAI_API_KEY=<your-openapi-key> yihong0618/xiaogpt --account=<your-xiaomi-account> --password=<your-xiaomi-password> --hardware=<your-xiaomi-hardware> --use_chatgpt_api --mute_xiaoai

**Comment by yihong0618** [comment]
正常是 0.5s 你不用 docker 跑着试试？
