### ISSUE TITLE
小爱同学  【问GPT】 XXXXXXXXXXXX，结果触发两个功能一个是音箱自带功能随机有时候放音乐，一个是问GPT

### ISSUE THREAD

**Issue by CitrusMao** [yihong0618/xiaogpt#246]
怎么才能实现
1、唤醒小爱同学 
2、说出关键词
3、小爱同学回复有什么问题问GPT 然后等待输入（）
4、我说出要问的问题
5、小爱同学回复正在问GPT
6、TTS播放回答的文本

**Comment by yihong0618** [comment]
开始持续对话（跟小爱说）

**Comment by muzizongheng** [comment]
> 开始持续对话（跟小爱说）

这个持续对话， 是gpt的同一个主题吗？ 能不能那种我一个主题的可以反复问？

**Comment by yihong0618** [comment]
可以，你试试不就知道了么。。。

**Comment by muzizongheng** [comment]
> 可以，你试试不就知道了么。。。

试了，但感觉不是同一个主题。 类似下面的对话历史。
我：请扮演一个英语老师，我们练习英语对话。
gpt：好的， 请给个主题。
我：体育。
gpt：（巴拉巴拉讲了一堆体育的介绍，但是中文介绍的）

**Comment by yihong0618** [comment]
建议你更改下 prompt 试试，我在外面手头没有小爱无法测试抱歉
