### ISSUE TITLE
提问，是否有计划支持第三方代理chatApi实现免梯子的网络

### ISSUE THREAD

**Issue by axiong5500** [yihong0618/xiaogpt#248]
本人已经代理实现了chatgpt接口，请问如何执行命令？

**Comment by afan1123** [comment]
> 本人已经代理实现了chatgpt接口，请问如何执行命令？

![6fddcf25bd0ba98ef1f525836630f1c55cf51cc26c3177539557ce06f323ec19QzpcVXNlcnNcd2FuZ3FpblxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMTQ0MjI5NTEwMl92MlxJbWFnZUZpbGVzXDE2ODYxMTE1MzQ3MDNfMkJFMTZGOTAtRURDMi00NGE3LTk1RDItNEI1NUM0OTY2MDhELnBuZw==](https://github.com/yihong0618/xiaogpt/assets/66288342/60b8282c-1514-4f38-b2d9-95f7a168aad1)
按照这里的配置？
另外我想问问大佬怎么实现的代理😂

**Comment by axiong8080** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/21275254/f787381c-07b1-404e-ac9b-41a190d58e15)
想把这个位置的apikey替换成http链接

**Comment by yihong0618** [comment]
能再给一些细节么？我没用过代理接口

**Comment by 46fafa** [comment]
> 能再给一些细节么？我没用过代理接口

https://aigptx.top/?aff=uFpUl2Kf这是个专门做第三方ChatGPTapi代理

**Comment by icucuio** [comment]
我也遇到同样的问题

**Comment by thmono** [comment]
这个也是第三方api（https://openkey.cloud），希望能得到支持，希望能实现这个效果（https://web.chatboxai.app/），这样就免翻墙能用了
