### ISSUE TITLE
通过Acccess_token 接入 slack-claude 

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#250]
下面是参考代码
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/adapter/claude/slack.py

https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-claude

**Comment by yihong0618** [comment]
谢谢

**Comment by joe12801** [comment]
> 谢谢

有效时间，听说话是永久

**Comment by yihong0618** [comment]
后续会支持 claude
