### ISSUE TITLE
怎么让小爱同学停止回答。让GPT直接回答

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#251]
设置 "mute_xiaoai": true
还有小爱同学还说一个小部分。
我看别人根据你的项目改了。可以小爱不回答。说什么利用小米自定义的技能。
看下面视频的链接
https://www.douyin.com/video/7212243333274406177

**Comment by jjjyyyllll** [comment]
这个挺好的 进入XX模式

**Comment by yihong0618** [comment]
做到小爱完全不回答不难，但是就会一直请求拿 history 有封号的风险，所以我们不会这么做

**Comment by yihong0618** [comment]
啊可能我说错了，我研究下自定义技能

**Comment by chaoqunxie** [comment]
为啥小爱同学回答了一半，终端里面chatgpt回复了，但是小爱不会说chatgpt回复的内容

**Comment by yihong0618** [comment]
@chaoqunxie 有些型号需要加上 --use_command

**Comment by chaoqunxie** [comment]
已解决 我使用的是配置文件 use_command改成true就可以了

**Comment by yihong0618** [comment]
好的
