### ISSUE TITLE
小爱音箱无法被唤醒，求助各位大神

### ISSUE THREAD

**Issue by brettez** [yihong0618/xiaogpt#254]
我用windows server 2012安装的python3.11，可以启动，但是小爱音箱无法调用chatgpt，配置如下：
    hardware: str = "L05C"
    account: str = "*********"
    password: str ="***********"
    openai_key: str = "sk-********************************************"
    proxy: str | None = None
    mi_did: str ="***********"
    keyword: Iterable[str] = KEY_WORD
    change_prompt_keyword: Iterable[str] = CHANGE_PROMPT_KEY_WORD
    prompt: str = PROMPT
    mute_xiaoai: bool = False
    bot: str = "chatgpt"
    cookie: str = ""
    api_base: str | None = None
    deployment_id: str | None = None
    use_command: bool = False
    verbose: bool = False
    start_conversation: str = "开始持续对话"
    end_conversation: str = "结束持续对话"
    stream: bool = False
    enable_edge_tts: bool = False
    localhost: bool = True
    edge_tts_voice: str = "zh-CN-XiaoxiaoNeural"
    gpt_options: dict[str, Any] = field(default_factory=dict)
    bing_cookie_path: str = ""
    bing_cookies: dict | None = None

**Comment by naiximcn** [comment]
代理开了没 最好是开TUN模式 系统代理它不一定走 要开规则模式 OpenAI的用美国IP 小米服务的用大陆IP 小米服务不接受大陆外任何区域IP

**Comment by ggwgit** [comment]
> 代理开了没 最好是开TUN模式 系统代理它不一定走 要开规则模式 OpenAI的用美国IP 小米服务的用大陆IP 小米服务不接受大陆外任何区域IP

你的意思是不能将这个程序直接部署到国外服务器上？

**Comment by naiximcn** [comment]
差不多

> > 代理开了没 最好是开TUN模式 系统代理它不一定走 要开规则模式 OpenAI的用美国IP 小米服务的用大陆IP 小米服务不接受大陆外任何区域IP
> 
> 你的意思是不能将这个程序直接部署到国外服务器上？
