### ISSUE TITLE
连不上openai 和login faild

### ISSUE THREAD

**Issue by 6vision** [yihong0618/xiaogpt#256]
本地笔记本的wls可以执行到唤醒说出问题，但连不上openai，我配置了系统代理（微信机器人就可以正常连接使用）！换用阿里云国内的服务器也是到这一步，再换用国外的Azure服务器，就报错了login faild/////////怎么解决？？
![image](https://user-images.githubusercontent.com/38057450/236610136-35631c90-3bb9-4775-acd1-520a2754a5e8.png)
![image](https://user-images.githubusercontent.com/38057450/236610158-870a93ae-153c-4577-8f78-218010144fbc.png)

**Comment by yihong0618** [comment]
阿里云和国外服务器都会触发小米的风控

**Comment by 6vision** [comment]
> 阿里云和国外服务器都会触发小米的风控

大佬，阿里云的和我本地的wsl2都成功导入账户信息，唤醒小爱，得到小爱的回到，就是连不上openai，我也已经配置了系统代理（部署在wsl2的chatgpt微信机器人正常使用当中）！可否指导一下，哪里有问题

**Comment by 6vision** [comment]
感谢大佬，已成功在本地和阿里云服务器成功部署服务！！待我好好玩玩！

**Comment by yihong0618** [comment]
帅啊。能分享下怎么做的么？这样别的朋友也方便

**Comment by 6vision** [comment]
> 帅啊。能分享下怎么做的么？这样别的朋友也方便

好嘞，大佬！得空写个教程贴过来！主要readme部分我没看完，我设备是 L05C，然后一开始没使用use_command参数，其次是config文件配置的代理没生效，最后配置好代理就行了！关于服务器代理配置：1、[我自己手动安装clash的记录](https://www.wangpc.cc/software/wechat-on-bot/)。2、[使用GitHub项目](https://github.com/wanhebin/clash-for-linux)

**Comment by yihong0618** [comment]
@6vision 感谢，我稍后加在 README 里
