### ISSUE TITLE
docker 为什么一直无法pull xiaogpt的镜像呢？

### ISSUE THREAD

**Issue by terryxuwen** [yihong0618/xiaogpt#258]
docker pull yihong0618/xiaogpt
Using default tag: latest
Trying to pull repository docker.io/yihong0618/xiaogpt ... 
manifest for docker.io/yihong0618/xiaogpt:latest not found

设了国内镜像网站也没用。 去docker hub上去看都是在的，各种版本都有，也不存在网上说的没有 latest tag的问题，加版本号问题一样。
直接 docker search xiaogpt 也能看到是有的，但无论怎么pull都下不来，见鬼了。

**Comment by yihong0618** [comment]
试了下是没问题的。
本地 build 试试？

**Comment by terryxuwen** [comment]
除了docker pull之外还有其他什么方式不？有没有直接从docker hub网站上http下载才转到目标机器上的办法？
本地build是啥意思，有相关方法介绍不？

**Comment by kenwoodjw** [comment]
docker pull docker.m.daocloud.io/yihong0618/xiaogpt 可以试下国内代理

**Comment by terryxuwen** [comment]
> docker pull docker.m.daocloud.io/yihong0618/xiaogpt 可以试下国内代理

docker pull docker.m.daocloud.io/yihong0618/xiaogpt
Using default tag: latest
Trying to pull repository docker.m.daocloud.io/yihong0618/xiaogpt ... 
Pulling repository docker.m.daocloud.io/yihong0618/xiaogpt
Error: image yihong0618/xiaogpt:latest not found

唉，不行

**Comment by kenwoodjw** [comment]
拉取其他镜像正常吗？或者你换个tag

**Comment by frostming** [comment]
如果加上 `--platform linux_amd64` 呢？

**Comment by terryxuwen** [comment]
谢谢楼上各位，我找了一下，真的有http方式下载然后转移的，方法如下：
yum  install skopeo
skopeo  copy docker://docker.io/yihong0618/xiaogpt docker-archive:/home/xiaogpt.tar
docker load -i xiaogpt.tar
docker image tag 6e671cabb047 yihong0618/xiaogpt:latest
现在我的docker正常了，但是总是无法启动。。。。。 提示是小米验证登录失败。。。奇怪。用户名和密码没错，在config文件中都指定了，也干脆 用 -e 参数传给 docker了。
快投降了。。。折腾好久。

**Comment by terryxuwen** [comment]
Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 136, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaogpt/xiaogpt.py", line 422, in run_forever
    await self.init_all_data(session)
  File "/app/xiaogpt/xiaogpt.py", line 109, in init_all_data
    await self._init_data_hardware()
  File "/app/xiaogpt/xiaogpt.py", line 131, in _init_data_hardware
    hardware_data = await self.mina_service.device_list()
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 27, in device_list
    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")

**Comment by yihong0618** [comment]
可能不能在阿里云或腾讯云和海外服务器运行，会被小米风控

**Comment by terryxuwen** [comment]
> 可能不能在阿里云或腾讯云和海外服务器运行，会被小米风控

这是在我家，国内哈

**Comment by terryxuwen** [comment]
终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。

**Comment by alexgang** [comment]
> 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。

我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？

**Comment by terryxuwen** [comment]
> > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> 
> 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？

你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。

**Comment by alexgang** [comment]
> > > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> > 
> > 
> > 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？
> 
> 你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。

谢谢，我问的是无法登录小米服务器的问题。我魔法改在路由器上了，所以没有设置proxy. 我本地直接跑python是可以正常运行的，但是docker部署一直就出现小米服务器登录失败问题....真是奇怪了

**Comment by terryxuwen** [comment]
> > > > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> > > 
> > > 
> > > 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？
> > 
> > 
> > 你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。
> 
> 谢谢，我问的是无法登录小米服务器的问题。我魔法改在路由器上了，所以没有设置proxy. 我本地直接跑python是可以正常运行的，但是docker部署一直就出现小米服务器登录失败问题....真是奇怪了

你的docker跑在路由上吗？这样整个镜像也是加了魔法的，那就不行了。

**Comment by alexgang** [comment]
> > > > > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> > > > 
> > > > 
> > > > 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？
> > > 
> > > 
> > > 你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。
> > 
> > 
> > 谢谢，我问的是无法登录小米服务器的问题。我魔法改在路由器上了，所以没有设置proxy. 我本地直接跑python是可以正常运行的，但是docker部署一直就出现小米服务器登录失败问题....真是奇怪了
> 
> 你的docker跑在路由上吗？这样整个镜像也是加了魔法的，那就不行了。

不在路由，我就在PC本机跑docker. 同一台机器，用python直接运行没问题，部署到本机的docker就一直小米登录失败

**Comment by terryxuwen** [comment]
> > > > > > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> > > > > 
> > > > > 
> > > > > 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？
> > > > 
> > > > 
> > > > 你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。
> > > 
> > > 
> > > 谢谢，我问的是无法登录小米服务器的问题。我魔法改在路由器上了，所以没有设置proxy. 我本地直接跑python是可以正常运行的，但是docker部署一直就出现小米服务器登录失败问题....真是奇怪了
> > 
> > 
> > 你的docker跑在路由上吗？这样整个镜像也是加了魔法的，那就不行了。
> 
> 不在路由，我就在PC本机跑docker. 同一台机器，用python直接运行没问题，部署到本机的docker就一直小米登录失败

路由的魔法规则排除小米服务器了吗

**Comment by terryxuwen** [comment]
> > > > > > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> > > > > 
> > > > > 
> > > > > 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？
> > > > 
> > > > 
> > > > 你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。
> > > 
> > > 
> > > 谢谢，我问的是无法登录小米服务器的问题。我魔法改在路由器上了，所以没有设置proxy. 我本地直接跑python是可以正常运行的，但是docker部署一直就出现小米服务器登录失败问题....真是奇怪了
> > 
> > 
> > 你的docker跑在路由上吗？这样整个镜像也是加了魔法的，那就不行了。
> 
> 不在路由，我就在PC本机跑docker. 同一台机器，用python直接运行没问题，部署到本机的docker就一直小米登录失败

或者进入exec进入镜像，在镜像里面连接需要魔法的网站，如果能联通，说明你整个镜像都处于魔法状态，需要检查本机及整个网络的魔法设置。

**Comment by alexgang** [comment]
> > > > > > > 终于搞定了，原因是魔法不能加在整个docker镜像上，会导致无法登陆小米的服务器，魔法要设置在config文件中。
> > > > > > 
> > > > > > 
> > > > > > 我碰到和你一样的问题，能帮忙说详细一下吗？什么叫魔法设置在config文件里？？？
> > > > > 
> > > > > 
> > > > > 你说的是哪个问题，是无法pull镜像，还是无法登陆小米服务器？如果是无法pull镜像，我上面有解决办法。如果是无法登陆小米服务器，你需要看你是否使用了魔法。不使用魔法是无法访问gpt的把？ 魔法设置看config文件的proxy参数。
> > > > 
> > > > 
> > > > 谢谢，我问的是无法登录小米服务器的问题。我魔法改在路由器上了，所以没有设置proxy. 我本地直接跑python是可以正常运行的，但是docker部署一直就出现小米服务器登录失败问题....真是奇怪了
> > > 
> > > 
> > > 你的docker跑在路由上吗？这样整个镜像也是加了魔法的，那就不行了。
> > 
> > 
> > 不在路由，我就在PC本机跑docker. 同一台机器，用python直接运行没问题，部署到本机的docker就一直小米登录失败
> 
> 或者进入exec进入镜像，在镜像里面连接需要魔法的网站，如果能联通，说明你整个镜像都处于魔法状态，需要检查本机及整个网络的魔法设置。

不是魔法问题，我尝试了关闭魔法，但是仍然显示小米服务登陆失败。 另外一个神奇的现象是：我在本机的python 直接运行是成功的，而且就算我把小米账号，密码换成错误密码，再次跑程序仍然能够正常运行？？？难道小米账号服务器缓存了？？
