### ISSUE TITLE
能不能直接破解小爱音箱，然后嵌入进去

### ISSUE THREAD

**Issue by Edgar-Lzxc** [yihong0618/xiaogpt#267]
就是破解小爱智能音箱后使用docker直接就在音箱上发报文给云函数，然后返回gpt的消息

**Comment by yihong0618** [comment]
能，但不属于这个项目。

**Comment by Edgar-Lzxc** [comment]
> 能，但不属于这个项目。

能不能给个链接，不会破解

**Comment by yihong0618** [comment]
http://javabin.cn/2021/xiaoai_fm.html

**Comment by Edgar-Lzxc** [comment]
> http://javabin.cn/2021/xiaoai_fm.html

太感谢了，好人一生平安

**Comment by jinmiao** [comment]
> 实现了么，也出一个教程哈

**Comment by jinmiao** [comment]
现实了么了，也出个教程？@Edgar-Lzxc
