### ISSUE TITLE
轮询的地方无法获取聊天记录，是否需要认证小爱开放平台？

### ISSUE THREAD

**Issue by ggwgit** [yihong0618/xiaogpt#268]
可用执行小爱命令，让其说出某句话，但在轮询的地方无法获取聊天记录，是否需要认证小爱开放平台？

get_latest_ask_from_xiaoai这个方法里获取的记录一直是空的

'https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware=LX06&timestamp=1684808565555&limit=2'

{'code': 0, 'message': 'Success', 'data': '{"bitSet":[0,1,1],"records":[],"nextEndTime":0}'}

**Comment by yihong0618** [comment]
不需要，可能需要你下载个小爱的 app 然后问几次试试
