### ISSUE TITLE
账号密码登陆现在要验证码才能获取设备信息

### ISSUE THREAD

**Issue by Edgar-Lzxc** [yihong0618/xiaogpt#271]
有没有办法跳过这一步，反正是内网ip和其它信息都看得到did也获取了，程序每次运行都说验证码错误，导致用不了

**Comment by joe12801** [comment]
用docker

**Comment by arbraham** [comment]
我今天用还是好的啊。另外我觉得没必要一开始就获得MIIO DID，只需要hardware型号就行，可以在获取hardware list时把获取的DID填回给config里以便do_tts时用。

**Comment by yihong0618** [comment]
> 我今天用还是好的啊。另外我觉得没必要一开始就获得MIIO DID，只需要hardware型号就行，可以在获取hardware list时把获取的DID填回给config里以便do_tts时用。

因为很多人不止一个音箱啊
