### ISSUE TITLE
docker版，每次所在网络断网重连后，必须重启docker实例才能正常使用

### ISSUE THREAD

**Issue by terryxuwen** [yihong0618/xiaogpt#272]
有办法解决这个问题吗？

**Comment by joe12801** [comment]
> 有办法解决这个问题吗？

对，很有问题，用一些时间，自动死机，没反应了

**Comment by yihong0618** [comment]
我们看一下/

**Comment by kenwoodjw** [comment]
> > 有办法解决这个问题吗？
> 
> 对，很有问题，用一些时间，自动死机，没反应了

docker run --restart always xx 试下加个restart参数

**Comment by yihong0618** [comment]
应该修复了。
