### ISSUE TITLE
ModuleNotFoundError: No module named 'edge_tts'

### ISSUE THREAD

**Issue by woiweb** [yihong0618/xiaogpt#274]
➜  xiaogpt git:(main) python3 xiaogpt.py --hardware LX04  --mute_xiaoai --use_gpt3

ModuleNotFoundError: No module named 'edge_tts'

**Comment by yihong0618** [comment]
pip install edge-tts

**Comment by woiweb** [comment]
> pip install edge-tts

i has already install this module,and i run the 'pip install edge-tts',  it prompt as follow:

![image](https://github.com/yihong0618/xiaogpt/assets/715007/2004e82f-4393-4c05-9045-d7877c046bee)

**Comment by yihong0618** [comment]
try edge-tts in cli

![image](https://github.com/yihong0618/xiaogpt/assets/15976103/033fa4f7-3bf2-4807-999e-43725f51d1a8)

**Comment by frostming** [comment]
Please make sure you are calling pip from the same venv

**Comment by woiweb** [comment]
> try edge-tts in cli see if it works or not
> 
> ![image](https://user-images.githubusercontent.com/15976103/242767455-033fa4f7-3bf2-4807-999e-43725f51d1a8.png)

![image](https://github.com/yihong0618/xiaogpt/assets/715007/e1ac22d6-98f3-4cfc-a551-45b65dd61045)
it works

**Comment by yihong0618** [comment]
python -m pip install edge-tts
