### ISSUE TITLE
小爱10寸触屏音响，型号X10A，无法播报chatGPT的回复

### ISSUE THREAD

**Issue by Phillweston** [yihong0618/xiaogpt#280]
使用Docker镜像，运行命令为：docker run -e OPENAI_API_KEY=xxxxxx yihong0618/xiaogpt --account=xxxxxx --password=xxxxxx --hardware=X10A --use_chatgpt_api --mute_xiaoai
终端可以看到小爱和GPT的回复，但是小爱触屏音响上只能回复小爱的答复，无法回复GPT的答复。
请问一下这个是什么原因呢？谢谢

以下为对话截图
![image](https://github.com/yihong0618/xiaogpt/assets/42629755/88ad3d99-7027-42ba-8cad-e0da44e7ff55)

**Comment by yihong0618** [comment]
用 micli 试试能否 tts

**Comment by Phillweston** [comment]
我刚才看了一下源码，应该是config.py里面没有添加X10A型号的支持
我添加了一下支持，申请了merge request

[Add Support for X10A Model](https://github.com/yihong0618/xiaogpt/pull/281)

**Comment by yihong0618** [comment]
谢谢。
issue 里面有个触屏版的，你帮我回复一下？

**Comment by Phillweston** [comment]
> 谢谢。 issue 里面有个触屏版的，你帮我回复一下？

OK没问题
