### ISSUE TITLE
micli.py list 执行之后会有报错

### ISSUE THREAD

**Issue by afan1123** [yihong0618/xiaogpt#285]
![ad1b54cd1a92cff403a5beb376c3081](https://github.com/yihong0618/xiaogpt/assets/66288342/9b366de0-ac1e-4dea-b5cb-aa08f01fb077)

**Comment by yihong0618** [comment]
micli list

**Comment by afan1123** [comment]
![246f1887b93a3f0a3ad5d24f96f68c0](https://github.com/yihong0618/xiaogpt/assets/66288342/0789c1ba-fe40-44a9-8568-753ef66012fe)
嗯嗯，现在是这样了，请问该怎么办呢

**Comment by yihong0618** [comment]
参考 README 添加你的环境变量，你可以看 windows 那部分。

**Comment by afan1123** [comment]
![cf1ed8eab9f8e505fcbcb8b1889ed19](https://github.com/yihong0618/xiaogpt/assets/66288342/f9c42251-5b26-49b9-9f45-883df2f08fdd)
![8fd88f0c0f0427b7cd4b40bb97b1cab](https://github.com/yihong0618/xiaogpt/assets/66288342/d8d15d31-17b4-4473-aa52-cab4bfe34831)
嗯嗯，我是参考了这部分，但是还是报错了，
不知道大佬你说的环境变量是什么意思

**Comment by afan1123** [comment]
> 参考 README 添加你的环境变量，你可以看 windows 那部分。

嗯嗯，解决了这一步，但是我的是L05C，这里说没有这种的
![ab43a710fcbe305feb4c49d23ffa5fc](https://github.com/yihong0618/xiaogpt/assets/66288342/2cd4fcfb-fde8-45eb-be91-b9a4a391774b)
![21b8b8cae5938f3d1bebb6559c0f6dc](https://github.com/yihong0618/xiaogpt/assets/66288342/fcbe8997-3fb3-4ae7-ae69-2ecb581a6c2d)

**Comment by yihong0618** [comment]
@afan1123 我把你的图片删了，你这样暴露隐私了
