### ISSUE TITLE
作者你好，请教一下关于LATEST_ASK_API

### ISSUE THREAD

**Issue by ArchangelXu** [yihong0618/xiaogpt#291]
这个api接口具体的逻辑是怎样的呢？我看传的参数是hardware，timestamp和limit，意思是获取对应硬件在timestamp时间前的最新limit条对话吗？

**Comment by yihong0618** [comment]
不是，获取的是小米服务器的时间

**Comment by ArchangelXu** [comment]
> 不是，获取的是小米服务器的时间

具体是？
我现在手边没有音箱，想拿以前的历史对话数据看下结构，要怎么传参？

**Comment by yihong0618** [comment]
"https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware={hardware}&timestamp={timestamp}&limit=2"

timestamp 拿 now 的就行
limit 可以多传点。
剩下需要你自己研究，不属于这个项目，所以先关了。
