### ISSUE TITLE
player_get_status函数无法判断是否在播放语音回答，这样无法实现wait_for_tts_finish

### ISSUE THREAD

**Issue by arbraham** [yihong0618/xiaogpt#292]
调测发现player_get_status函数无法判断是否在播放语音回答，即无法判断tts是否正在播放。这样无法实现wait_for_tts_finish的功能。请大佬再补充一个判断tts是否播放完成得函数。

**Comment by yihong0618** [comment]
小米没提供这个接口只能轮训，之前是有的，但是会频繁请求我们去掉了
