### ISSUE TITLE
enable_edge_tts报错

### ISSUE THREAD

**Issue by arbraham** [yihong0618/xiaogpt#293]
开启了enable_edge_tts，不管是否配localhost和代理，发现GPT回答后无法调用tts回答，
"enable_edge_tts": true,
"proxy": "http://127.0.0.1:7890",
 "localhost": true
"stream": true,

到这个函数就报错：
       async def run_tts(text_stream, tts_lang, queue):
            async for text in text_stream:
                try:
                    url, duration = await self.text2mp3(text, tts_lang)
                except Exception:
                    self.log.exception("haha")
                    continue
                await queue.put((url, duration))
这个错误：
HTTPS proxies https://127.0.0.1:7890 are not supported, ignoring
[06/11/23 18:03:02] ERROR    haha                                xiaogpt.py:334
                             Traceback (most recent call last):                
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\venv\lib\site-packages\aiohttp\co               
                             nnector.py", line 1091, in                        
                             _start_tls_connection                             
                                 tls_transport = await                         
                             self._loop.start_tls(                             
                               File                                            
                             "C:\Users\29014\AppData\Local\Progr               
                             ams\Python\Python310\lib\asyncio\ba               
                             se_events.py", line 1239, in                      
                             start_tls                                         
                                 await waiter                                  
                             ConnectionResetError                              
                                                                               
                             The above exception was the direct                
                             cause of the following exception:                 
                                                                               
                             Traceback (most recent call last):                
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\xiaogpt\xiaogpt.py", line 332, in               
                             run_tts                                           
                                 url, duration = await                         
                             self.text2mp3(text, tts_lang)                     
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\xiaogpt\xiaogpt.py", line 326, in               
                             text2mp3                                          
                                 return (await                                 
                             self.get_file_url(stream),                        
                             duration)                                         
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\xiaogpt\xiaogpt.py", line 309, in               
                             get_file_url                                      
                                 resp = await session.put(                     
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\venv\lib\site-packages\aiohttp\cl               
                             ient.py", line 536, in _request                   
                                 conn = await                                  
                             self._connector.connect(                          
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\venv\lib\site-packages\aiohttp\co               
                             nnector.py", line 540, in connect                 
                                 proto = await                                 
                             self._create_connection(req,                      
                             traces, timeout)                                  
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\venv\lib\site-packages\aiohttp\co               
                             nnector.py", line 899, in                         
                             _create_connection                                
                                 _, proto = await                              
                             self._create_proxy_connection(req,                
                             traces, timeout)                                  
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\venv\lib\site-packages\aiohttp\co               
                             nnector.py", line 1325, in                        
                             _create_proxy_connection                          
                                 return await                                  
                             self._start_tls_connection(                       
                               File                                            
                             "C:\Users\29014\source\repos\xiaogp               
                             t\venv\lib\site-packages\aiohttp\co               
                             nnector.py", line 1111, in                        
                             _start_tls_connection                             
                                 raise                                         
                             client_error(req.connection_key,                  
                             exc) from exc                                     
                             aiohttp.client_exceptions.ClientCon               
                             nectorError: Cannot connect to host               
                             transfer.sh:443 ssl:default [None]

**Comment by yihong0618** [comment]
看起来是 ssl 问题
