### ISSUE TITLE
请问把OpenAI APIKEY换成New Bing，怎样设置？

### ISSUE THREAD

**Issue by ericshirs** [yihong0618/xiaogpt#294]
https://github.com/acheong08/EdgeGPT#getting-authentication-required
中的python3 -m pip install EdgeGPT --upgrade起什么作用？是获取bing的cookies吗？
获取cookies之后，怎样启动程序呢？如果用docker，又该怎样启动呢？

**Comment by lijian12345** [comment]
不需要安装EdgeGPT，只需要用cookie editor导出cookie到一个json文件，然后运行以下命令即可
```xiaogpt --hardware LX06 --mute_xiaoai --stream --enable_edge_tts --use_newbing --bing_cookie_path bing_cookies.json```

**Comment by ChenArno** [comment]
请问docker怎么配置的，我将cookis.json跟xiaoaiconfig.json放在同一目录下不生效
