### ISSUE TITLE
如果用new bing的话，怎么设置对应的三个模式呢

### ISSUE THREAD

**Issue by lijian12345** [yihong0618/xiaogpt#295]
在导出的cookies.json文件里就包括了这个信息吗，还是要怎么设置

**Comment by lijian12345** [comment]
> 参考 edgeGPT https://github.com/acheong08/EdgeGPT

我看EdgeGPT启动的时候是有--style creative这个参数的，但是xiaogpt并没有。而且cookies.json里应该也是只有cookie的信息吧

**Comment by yihong0618** [comment]
是的，我研究下。

**Comment by lijian12345** [comment]
> 是的，我研究下。

666，多谢大佬

**Comment by uuskys** [comment]
我觉得三个模式应该包括在cookie里了吧
看起来你已经成功使用new bing了，参数怎么设呢？
