### ISSUE TITLE
据说“定制小爱”功能要停运下线了。请问：这会不会影响这个程序运行？

### ISSUE THREAD

**Issue by ericshirs** [yihong0618/xiaogpt#296]
https://finance.sina.com.cn/tech/digi/2023-06-13/doc-imyxccqp9009951.shtml
IT之家 6 月 13 日消息，小米小爱同学团队发布公告称“由于产品策略调整，定制小爱功能将于 2023 年 7 月 10 日小爱语音 V6.6 版本正式停运下线”。

**Comment by yihong0618** [comment]
不会
