### ISSUE TITLE
docker运行模版少一个did的参数还能运行吗？

### ISSUE THREAD

**Issue by tianmk520** [yihong0618/xiaogpt#297]
docker run -e OPENAI_API_KEY=<your-openapi-key> yihong0618/xiaogpt --account=<your-xiaomi-account> --password=<your-xiaomi-password> --hardware=<your-xiaomi-hardware> --use_chatgpt_api    
docker运行的时候，官方模版没看到指定mi did的参数，怎么知道是哪个音响呀？我用脚本可以跑起来，docker跑不起来，但是脚本跑起来之后经常死掉，不知道哪里处问题了

**Comment by yihong0618** [comment]
能提供下更多的报错信息么？

**Comment by yihong0618** [comment]
close for no reply
