### ISSUE TITLE
关于config中几个参数的疑问

### ISSUE THREAD

**Issue by africa1207** [yihong0618/xiaogpt#298]
prompt：这个不应该是我发问的内容吗？怎么还有默认值？或者说这个是对gpt的规则限制？我也可以定义比如：你现在是一名翻译，接下来把我说的内容都翻译成英语。那么我问了问题是否就会变成英语返回？
change_prompt_keyword：同prompt，如果是规则限制，我只要说“小爱同学，更改提示词”，然后我再说我的规则定义：你每个回答前都加上“哈哈”，是否再发问就变成哈哈开头的了？
另外我使用的docker，mute_xiaoai好像不起作用

**Comment by yihong0618** [comment]
1. 有的我们需要限制回复的长度。
2. 看可以
3. mute_xiaoai 不起作用可能是型号的限制
