### ISSUE TITLE
实现拦截小爱回答，只播放 chatgpt 的

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/xiaogpt#3]

**Comment by yihong0618** [comment]
又想到了一个诡异的方式，有可能可以实现，明天写代码。

**Comment by pjq** [comment]
在你的基础上做了一些调优，现在好一些了
- https://github.com/pjq/ChatGPT-MiSpeaker/blob/main/ChatGPT-MiSpeaker.py

**Comment by yihong0618** [comment]
@pjq 看了下代码，可以的，你要把其中一些公用的提个 PR 么

**Comment by yihong0618** [comment]
也可以等我尝试拦截小爱回答一起提

**Comment by pjq** [comment]
我把README.md, python脚本名字都改掉了, 提过来会Override你之前的

**Comment by yihong0618** [comment]
> 我把README.md, python脚本名字都改掉了, 提过来会Override你之前的

好的

**Comment by pjq** [comment]
我整理了一下, 一个commit过来

**Comment by yihong0618** [comment]
TODO

**Comment by lichengda** [comment]
大佬们，你们成功了吗？

**Comment by yihong0618** [comment]
@lichengda 可以实现但不太优雅。

**Comment by lichengda** [comment]
为啥？

**Comment by lichengda** [comment]
@yihong0618 你的代码更新了吗？

**Comment by lichengda** [comment]
俺试试去

**Comment by yihong0618** [comment]
没更新，因为没太好的办法，小爱还是会出声，只能在他出声后停止播放

**Comment by lichengda** [comment]
--conversation_id 在哪里看？

**Comment by lichengda** [comment]
@yihong0618

**Comment by yihong0618** [comment]
chatgpt 网页版，url 里

**Comment by yihong0618** [comment]
Done

**Comment by zlc000190** [comment]
做到了吗

**Comment by yihong0618** [comment]
> 做到了吗

嗯

**Comment by lichengda** [comment]
出Whisper 可以直接用上吗？
