### ISSUE TITLE
micli list 结果报Login failed

### ISSUE THREAD

**Issue by wendaocode** [yihong0618/xiaogpt#30]
请教一下
跑micli list结果报SSLCertVerificationError，Login failed
查了一下需要关闭VPN，关了VPN直连也无法解决。
请问是什么原因，有什么解决办法吗？

> Exception on login None: Cannot connect to host account.xiaomi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')]
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
>     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1103, in create_connection
>     transport, protocol = await self._create_connection_transport(
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1133, in _create_connection_transport
>     await waiter
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
>     ssldata, appdata = self._sslpipe.feed_ssldata(data)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
>     self._sslobj.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/miservice/miaccount.py", line 56, in login
>     resp = await self._serviceLogin(f"serviceLogin?sid={sid}&_json=true")
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/miservice/miaccount.py", line 98, in _serviceLogin
>     async with self.session.request(
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
>     self._resp = await self._coro
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
>     conn = await self._connector.connect(
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
>     raise last_exc
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
>     transp, proto = await self._wrap_create_connection(
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
>     raise ClientConnectorCertificateError(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host account.xiaomi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')]
> Error https://api.io.mi.com/app/home/device_list: Login failed

**Comment by yihong0618** [comment]
关掉 vpn 去掉 proxy

**Comment by wendaocode** [comment]
> 
关了，
scutil --proxy
<dictionary> {
  HTTPEnable : 0
  HTTPSEnable : 0
  ProxyAutoConfigEnable : 0
  SOCKSEnable : 0
}

**Comment by wendaocode** [comment]
关掉了VPN，去掉了proxy。
还是报错，请问有其他可能吗？

scutil --proxy
<dictionary> {
  HTTPEnable : 0
  HTTPSEnable : 0
  ProxyAutoConfigEnable : 0
  SOCKSEnable : 0
}

**Comment by yihong0618** [comment]
unset http_proxy
unset https_proxy
