### ISSUE TITLE
测试了一下,小米小爱音箱HD(hardware:M01)这一款好像没办法用

### ISSUE THREAD

**Issue by jaxwang** [yihong0618/xiaogpt#311]
我有两个小米音箱 , 一个是小米小爱音箱HD(hardware:M01),  ,另一个是小爱音箱Pro(hardware:LX06),

经测试后, 小爱音箱Pro可以正常使用GPT, 查看日志输出也一切正常.

但是 , 换到小米小爱音箱HD(hardware:M01)就不起作用了, 用了唤醒词语, 控制台也接受不到任何信息, 只显示初始两条日志:

```
xiaogpt    | Running xiaogpt now, 用`请问`开头来提问
xiaogpt    | 或用`开始持续对话`开始持续对话
```
我确定我的config.json是没有写错的.
另外, 我是用docker跑在我的路由器上, 用docker-compose编排的.
不过, 我不认为是环境的问题, 因为我的小爱音箱Pro(hardware:LX06)是可以正常使用的.

是不是 小米小爱音箱HD(hardware:M01) 这个设备本身就没办法支持?

**Comment by yihong0618** [comment]
可以本地用 micli 试试

**Comment by jaxwang** [comment]
> 

我用 `python micli.py spec onemore.wifispeaker.sm4`  (onemore.wifispeaker.sm4是我音箱的model) 看了我音箱支持的命令: 
```
# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:onemore-sm4:1

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rwn

Play_Control = 3
    Playing_State = 1  # uint8  # rn

    _Play = 1
    _Pause = 2

Microphone = 4
    Mute = 1  # bool  # rwn

Speaker_Volume
    MIN = 0
    MAX = 100

Play_Control_Playing_State
    Pause = 0
    Playing = 1

```
压根就没有`5` !! , 也就是没有 `Intelligent_Speaker` 这一项...  我试了一下控制音量的命令  都没问题..
看来这个早期的小米音箱HD是无缘了, hardware是`M01` , Model是`onemore.wifispeaker.sm4` ,  产品名叫`小米小爱音箱HD` 
小米商城的链接是<https://www.mi.com/aispeaker-hd?product_id=1185100022> , 当初花了599元买的. 😭   给大家避避坑..

**Comment by yihong0618** [comment]
感谢上面信息。。。

**Comment by Joy730** [comment]
小爱音箱Pro是可以使用，可有一个很大的弊端，就是无法连续对话，每次都要叫“小爱同学”唤起，使用起来不方便

**Comment by yihong0618** [comment]
> 小爱音箱Pro是可以使用，可有一个很大的弊端，就是无法连续对话，每次都要叫“小爱同学”唤起，使用起来不方便

不需要，参考 readme 跟他说开始持续对话

**Comment by duolabmeng6** [comment]
```
mt.wakeUp()
```
我测试了一下 这个 没有办法唤醒...

**Comment by yihong0618** [comment]
> ```
> mt.wakeUp()
> ```
> 
> 我测试了一下 这个 没有办法唤醒...

有些型号是不行的。README 里有记录。。。

**Comment by yihong0618** [comment]
> > > 
> > 
> > 
> > > mt.wakeUp()
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 我测试了一下 这个 没有办法唤醒...
> > 
> > 
> > 有些型号是不行的。README 里有记录。。。
> 
> 大佬我魔改了以后可以 填 did 就行 但是问题是 提示 我在... 这个声音很烦 py版本很好 但是随机不播放gpt声音 go版本完全正常 播放gpt的没有失败过

我研究下和 go 版本的差异，谢谢

**Comment by duolabmeng6** [comment]
各有好处...py代码很完善...我一度以为能用了...结果随机输出了答案 读不出来 代码看了 也推送了 反正是诡异. 折腾了几天  小朋友也不爱玩..  提示词不知道用啥好  哈哈哈

**Comment by yihong0618** [comment]
> 各有好处...py代码很完善...我一度以为能用了...结果随机输出了答案 读不出来 代码看了 也推送了 反正是诡异. 折腾了几天 小朋友也不爱玩.. 提示词不知道用啥好 哈哈哈

有没有兴趣一起完善他？

**Comment by duolabmeng6** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > mt.wakeUp()
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我测试了一下 这个 没有办法唤醒...
> 
> > > 
> 
> > > 
> 
> > > 有些型号是不行的。README 里有记录。。。
> 
> > 
> 
> > 大佬我魔改了以后可以 填 did 就行 但是问题是 提示 我在... 这个声音很烦 py版本很好 但是随机不播放gpt声音 go版本完全正常 播放gpt的没有失败过
> 
> 
> 
> 我研究下和 go 版本的差异，谢谢


两份代码几乎流程都一样 我以为是同一人写的... py版本的发唤醒 是加密的 我想抠到golang用的 奈何gpt不给力 扣不出来 哈哈哈哈

**Comment by yihong0618** [comment]
可能是 go 的异步更好一些 @frostming 我们研究下

**Comment by duolabmeng6** [comment]
> > 各有好处...py代码很完善...我一度以为能用了...结果随机输出了答案 读不出来 代码看了 也推送了 反正是诡异. 折腾了几天 小朋友也不爱玩.. 提示词不知道用啥好 哈哈哈
> 
> 
> 
> 有没有兴趣一起完善他？

我有golang版本的推送音频协议，可以收到播放状态的回调，py版本只有1个最大的问题 随机推送失败，挺纠结要完善那个版本
go改个唤醒 不提示我在 
py这边解决 100%推送语音成功
思考一下... py这边bug重写一下推送逻辑？...py版本我也有推送的协议

**Comment by duolabmeng6** [comment]
https://github.com/duolabmeng6/easy_to_tv
https://github.com/duolabmeng6/projection_screen_tv

这两个是推送音频协议的代码
go版本的话是可以有播放回调
py我没写

就是如果没有收到播放回调的情况下就
再发一次 这样就能解决发送失败的情况了

**Comment by yihong0618** [comment]
@duolabmeng6 thanks 我看一下。

**Comment by caravan-desert** [comment]
> > > 
> > 
> > 
> > > mt.wakeUp()
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 我测试了一下 这个 没有办法唤醒...
> > 
> > 
> > 有些型号是不行的。README 里有记录。。。
> 
> 大佬我魔改了以后可以 填 did 就行 但是问题是 提示 我在... 这个声音很烦 py版本很好 但是随机不播放gpt声音 go版本完全正常 播放gpt的没有失败过

@duolabmeng6 你是改成did就能用这款音箱了吗？怎么改呢

**Comment by caravan-desert** [comment]
> 我也是小爱音箱HD，但直接说找不到，我的产品型号是 XMYX01JY 。 提示我Exception: we have no hardware: XMYX01JY please check。 不知道是啥原因

hardware就是sm4, 但是不能唤醒, 就是这个issue在讲的事情

**Comment by yihong0618** [comment]
> > 我也是小爱音箱HD，但直接说找不到，我的产品型号是 XMYX01JY 。 提示我Exception: we have no hardware: XMYX01JY please check。 不知道是啥原因
> 
> hardware就是sm4, 但是不能唤醒, 就是这个issue在讲的事情

目前看是阉割掉高级那个蓝牙的小爱无法进行唤醒，只能用 --use_command 也不能 mute
