### ISSUE TITLE
請問--mute_xiaoai這個參數不生效

### ISSUE THREAD

**Issue by 76159482** [yihong0618/xiaogpt#312]
--mute_xiaoai這個參數不生效，小愛影箱的聲音還是繼續播放，但是GPT的聲音無法就中斷了。

![image](https://github.com/yihong0618/xiaogpt/assets/41219170/8b8def51-f02c-425f-862e-0628d74858fb)

**Comment by yihong0618** [comment]
有些型号是无法 mute 的，参考 README
