### ISSUE TITLE
Implementation to Korean

### ISSUE THREAD

**Issue by dsdanielpark** [yihong0618/xiaogpt#317]
I deeply admire your impressive [xiaogpt](https://github.com/yihong0618/xiaogpt) project and code. 

While Google Assistant and Apple's Siri may have surpassed this project, my passion lies in exploring new territories, so I would love to port this project into Korean.

I believe I can follow the YouTube tutorials and various instructions easily, but I wonder if I could contribute by translating the project into Korean. Could you provide a simple guide on how to do the Korean port for xiaogpt?

Lastly, I'm curious if xiaogpt will work with the XIOMI - `XMYX04WM` model. If not, I'm willing to purchase the XIOMI-`A8-L`model and proceed with the implementation for this project.

Thank you, and have a wonderful weekend night!

**Comment by yihong0618** [comment]
Cool  XMYX04WM maybe not I wonder.
you can check the config file https://github.com/yihong0618/xiaogpt/blob/main/xiaogpt/config.py#L16-L31 which support.

FYI: the xiaogpt job is based on my forked repo -> https://github.com/yihong0618/MiService its only support China account for now, but you can change some code to support your country.

Sorry its Chinese, I hope goggle translate or ChatGPT or DeepL will help~

and thanks for your repo Bard-API, Have a good weekend~

**Comment by yihong0618** [comment]
> 

PR welcome, hope it can work in other counties

**Comment by yihong0618** [comment]
@dsdanielpark 

do some search you can use https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor to check if Korean account can do something or not, and make it support to  https://github.com/yihong0618/MiService

**Comment by dsdanielpark** [comment]
Thank you, I will start from here. https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor by using korean account.
