### ISSUE TITLE
请问已经申请了azure 的openai 的api，应该如何使用，求大佬指导

### ISSUE THREAD

**Issue by jonny-gg** [yihong0618/xiaogpt#320]
不止代码里面所说的deployment_id 是不是类似这种
![image](https://github.com/yihong0618/xiaogpt/assets/10399955/3a994837-2547-4b43-add0-ae995a9b44c5)

**Comment by yihong0618** [comment]
和其它 azure 的方式一样，搜索怎么用 azure ChatGPT 就行

**Comment by yauuzi** [comment]
"openai_key": "717a569d35cxxxxxxxxx", // azure key   这个配置可以 亲测azure可行
  "deployment_id": "xxxx-openai-chat",
  "api_base":"https://xxxx-openai-chat.openai.azure.com/"

**Comment by yauuzi** [comment]
"openai_key": "717a569d35cxxxxxxxxx", // azure key   这个配置可以 亲测azure可行
  "deployment_id": "xxxx-openai-chat",
  "api_base":"https://xxxx-openai-chat.openai.azure.com/"

**Comment by xiaoch669** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/101499434/5e5833d1-863d-44a8-a229-796828343eca)
配置好了，但是报错，开的clash，也是7890端口，网络问题应该是解决了，但是一直报秘钥出错，新写的test是可以跑通的
![image](https://github.com/yihong0618/xiaogpt/assets/101499434/a39ba382-05e6-4db3-9d34-ddf4154ddb36)

**Comment by xiaoch669** [comment]
> "openai_key": "717a569d35cxxxxxxxxx", // azure key 这个配置可以 亲测azure可行 "deployment_id": "xxxx-openai-chat", "api_base":"https://xxxx-openai-chat.openai.azure.com/"
大佬看看我的问题

**Comment by xiaoch669** [comment]
不行哎，我用官方的示例可以跑通，我也看了chatgptapi_bot.py的源码，没找出啥问题，运行报错Incorrect API key provided: bbbcb604********************7392. You can find your API key at&nbsp;
https://platform.openai.com/account/api-keys.说明网络应该没问题了，会不会是字符编码问题，您有啥思路没



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月5日(周四) 上午9:41
收件人: ***@***.***&gt;;
抄送: "Guangpeng ***@***.******@***.***&gt;;
主题: Re: [yihong0618/xiaogpt] 请问已经申请了azure 的openai 的api，应该如何使用，求大佬指导 (Issue #320)




 
@xiaoch669 我把你的截图删了（你截图里暴露账号信息了）
 你全局代理试试？按照楼上的回复

**Comment by xiaobingwudi** [comment]
deployment_id 就是部署名称“xiaomi”

**Comment by xiaobingwudi** [comment]
你的邮件我已经收到了，这是一个邮件回执
