### ISSUE TITLE
大佬们，这个windows中的第四步得到did具体应该怎么操作啊求求

### ISSUE THREAD

**Issue by momo325** [yihong0618/xiaogpt#323]
Windows 获取小米音响DID
1 pip install miservice_fork
2 set MI_USER=xxxx
3 set MI_PASS=xxx
4 得到did
5 set MI_DID=xxxx
6 具体可参考 one_click.bat 脚本

**Comment by yihong0618** [comment]
micli list

**Comment by momo325** [comment]
@yihong0618 是这样么？但是用不了啊
![image](https://github.com/yihong0618/xiaogpt/assets/68660594/59c8e20e-5f5a-47e1-9b80-6685dc672dad)

**Comment by yihong0618** [comment]
python -m miservice list

**Comment by momo325** [comment]
已经解决了，给不太会的朋友们说一下，下载miserver-main，解压，输入那三个命令后，手动编辑miaccount.py,手动填入'账号密码'，运行micli.py -list即可
