### ISSUE TITLE
这个咋解决，有人遇到过么

### ISSUE THREAD

**Issue by hlming09** [yihong0618/xiaogpt#328]
找到了你的音箱:        , message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware=LX06&timestamp=1690806126956&limit=2')
 求问大神，这个咋解决

**Comment by yihong0618** [comment]
看起来是，没拿到，你 print 看看？
