### ISSUE TITLE
如果你写了相关教程或者视频可以提 PR 到 README

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/xiaogpt#33]
我可以放在 README 上
RT

**Comment by lichengda** [comment]
出Whisper可以加上去吗？

**Comment by yihong0618** [comment]
@lichengda 跟项目相关/

**Comment by lichengda** [comment]
大佬现在解决小爱的干扰了？

**Comment by yihong0618** [comment]
是，参考 README 但不建议长时间用

**Comment by lichengda** [comment]
@yihong0618 为啥？先在可以用3.5的api了吗？

**Comment by yihong0618** [comment]
可以

**Comment by lichengda** [comment]
export OPENAI_API_KEY=sk-u   api密钥我都输入了，但是这样启动的时候还是报错python3 xiaogpt.py --hardware LX06  --mute_xiaoai --use_chatgpt_api

**Comment by Maple-Dawn** [comment]
我弄了一个视频，你看看可以不

**Comment by Maple-Dawn** [comment]
我弄了一个视频，你看看可以不 
https://www.youtube.com/watch?v=K4YA8YwzOOA

**Comment by yihong0618** [comment]
Done
