### ISSUE TITLE
Cookie方式无法直接使用

### ISSUE THREAD

**Issue by redteaLi** [yihong0618/xiaogpt#332]
没办法只用抓包抓到的cookie，不输入账号密码

原因：登录的时候有去调用文件(Path.home() + ".mi.token")读取server生成的token信息。以下json串。

{
  "deviceId": "xx",
  "userId": 1000,
  "passToken": "xx",
  "xiaomiio": [
    "xxx",
    "xxx"
  ],
  "micoapi": [
    "xxx",
    "xxx"
  ]
}

**Comment by yihong0618** [comment]
login 的方式不行？

**Comment by redteaLi** [comment]
另外香港的机子的话，可以在本地用miservice登录账号，然后将token文件复制到服务器上的Path.home() + ".mi.token"即可。运行配置不需要配置账号密码、cookie

**Comment by redteaLi** [comment]
> login 的方式不行？

香港的机子，登录不了

**Comment by yihong0618** [comment]
哦哦，可以修复一下跳过。这个读目录，但是可能无法 mute.
有兴趣提个 PR 么？或者我来看看

btw, miservice 能登陆理论上 xiaogpt 就行啊？

**Comment by redteaLi** [comment]
> 哦哦，可以修复一下跳过。这个读目录，但是可能无法 mute. 有兴趣提个 PR 么？或者我来看看
> 
> btw, miservice 能登陆理论上 xiaogpt 就行啊？

不怎么会python，miservice是自己的电脑运行的登录，我用服务器登录老是不成功，可能是安全校验过不去吧

**Comment by redteaLi** [comment]
docker run --rm -d -v /opt/xiaogpt/config:/config  -v /opt/xiaogpt/mitoken:/root  --name xiaogpt-pro yihong0618/xiaogpt --config=/config/config.json --hardware=LX06 --stream

这是我的docker运行命令，config里面没有账号密码和cookie信息，/opt/xiaogpt/mitoken文件夹下是本地登录获取的.mi.token文件。

**Comment by yihong0618** [comment]
好的，我们研究下

**Comment by yihong0618** [comment]
@redteaLi 我这边测试没问题（没用docker 跑。

**Comment by KJZH001** [comment]
> @redteaLi 我这边测试没问题（没用docker 跑。

我这边也尝试了一下，拿本地在windows上获取的token直接放到香港的linux上跑，直接部署在主系统上可以正常登录

原本会提示
```
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_xxx: Login failed
```
token放上去就正常了

**Comment by yihong0618** [comment]
@KJZH001 是的。有兴趣提个 PR 加在 README 的问题里么？
但可能只能跑 24 小时。。。（之后会报错还得重新获取）

**Comment by redteaLi** [comment]
> @KJZH001 是的。有兴趣提个 PR 加在 README 的问题里么？ 但可能只能跑 24 小时。。。（之后会报错还得重新获取）

本地获取的token放服务器可以好久，我的从开始提问题到现在就掉过一次。

**Comment by KJZH001** [comment]
> @KJZH001 是的。有兴趣提个 PR 加在 README 的问题里么？ 但可能只能跑 24 小时。。。（之后会报错还得重新获取）

发起pr了

**Comment by yihong0618** [comment]
@KJZH001 谢谢，先关了， 有问题再随时打开。

**Comment by VectorZhao** [comment]
我在家部署的项目，最近出现了无法登陆的现象，但是我的是国区账号，api2.mina.mi.com走的直连

**Comment by yihong0618** [comment]
> 我在家部署的项目，最近出现了无法登陆的现象，但是我的是国区账号，api2.mina.mi.com走的直连

重新在本地登陆下 xiaomi cloud

**Comment by VectorZhao** [comment]
可以了

**Comment by hungleung** [comment]
> 可以了

请问如何解决的，谢谢。

**Comment by yihong0618** [comment]
> > 可以了
> 
> 
> 
> 请问如何解决的，谢谢。

重新在本地登陆下 xiaomi cloud
