### ISSUE TITLE
如何用登录账号密码的形式获取到小爱音箱的对话记录

### ISSUE THREAD

**Issue by weishaogeng512** [yihong0618/xiaogpt#333]
请教一下，如何用登录账号密码的形式获取到小爱音箱的对话记录呢？
代码看了半天没看明白，拜托作者不吝赐教

**Comment by yihong0618** [comment]
LATEST_ASK_API = "https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware={hardware}&timestamp={timestamp}&limit=2"
把这行代码的 limit 2 改大，然后 print

**Comment by weishaogeng512** [comment]
> LATEST_ASK_API = "[https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware={hardware}&timestamp={timestamp}&limit=2](https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware=%7Bhardware%7D&timestamp=%7Btimestamp%7D&limit=2)"
> 把这行代码的 limit 2 改大，然后 print

我直接使用这个LATEST_ASK_API得到的内容是{'code': 601, 'message': 'illegal argument exception', 'data': "MissingRequestCookieException: Required cookie 'userId' for method parameter type Long is not present"}

**Comment by yihong0618** [comment]
你不能直接用，代码里改，然后 print 出来。

**Comment by weishaogeng512** [comment]
不知是否冒昧，您能否再开一个项目，分享一下如何获取到小爱音箱轮询的对话记录？

**Comment by yihong0618** [comment]
可能后面会做，现在没有精力。
