### ISSUE TITLE
用着用着突然不能用了，唤醒词唤不醒，看日志是报错了，请看下原因

### ISSUE THREAD

**Issue by wxjun2018** [yihong0618/xiaogpt#334]
[08/08/23 19:03:45] WARNING  Execption when get latest ask from   xiaogpt.py:243
                             xiaoai:                                            
[08/08/23 19:13:01] WARNING  Execption when get latest ask from   xiaogpt.py:243
                             xiaoai:                                            
[08/08/23 19:22:25] WARNING  Execption when get latest ask from   xiaogpt.py:243
                             xiaoai:                                            
--------------------
问题：？
以下是小爱的回答:  
人工智能（AI）是计算机科学分支，研究模拟、延伸和扩展人的智能的技术科学。目的是
生产出智能机器，能以人类智能相似的方式做出反应。研究领域包括机器人、语言识别、图
像识别、自然语言处理和专家系统等。
以下是 CHATGPTAPI 的回答: 你好小朋友！很高兴和你聊天。你有什么问题想问我吗？我会用简单的话来回答你哦！

如果你有问题，可以告诉我，我会尽力帮助你。例如，如果你想知道为什么天空是蓝色的，那是因为太阳的光线经过大气层时，被散射成了蓝色。所以我们看到的天空就是蓝色的啦！

还有，如果你想知道为什么花会开，那是因为花需要阳光、水和土壤来生长。当它们得到足够的养分和温暖的阳光时，它们就会开出漂亮的花朵。

另外，如果你想知道为什么我们要上学，那是因为上学可以学到很多有趣的知识，可以和小朋友们一起玩耍，还可以成为更聪明的大人。上学可以让我们变得更强大！

希望这些回答能让你开心，如果你还有其他问题，随时告诉我哦！记得要好好享受快乐的童年时光，玩得开心！
回答完毕
开始对话
--------------------
问题：讲一个？
以下是小爱的回答:  想听什么呢？
以下是 CHATGPTAPI 的回答: Exception in callback MiGPT.ask_gpt.<locals>.done_callback(<Task cancell...aogpt.py:380>>) at /root/xiaogpt/xiaogpt/xiaogpt.py:388
handle: <Handle MiGPT.ask_gpt.<locals>.done_callback(<Task cancell...aogpt.py:380>>) at /root/xiaogpt/xiaogpt/xiaogpt.py:388>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/root/xiaogpt/xiaogpt/xiaogpt.py", line 390, in done_callback
    if future.exception():
asyncio.exceptions.CancelledError
回答完毕
继续对话, 或用`结束持续对话`结束对话
--------------------
问题：讲一个奥特曼的故事？
以下是小爱的回答:  好的，为你播放会员专享内容宇宙英雄奥特曼 
罗布奥特曼《罗布奥特曼》 第2集 兄弟情 中
以下是 CHATGPTAPI 的回答: Exception in callback MiGPT.ask_gpt.<locals>.done_callback(<Task cancell...aogpt.py:380>>) at /root/xiaogpt/xiaogpt/xiaogpt.py:388
handle: <Handle MiGPT.ask_gpt.<locals>.done_callback(<Task cancell...aogpt.py:380>>) at /root/xiaogpt/xiaogpt/xiaogpt.py:388>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/root/xiaogpt/xiaogpt/xiaogpt.py", line 390, in done_callback
    if future.exception():
asyncio.exceptions.CancelledError
回答完毕
继续对话, 或用`结束持续对话`结束对话
--------------------
问题：讲一个奥特曼的故事？
以下是小爱的回答:  好的，为你播放会员专享内容宇宙英雄奥特曼 
罗布奥特曼《罗布奥特曼》 第2集 兄弟情 中
以下是 CHATGPTAPI 的回答: 好的，我给你讲一个奥特曼的故事吧！

从前，有一个叫做奥特曼的超级英雄。他来自一个叫“光之国”的星球。奥特曼身穿一套闪亮的银白色战斗服，头戴一个红色的光头罩。

奥特曼的任务是保护地球上的人们免受怪兽的伤害。每当有怪兽出现，奥特曼就会变身成为巨大的奥特曼，和怪兽进行战斗。

一天，一个巨大的怪兽出现在一个小城市里，它的身上有着坚硬的外壳和锋利的爪子。人们非常害怕，不知道该怎么办。

奥特曼立刻飞到了现场，他用他强大的力量和勇气与怪兽展开了激烈的战斗。奥特曼运用他的拳头和脚踢，对怪兽进行了猛烈的攻击。

虽然怪兽非常强大，但奥特曼不放弃。他坚持不懈地战斗，最终成功地打败了怪兽，拯救了小城市的人们。

人们对奥特曼充满了感激和敬佩，他们为奥特曼的勇敢和正义感而鼓掌。奥特曼收起巨大的身体，变回了原来的样子，微笑着对人们说：“不要害怕，我会一直保护你们。”

从那以后，奥特曼成为了人们心目中的英雄，每当有危险出现，他总会出现在人们身边，保护他们的安全。

小朋友，奥特曼故事就是这样，他是一个勇敢又强大的超级英雄，总是保护着地球上的人们。希望你喜欢这个故事！记得要勇敢和善良哦！
回答完毕
继续对话, 或用`结束持续对话`结束对话
--------------------
问题：？
以下是小爱的回答:  哎呀，不如换个方式再说一下啦！
以下是 CHATGPTAPI 的回答: 谢谢你的夸奖，小朋友！我很高兴你喜欢奥特曼的故事。如果你还有其他问题或者想听其他故事，随时告诉我哦！我会尽力回答和满足你的需求。祝你度过愉快的一天！
回答完毕
继续对话, 或用`结束持续对话`结束对话
--------------------
问题：捷德奥特曼是谁？
以下是小爱的回答:  
捷德奥特曼，是圆谷株式会社特摄剧《捷德奥特曼》中的主角，新生代英雄之一。贝利亚奥
特曼的儿子，同时也是赛罗奥特曼的伙伴。⁥在地球上，捷德奥特曼化身名为朝仓陆的少年
，与同伴们一同生活，并为了和平而与怪兽战斗，也是捷德奥特曼自身在守护世界的过程中
，寻找对自己最重要的事物。
以下是 CHATGPTAPI 的回答: 捷德奥特曼是奥特曼系列中的一个角色。他是奥特曼系列中的第二位奥特曼，也是第一个以机器人形态出现的奥特曼。

捷德奥特曼的真名叫做“捷德·斯特林格·奥特曼”，他来自一个叫“M78星云”的星球。捷德奥特曼的外观和普通奥特曼有所不同，他有着金色的外观和蓝色的眼睛。

捷德奥特曼的特点是他可以变形成为一个巨大的机器人，他的机器人形态非常强大，有着各种强力武器和装备。他可以使用火箭拳、飞行器和能量光束等武器来对抗怪兽。

捷德奥特曼的使命和其他奥特曼一样，就是保护地球上的人们免受怪兽的伤害。他总是勇敢地与怪兽战斗，保护人们的安全。

捷德奥特曼在奥特曼系列中扮演了重要的角色，他的形象深受小朋友们的喜爱。

希望这个简单的介绍能够帮助你了解捷德奥特曼！如果你还有其他问题，随时告诉我哦！
CHATGPTAPI 回答出错 Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 
'message': 'ubus server or device returned invalid result', 'data': 
{'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 
'app_ios_XDt65lVoeCgJujEBrx9Ic4zH8TNmsi'}}
继续对话, 或用`结束持续对话`结束对话
--------------------
问题：奥姆的故事？
Traceback (most recent call last):
  File "xiaogpt.py", line 5, in <module>
    main()
  File "/root/xiaogpt/xiaogpt/cli.py", line 165, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/xiaogpt/xiaogpt/xiaogpt.py", line 484, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/root/xiaogpt/xiaogpt/xiaogpt.py", line 424, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/root/xiaogpt/xiaogpt/xiaogpt.py", line 415, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
  File "/usr/local/lib/python3.8/dist-packages/miservice/minaservice.py", line 68, in player_get_status
    return await self.ubus_request(
  File "/usr/local/lib/python3.8/dist-packages/miservice/minaservice.py", line 32, in ubus_request
    result = await self.mina_request(
  File "/usr/local/lib/python3.8/dist-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/usr/local/lib/python3.8/dist-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_AuO3o5HgGmYtErfkj7LPJXKisU1dwV'}}
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<MiGPT.poll_latest_ask() running at /root/xiaogpt/xiaogpt/xiaogpt.py:102> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fd24156cd00>()]>>
Exception ignored in: <coroutine object MiGPT.poll_latest_ask at 0x7fd241565940>
RuntimeError: coroutine ignored GeneratorExit

**Comment by yihong0618** [comment]
小爱的 ubus 可能有问题了，重启下小孩同学和 xiaogpt

**Comment by wxjun2018** [comment]
> 小爱的 ubus 可能有问题了，重启下小孩同学和 xiaogpt

能否让脚本抛出异常 但是不退出程序

**Comment by yihong0618** [comment]
不能。
