### ISSUE TITLE
支持使用使用潘多拉（Pandora）项目吗

### ISSUE THREAD

**Issue by m8458246** [yihong0618/xiaogpt#336]
对于chatgpt API免费版过期的人，想要白嫖，此项目支持潘多拉（/pengzhile/pandora）项目吗，它可以将access token改为API，但是需要配置服务器地址，有大佬提示下如何配置吗。

**Comment by yihong0618** [comment]
目前不支持
PR welcome~ 我们之后也会看看

**Comment by dadaoerv** [comment]
不直接支持，其实配合base url是可以实现的

**Comment by BR1981** [comment]
项目的base url从哪里修改呢？
