### ISSUE TITLE
关于使用Bard模式，为什么还要输入openAI key，和board token的验证问题

### ISSUE THREAD

**Issue by wangrui1573** [yihong0618/xiaogpt#337]
1.测试发现使用Bard模式，还是要输入GPT KEY，我随便输了一个可以
2.bard token获取之后还是不正确，该怎么取得

![image](https://github.com/yihong0618/xiaogpt/assets/42831156/fd56eb96-9a63-4bac-9254-f9bf8a7f0b1b)

![image](https://github.com/yihong0618/xiaogpt/assets/42831156/d8f543ed-e189-4082-b902-ad59971b692f)

**Comment by wangrui1573** [comment]
配置如下:
![image](https://github.com/yihong0618/xiaogpt/assets/42831156/d4f2dee2-9966-430c-b9bb-81947747de07)

**Comment by yihong0618** [comment]
@wangrui1573  我今天或者明天看一下哈。

**Comment by wangrui1573** [comment]
要更新这个
https://github.com/dsdanielpark/Bard-API/issues/155

**Comment by yihong0618** [comment]
看起来是上游挂了，有兴趣看看提个 PR 么？

**Comment by wangrui1573** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/42831156/ec9563c8-0d86-406b-a1fd-1cc359b73898)
按上面的issue链接，不同地区需要多个cookie才能使用，是一个数组

最终按上图，重新生成cookie解决了，bard模式下，openai_key乱填确实有用

**Comment by yihong0618** [comment]
@wangrui1573 修复了，等 CI 跑完可以再试试
