### ISSUE TITLE
建议完善配置文件的设置，运行更为简单一些。

### ISSUE THREAD

**Issue by dadaoerv** [yihong0618/xiaogpt#338]
1. 目前很多项目都支持使用one api这样的平台，整合azure，讯飞，百度，openai等的调用。使用上也很简单，本项目只需要调用one api的key和base url即可。那么小爱同学支持的大语言模型将更为广泛。小爱同学，你是谁？我是百度xxx，岂不是美哉。
2. 建议建立一个统一的config文件，运行xiaoai.py这样去调用配置文件，上面的这些就可以实现了。而不用加命令--

**Comment by fxconfig** [comment]
自己改改就好了，就两三句代码的事情
dic = Config.read_from_file
config = Config(**dic)
miboy = MiGPT(config)
run~~~~~

**Comment by yihong0618** [comment]
我们研究下，谢谢

**Comment by superwiboy** [comment]
最近one api支持gemini API调用了
