### ISSUE TITLE
是否考虑接入上网搜索功能

### ISSUE THREAD

**Issue by xieqiwen1994** [yihong0618/xiaogpt#339]
hello，请问是否计划计入类似这个项目中的使用bing-search搜索功能。
https://github.com/goldfishh/chatgpt-on-wechat/blob/master/plugins/tool/README.md#7-bing-search-

**Comment by xieqiwen1994** [comment]
效果类似这样。 如果能把这个功能接入小爱，可玩性又增加了。     
![1695358653640](https://github.com/yihong0618/xiaogpt/assets/22072746/ff70b565-e309-44b3-9b6f-163fe81d843b)

**Comment by xieqiwen1994** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/22072746/89c9c5be-8193-4dec-88bc-488be46928eb)

缺点可能是上网后搜索结果要chatgpt处理， 消耗的token可能会有些多， 用gpt3.5可能这个消耗不会那么有感知。

**Comment by yihong0618** [comment]
可以。我们试试

**Comment by frostming** [comment]
Supported by LangChain bot
