### ISSUE TITLE
使用glm模型会提示[1220][您无权访问chatglm_130b。]

### ISSUE THREAD

**Issue by momo325** [yihong0618/xiaogpt#342]
![image](https://github.com/yihong0618/xiaogpt/assets/68660594/3e114a2f-d7e8-4e8e-804b-137a0af3ceb5)
可以确保的是，我的config文件中的key是正确的
![image](https://github.com/yihong0618/xiaogpt/assets/68660594/f6363836-4f80-4137-8111-eacd6fac6f37)

**Comment by yihong0618** [comment]
你这个 key 可能没有 130b 的权限？可以本地用代码确认下。

**Comment by momo325** [comment]
这个如何确认有没有这个权限呢？我是免费账户，是否需要修改config.json文件使用免费模型？感谢

**Comment by momo325** [comment]
@yihong0618 这个如何确认有没有这个权限呢？我是免费账户，是否需要修改config.json文件使用免费模型？感谢

**Comment by momo325** [comment]
> 你这个 key 可能没有 130b 的权限？可以本地用代码确认下。

@yihong0618 这个如何确认有没有这个权限呢？我是免费账户，是否需要修改config.json文件使用免费模型？感谢

**Comment by yihong0618** [comment]
@momo325 访问他们的网站里面有 playground, 另外是他们的参数改了，现在应该可以了？

**Comment by yihong0618** [comment]
@momo325 不客气！
