### ISSUE TITLE
gpt回答的时候，打印出来答案，但是小爱说敏感信息。

### ISSUE THREAD

**Issue by jacket230** [yihong0618/xiaogpt#343]
gpt回答的时候，打印出来答案，但是小爱说敏感信息。LX05，是不是被xiaomi屏蔽了？

**Comment by jacket230** [comment]
内含敏感信息。：——）

**Comment by dongjing007** [comment]
是的，我也出现过，答案最终调用到小米的云端，tts朗读，被过滤拦截了。😂

**Comment by dongjing007** [comment]
是的，我也出现过，有些答案会包含敏感字，被xiaomi拦截😂

**Comment by yihong0618** [comment]
> 是的，我也出现过，有些答案会包含敏感字，被xiaomi拦截😂

我们不需要小米的答案啊

**Comment by dongjing007** [comment]
> > 是的，我也出现过，有些答案会包含敏感字，被xiaomi拦截😂
> 
> 我们不需要小米的答案啊

答案会通过MiServer tts朗读出来，这一步xiaomi会拦截过滤

**Comment by yihong0618** [comment]
我们可以过滤下，我试试

**Comment by yihong0618** [comment]
问啥敏感啊。。。

**Comment by dongjing007** [comment]
> 问啥敏感啊。。。

比如，请评价一下恒.大xujiayin，对返回的结果朗读时，就提示敏感，这种比较难过滤吧。

**Comment by sj1531122** [comment]
我问的问题是：中国有多少个党派，gpt3也是回答敏感信息。

**Comment by frostming** [comment]
这没办法吧，可以改用edge tts

**Comment by muzizongheng** [comment]
> 这没办法吧，可以改用edge tts

换了tts 引擎就可以吗？ 我现在也是遇到这个说有敏感词的问题

**Comment by yihong0618** [comment]
> > 这没办法吧，可以改用edge tts
> 
> 换了tts 引擎就可以吗？ 我现在也是遇到这个说有敏感词的问题

可以试试

**Comment by HarborC** [comment]
换了edge，敏感词的问题好像有所缓解，但是换了tts 引擎 为edge ，小爱会说到一般开始放音乐是啥情况 orz。

**Comment by yihong0618** [comment]
> 换了edge，敏感词的问题好像有所缓解，但是换了tts 引擎 为edge ，小爱会说到一般开始放音乐是啥情况 orz。

😂是每次都这样么？

**Comment by yihong0618** [comment]
> 换了edge，敏感词的问题好像有所缓解，但是换了tts 引擎 为edge ，小爱会说到一般开始放音乐是啥情况 orz。

现在不会了，已经修复

**Comment by HarborC** [comment]
> > 换了edge，敏感词的问题好像有所缓解，但是换了tts 引擎 为edge ，小爱会说到一般开始放音乐是啥情况 orz。
> 
> 现在不会了，已经修复

这个问题现状是tts使用edge可以解决敏感词问题，并且不会出现中途放音乐的情况，但是原有还是会出现铭感词问题对吧
