### ISSUE TITLE
使用newbing应该怎么设置

### ISSUE THREAD

**Issue by uuskys** [yihong0618/xiaogpt#346]
能给给个示例吗

**Comment by yihong0618** [comment]
好久没用 new bing 了我不确定还好不好用（上游不维护了
我周末确认下

**Comment by naoki66** [comment]
是否在配置config.json设置？

  "bot": "newbing",
  "bing_cookie_path": "/config/bing_cookies.json",
我如此设置了 并没有反应

**Comment by imhut** [comment]
> 好久没用 new bing 了我不确定还好不好用（上游不维护了 我周末确认下

目前new bing还是可以用的，目前EDGEGPT上游确实不维护了，不过还有分支在维护，https://github.com/jacobgelling/EdgeGPT

git+https://github.com/F33RNI/EdgeGPT@main#egg=EdgeGPT

**Comment by yihong0618** [comment]
> > 好久没用 new bing 了我不确定还好不好用（上游不维护了 我周末确认下
> 
> 目前new bing还是可以用的，目前EDGEGPT上游确实不维护了，不过还有分支在维护，https://github.com/jacobgelling/EdgeGPT
> 
> git+https://github.com/F33RNI/EdgeGPT@main#egg=EdgeGPT

谢谢
