### ISSUE TITLE
azure配置好之后运行报错

### ISSUE THREAD

**Issue by huangxiangdan** [yihong0618/xiaogpt#347]
日志如下：
`问题：查一下吴江五等于几？
以下是小爱的回答:  这个小爱还在学习呢，不如你问我，你会做什么，先了解一下我的功能吧
以下是 CHATGPTAPI 的回答: [10/21/23 22:11:19] DEBUG    Edge TTS with voice=zh-CN-XiaoxiaoNeural                                    xiaogpt.py:347
                    ERROR    'ChatGPTBot' object has no attribute 'deployment_id'                        xiaogpt.py:391`

抱歉因为不熟悉python，没法直接提pr。
将
`if openai.api_type == "azure":
            kwargs["deployment_id"] = self.deployment_id`
改为
`if openai.api_type == "azure":
            kwargs["deployment_id"] = self.default_options["engine"]`
即可正常运行。

所以此处应该是个bug。麻烦修复下。
另外给使用azure的同学做个参考：
--deployment_id gpt-35-turbo(直接命名为model_name，这样各种api兼容性比较好) --api_base https://xxx(resource_name).openai.azure.com 这样使用即可

**Comment by yihong0618** [comment]
谢谢，我们更新下

**Comment by cxjava** [comment]
# azure base url 是类似这样的`https://xxxx-bbbb.openai.azure.com/`
<img width="1057" alt="Snipaste_2023-10-30_11-03-39" src="https://github.com/yihong0618/xiaogpt/assets/802316/4e17ee74-1970-4a12-8fa4-ce9e3207c6d4">

# 如何找到deployment_id：

<img width="680" alt="Snipaste_2023-10-30_11-03-59" src="https://github.com/yihong0618/xiaogpt/assets/802316/7d923c16-facf-4a8f-9362-a2b1ebfd63da">

# 如下的deployment_id是 `gpt-test`:

<img width="927" alt="Snipaste_2023-10-30_11-07-28" src="https://github.com/yihong0618/xiaogpt/assets/802316/b073c34c-fd9e-42a2-a5cb-dbbfc0462fb3">

那么配置文件应该设置为：
```json
{
  "hardware": "LX06",
  "account": "",
  "password": "",
  "glm_key": "",
  "bard_token": "",
  "serpapi_api_key": "",
  "cookie": "",
  "mi_did": "",
  "use_command": false,
  "mute_xiaoai": true,
  "verbose": false,
  "bot": "chatgptapi",
  "enable_edge_tts": false,
  "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
  "prompt": "请用100字以内回答",
  "keyword": ["请问"],
  "change_prompt_keyword": ["更改提示词"],
  "start_conversation": "开始持续对话",
  "end_conversation": "结束持续对话",
  "stream": false,
  "proxy": "",
  "gpt_options": {},
  "bing_cookie_path": "",
  "bing_cookies": {},
  "openai_key": "abcdefg",
  "api_base": "https://xxxx-bbbb.openai.azure.com/",
  "deployment_id": "gpt-test",
  "localhost": true
}
```

**Comment by jingtaozhang18** [comment]
<img width="539" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/64130990/70072569-4228-474f-a931-2625c78554d0">
启动之后，没有收到GPT的回答，请问如何看一下日志，是哪里出错了

**Comment by yihong0618** [comment]
—verbose

**Comment by jingtaozhang18** [comment]
<img width="1422" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/64130990/2899abe0-ff2c-4304-ba1d-b2ff4a8a3729">
添加这个日志之后，并没有说哪里出了问题，卡在了xiaogpt.py:64

**Comment by jingtaozhang18** [comment]
我已经可以在本地通过直接请求Azure Open AI的API接口
<img width="1407" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/64130990/b8ae3999-108c-42c6-be05-71231b5f6a28">

**Comment by jingtaozhang18** [comment]
可能是我的网络问题，今天早上可以运行成功了

**Comment by yihong0618** [comment]
> 可能是我的网络问题，今天早上可以运行成功了

好的

**Comment by Saintoliver** [comment]
> # azure base url 是类似这样的`https://xxxx-bbbb.openai.azure.com/`
> <img alt="Snipaste_2023-10-30_11-03-39" width="1057" src="https://private-user-images.githubusercontent.com/802316/278928911-4e17ee74-1970-4a12-8fa4-ce9e3207c6d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYwMDgsIm5iZiI6MTcxMzQ0NTcwOCwicGF0aCI6Ii84MDIzMTYvMjc4OTI4OTExLTRlMTdlZTc0LTE5NzAtNGExMi04ZmE0LWNlOWUzMjA3YzZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMzA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjNkOTE0NjVjNzQzYzFiOTkxOWY0NDBkYTM1MGY4OTg5YWQ4M2Q3YTI0MTU0NDhhODFmYTg3ZGYwODE4ODVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mrk6gPNtRvNlpl_1aQ6CpmIVnbsktCUxQupTWrYYRqI">
> # 如何找到deployment_id：
> <img alt="Snipaste_2023-10-30_11-03-59" width="680" src="https://private-user-images.githubusercontent.com/802316/278928986-7d923c16-facf-4a8f-9362-a2b1ebfd63da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYwMDgsIm5iZiI6MTcxMzQ0NTcwOCwicGF0aCI6Ii84MDIzMTYvMjc4OTI4OTg2LTdkOTIzYzE2LWZhY2YtNGE4Zi05MzYyLWEyYjFlYmZkNjNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMzA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjQ0Y2Y5NDU2OTk0YzNiMmI0YTUyYWFiOTAzNjMxN2FlYzcxZDg3MjlkNDRhOGFiMDg5ZGQ2YzU2Y2ZjMTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6d1qcKJBahrBWk2RNtAu8_Sy_EYDyGfBsMOVZ8Y5tIs">
> # 如下的deployment_id是 `gpt-test`:
> <img alt="Snipaste_2023-10-30_11-07-28" width="927" src="https://private-user-images.githubusercontent.com/802316/278929016-b073c34c-fd9e-42a2-a5cb-dbbfc0462fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDYwMDgsIm5iZiI6MTcxMzQ0NTcwOCwicGF0aCI6Ii84MDIzMTYvMjc4OTI5MDE2LWIwNzNjMzRjLWZkOWUtNDJhMi1hNWNiLWRiYmZjMDQ2MmZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMzA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjk0MmZiYzZkYzQ1ODQwOGE5OTc5ZTA1N2UzMmUyNjUzNzFmNzk0MzI5ZjA1MDYyOWEwNDM2MjA5NDQ4YTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g85heN6eJKSfwjgHAOxxG85yDikNBZkNZTfJEXF9PKY">
> 那么配置文件应该设置为：
> 
> ```json
> {
>   "hardware": "LX06",
>   "account": "",
>   "password": "",
>   "glm_key": "",
>   "bard_token": "",
>   "serpapi_api_key": "",
>   "cookie": "",
>   "mi_did": "",
>   "use_command": false,
>   "mute_xiaoai": true,
>   "verbose": false,
>   "bot": "chatgptapi",
>   "enable_edge_tts": false,
>   "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
>   "prompt": "请用100字以内回答",
>   "keyword": ["请问"],
>   "change_prompt_keyword": ["更改提示词"],
>   "start_conversation": "开始持续对话",
>   "end_conversation": "结束持续对话",
>   "stream": false,
>   "proxy": "",
>   "gpt_options": {},
>   "bing_cookie_path": "",
>   "bing_cookies": {},
>   "openai_key": "abcdefg",  👈㊙️
>   "api_base": "https://xxxx-bbbb.openai.azure.com/", 👈㊙️
>   "deployment_id": "gpt-test", 👈㊙️
>   "localhost": true
> }
> ```

请问大佬是否要先注册，成功获取Create Azure OpenAI的服务？我每次都卡在了price tier 上了。
![image](https://github.com/yihong0618/xiaogpt/assets/116894295/2e638ae5-97a4-4b8b-b738-a3ec2c234e0d)

**Comment by Saintoliver** [comment]
自问自答，已经找到了方案。

https://zhuanlan.zhihu.com/p/674880947

重要的是要用教育邮箱申请成功率高，前几次都是用一般邮箱申请，被驳回了5次。。。
