### ISSUE TITLE
--proxy参数在和--use_langchain配合后无法输出内容

### ISSUE THREAD

**Issue by yuan6785** [yihong0618/xiaogpt#348]
是否是因为proxy在langchain无法生效的原因？

**Comment by yuan6785** [comment]
OPENAI_API_KEY=***** SERPAPI_API_KEY=*****   http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118  /opt/software/anconda3/envs/py310_xiaogpt/bin/xiaogpt --account=*****  --password=*****  --hardware=L15A --proxy http://127.0.0.1:8118 --mute_xiaoai --use_langchain --stream

最终，我用了http全局代理 (http_proxy=http://127.0.0.1:8118 https_proxy=http://127.0.0.1:8118  )，是可以跑通的。

**Comment by yihong0618** [comment]
不客气！

**Comment by dongjing007** [comment]
请求langchain时，没有配置proxy，我来加一下吧。

**Comment by yihong0618** [comment]
@dongjing007 感谢。

**Comment by dongjing007** [comment]
> @dongjing007 感谢。

客气啦，我本地加上了，明天自测通过就提PR（要弄个代理比较麻烦 🤣

**Comment by dongjing007** [comment]
> @dongjing007 感谢。

客气啦，明天自测通过就提PR（要找个代理来测试，比较麻烦 🤣）

**Comment by yihong0618** [comment]
感谢～

**Comment by yihong0618** [comment]
fixed thanks @dongjing007
