### ISSUE TITLE
一台电脑上起多个进程多个用户会出现问题

### ISSUE THREAD

**Issue by NullpointerW** [yihong0618/xiaogpt#351]
多个进程会读取同一个mi.token，输入账户密码的情况下应该要忽略读取mitoken的流程吧？

**Comment by yihong0618** [comment]
@NullpointerW 目前不支持多个进程。
PR to support this welcome

**Comment by NullpointerW** [comment]
> @NullpointerW 目前不支持多个进程。 PR to support this welcome

我修改了下，不让它读取mitoken 现在可以起多个用户了

**Comment by yihong0618** [comment]
@NullpointerW nice

**Comment by yihong0618** [comment]
@NullpointerW 目前输入账号密码也需要读这个 token....

**Comment by NullpointerW** [comment]
> @NullpointerW 目前输入账号密码也需要读这个 token....

可我删掉了mitoken 也能登录啊，只不过要再获取一次token写入到新的mitoken

**Comment by yihong0618** [comment]
是的，但是有些功能需要读 device_id 啥的，理论上改改可以支持多用户，我们看看怎么设计好

**Comment by NullpointerW** [comment]
还有请问下，进入gpt模式的提示音如何修改？@yihong0618

**Comment by yihong0618** [comment]
什么提示音？正在问？

**Comment by NullpointerW** [comment]
> 什么提示音？正在问？

就是说出提示词后 音响会有“叮”一声提示音进入连续对话模式，这个音效能改吗？
