### ISSUE TITLE
使用bard时出错

### ISSUE THREAD

**Issue by uuskys** [yihong0618/xiaogpt#352]
报错如下，是不是跟代理有关？
问题：你能干什么？
以下是小爱的回答:  
我可以为你播放音乐，控制设备，查询信息，设置提醒，设置闹钟，我的能力还在不断增加，你可以在小爱音箱app上查看我的所有技能。
以下是 BARD 的回答: AsyncClient.post() got an unexpected keyword argument 'proxies'
BARD 回答出错 cannot access local variable 'r' where it is not associated with a value

**Comment by yihong0618** [comment]
pip install -U httpx
