### ISSUE TITLE
能增加一个开关吗，就是针对【目前已知 LX04、X10A 和 L05B L05C 可能需要使用 --use_command】

### ISSUE THREAD

**Issue by xiaobingwudi** [yihong0618/xiaogpt#363]
我调试了 L05B，终端有gpt的回答，但是就是不发出gpt内容的声音，这个问题，又什么好的解决办法吗？

**Comment by yihong0618** [comment]
没有，这几个型号只能使用 --use_command

**Comment by xiaobingwudi** [comment]
你的邮件我已经收到了，这是一个邮件回执

**Comment by xiaobingwudi** [comment]
请问--use_command 怎么用呀发自我的手机-------- 原始邮件 --------发件人： yihong ***@***.***>日期： 2023年11月1日周三 上午9:26收件人： yihong0618/xiaogpt ***@***.***>抄送： xiaobingwudi ***@***.***>, Author ***@***.***>主    题： Re: [yihong0618/xiaogpt] 能增加一个开关吗，就是针对【目前已知 LX04、X10A 和 L05B L05C 可能需要使用 --use_command】 (Issue #363)
没有，这几个型号只能使用 --use_command

**Comment by xiaobingwudi** [comment]
> 没有，这几个型号只能使用 --use_command

请问大佬，具体是怎么样使用呀？

**Comment by duolabmeng6** [comment]
我也遇到了这个情况但是golang版本是可以的

**Comment by xiaobingwudi** [comment]
请问有来源地址吗？

**Comment by duolabmeng6** [comment]
这个项目最底下这个golang的 比py版本聊起来舒服...py版本断 很烦  .... golang 几乎100成功
