### ISSUE TITLE
小爱音箱可以读取l05b的chaggpt内容了，但是读不全，只能读取前面几个字，要么就是提醒网络连接错误，请重新再试吧

### ISSUE THREAD

**Issue by xiaobingwudi** [yihong0618/xiaogpt#364]
我的服务器是国内的，带宽是6M的，用的是openai.azure，chatgpt终端可以很快的显示结果，但是语音播报的时候，就不行了，要么读不全，要么没有声音，要么“就是提醒网络连接错误，请重新再试吧”，请问大佬，这个是什么原因呀，如何解决呀

**Comment by yihong0618** [comment]
参考 README 先保证 tts 能运行
另外 l05b 无法 stream 无法 mute-xiaoai
