### ISSUE TITLE
lx04实施的问题记录，还希望帮忙指导下

### ISSUE THREAD

**Issue by sweetowen** [yihong0618/xiaogpt#365]
lx04实施的问题记录，还希望帮忙指导下：
注：其中2和3我是直接重新装一遍不确定是否存在问题（pip install -U --force-reinstall xiaogpt），还是需要先卸载下才行？
    1.音箱显示屏提示连续对话是实验室功能只适用于音乐场景（其它场景等陆续开放），可能这个导致“持续对话”还是需要每次先“小爱同学”唤醒，这样每次小爱也会回答，连续对话的效果体验基本没有了；
    2.mute小爱发言效果一般，按最新代码把await那行注掉了也是同样效果；（#await asyncio.sleep(1 - d)）
    3.想修改“开始持续对话”的提示词，直接改了代码中的默认配置，但发现不生效，后面改用配置文件方式才生效；
    4.让它用英文回答长结果时（比如china technology，总共有3段），回答完最后一句会傻等半天不结束，看日志能明显发现，有时我不知道再提新的问题，它有时还会抛异常；看异常和stream相关，xiaogpt.py的391和401行；
    5.英文回答时读起来非常明显的中式英语不连贯，本来尝试改别的tts试下，发现用edge-tts不生效，可能只能通过--use-command的方式来使用小米的tts；
    6.建议“mi_did”也能变成命令行参数，现在好像不能，这样命令行和配置文件同时生效，我就可以一份配置文件通过两个命令去运行两个设备（家里还有台更老的lx01等着用起来给父母体验），多个配置文件维护容易遗漏修改；

**Comment by yihong0618** [comment]
以上问题都因为 lx04 无法 mute 小爱 stream 功能也依赖这个。
参考 readme 下方的不支持型号

**Comment by sweetowen** [comment]
> 以上问题都因为 lx04 无法 mute 小爱 stream 功能也依赖这个。 参考 readme 下方的不支持型号

好的，感谢回复！
那我当前执行的命令是这种：xiaogpt --hardware LX04 --mute_xiaoai --stream --use_command --use_chatgpt_api

建议是改成如下这种吗？去掉mute和stream参数会更稳定？
 xiaogpt --hardware LX04 --use_command --use_chatgpt_api

**Comment by yihong0618** [comment]
不会更稳定，会跟你之前一样。。。因为 `--mute_xiaoai --stream ` 这两个其实你那里没用到针对 lx04

**Comment by sweetowen** [comment]
> 不会更稳定，会跟你之前一样。。。因为 `--mute_xiaoai --stream ` 这两个其实你那里没用到针对 lx04

好的，了解了，感谢！
那只能希望lx04的米家固件能尽快升级支持连续对话了，那样体验也许能好不少，哈哈。要不只能换设备了。
