### ISSUE TITLE
module 'openai' has no attribute 'aiosession'

### ISSUE THREAD

**Issue by Ginsaka-You** [yihong0618/xiaogpt#368]
在对话时，可以获得小爱的回答，但获得 gpt 的回答时显示 module 'openai' has no attribute 'aiosession'。使用设备 LX06

**Comment by Ginsaka-You** [comment]
<img width="695" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/12579943/fc492488-5bb1-46b1-9e09-79f4f2ee2da1">

**Comment by yihong0618** [comment]
python -m pip install -U openai

**Comment by yihong0618** [comment]
pip install openai==0.27.2

**Comment by Ginsaka-You** [comment]
<img width="1311" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/12579943/02871749-7f0e-46fe-8045-f040c137c923">

并且在尝试 --upgrade --force-reinstall 之后依然出现 module 'openai' has no attribute 'aiosession'

**Comment by yihong0618** [comment]
> <img alt="image" width="695" src="https://user-images.githubusercontent.com/12579943/280933852-fc492488-5bb1-46b1-9e09-79f4f2ee2da1.png">

另外别用 gpt3 用 chatgptapi~

**Comment by Ginsaka-You** [comment]
> > <img alt="image" width="695" src="https://user-images.githubusercontent.com/12579943/280933852-fc492488-5bb1-46b1-9e09-79f4f2ee2da1.png">
> 
> 另外别用 gpt3 用 chatgptapi~

哈哈，感谢感谢
