### ISSUE TITLE
有个问题，是不是得专门用台电脑来着挂着程序才能实现小爱一直对接gpt

### ISSUE THREAD

**Issue by Kar1chan** [yihong0618/xiaogpt#371]

**Comment by yihong0618** [comment]
linux 树莓派，或者用一些 hack 手段阿里云腾讯云都行

**Comment by frostming** [comment]
这个项目是hack向的，面向愿意折腾的「玩家」
面向用户的类似项目，会封装得比较好，有 [这位大佬的魔改火火兔](https://space.bilibili.com/495999206)
