### ISSUE TITLE
是否可以使用one-api支持开源模型. 

### ISSUE THREAD

**Issue by leavegee** [yihong0618/xiaogpt#378]
虽然能力是差点意思. 但是不用联网更不用魔法
比如接入CHATGLM3-B6

**Comment by yihong0618** [comment]
one-api 指的是？

**Comment by superwiboy** [comment]
> @leavegee one-api 指的是？ 但这个项目一定需要联网的需要请求 xiaomi...不用魔法的话现在支持 GLM

https://github.com/songquanpeng/one-api?tab=readme-ov-file#one-api
