### ISSUE TITLE
有gpt4的api key, 去代码里改了model 后的参数为gpt4,但是调用时还是gpt3，点解？

### ISSUE THREAD

**Issue by ggy1021** [yihong0618/xiaogpt#379]
有gpt4的api key, 去代码里改了model 后的参数为gpt4,但是调用时还是gpt3，点解？

**Comment by yihong0618** [comment]
--use_chatgptapi 么？

**Comment by ggy1021** [comment]
--use chatgptapi 不稳定，很大概率connect error,  --use gpt3 稳定一些，但是两个都改了model部分的参数后，试验一下，后台显示依然都消耗的gpt3的token

**Comment by yihong0618** [comment]
use gpt3 不能改 model

**Comment by ggy1021** [comment]
![20231124-140531](https://github.com/yihong0618/xiaogpt/assets/48542695/00ec8414-7533-45d8-bcdf-068c82d0eeee)
class ChatGPTBot(ChatHistoryMixin, BaseBot):

    default_options: ClassVar[dict[str, str]] = {"model": "gpt-4-0314"}
    openai_key: str
    api_base: str | None = None
    proxy: str | None = None
    deployment_id: str | None = None
    history: list[tuple[str, str]] = dataclasses.field(default_factory=list, init=False)

**Comment by ggy1021** [comment]
用这个--use chatgptapi   也改了对应位置的model参数后，用--use chatgptapi 回答成功了，但是看上去依然是gpt3的答案

**Comment by yihong0618** [comment]
理论上已经是 3.5 路我们看看

**Comment by ggy1021** [comment]
> 理论上已经是 3.5 路我们看看

是3.5了。

**Comment by yihong0618** [comment]
好的我先关了哈
