### ISSUE TITLE
用cookie也login failed

### ISSUE THREAD

**Issue by spart9527** [yihong0618/xiaogpt#380]
大佬帮忙看下，qnap docker下安装的，两种办法
1、环境变量里添加了cookie，不论内容是等于手机抓包完整的内容（从deviceId开头，到serviceToken，再到最后一段userId），还是cookie=serviceToken的内容；（所以这个cookie到底应该怎样填。。）

2、环境变量里添加account和password，没有cookie

都报同样的错误：
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_XXXXXXX: Login failed

**Comment by yihong0618** [comment]
cookie 应该目前无法添加 config 
参考这个 https://github.com/yihong0618/xiaogpt/issues/332

**Comment by spart9527** [comment]
> cookie 应该目前无法添加 config 参考这个 #332

嗯嗯，前面看了这个，但是小白没看懂token要怎么取，怎么放，放到哪里。。

谢谢大佬的及时回复

**Comment by spart9527** [comment]
> cookie 应该目前无法添加 config 参考这个 #332

大佬，我在Windows里拿到token文件了，服务部署在qnap的NAS上，这个文件传上去就消失了（好像被删了），请教一下怎么弄。。
