### ISSUE TITLE
'str' object has no attribute 'choices'

### ISSUE THREAD

**Issue by qiqiandfei** [yihong0618/xiaogpt#383]
问题描述：
配置文件中我删除了proxy的设置，因为如果不删除，会提示“Unknown scheme for proxy URL URL('')”，删除proxy配置后可以正常运行和正常提问。提问后的报错见log，s12和LX05的音箱都遇到了同样的问题。apikey是从水龙头白嫖的，不知道是否有影响？

日志:
Running xiaogpt now, 用请问开头来提问
或用开始持续对话开始持续对话
--------------------
问题：中国什么时候能捧起大力神杯？
以下是小爱的回答:  问题太有水平了，待我去学习一下
以下是 CHATGPTAPI 的回答: CHATGPTAPI 回答出错 'str' object has no attribute 'choices'

配置：
{
  "hardware": "s12",
  "account": "xxxxxx",
  "password": "xxxxx",
  "openai_key": "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "glm_key": "",
  "bard_token": "",
  "serpapi_api_key": "",
  "cookie": "",
  "mi_did": "84416281",
  "use_command": true,
  "mute_xiaoai": true,
  "verbose": false,
  "bot": "chatgptapi",
  "tts": "mi",
  "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
  "prompt": "请用100字以内回答",
  "keyword": ["请问"],
  "change_prompt_keyword": ["更改提示词"],
  "start_conversation": "开始持续对话",
  "end_conversation": "结束持续对话",
  "stream": false,
  "gpt_options": {},
  "bing_cookie_path": "",
  "bing_cookies": {},
  "api_base": "https://openkey.cloud",
  "deployment_id": "",
  "localhost": true
}

mcli list：
  "name": "小米AI音箱",
    "model": "xiaomi.wifispeaker.s12",
    "did": "",
    "token": ""

**Comment by yihong0618** [comment]
@qiqiandfei 你把这个 issue 删了重新提一个吧。。。暴露 token 了
