### ISSUE TITLE
bot 名称能否由“chatgptapi”改成“chatGPTAPI"

### ISSUE THREAD

**Issue by ccwssy** [yihong0618/xiaogpt#384]
大佬，我的音箱型号是L05C 使用的 --use_command。
每次小爱调用chatgpt，都会说一句：正在问chatgptapi，而这个chatgptapi因为全是小写，小爱会把”chatgptapi“当成一个整体的英文单词，发音会很奇怪.
如果名称改写成大写的”chatGPTAPI",会正常发音成 “chat""GPT"API。
大家在使用是否也有这个问题？

**Comment by yihong0618** [comment]
@ccwssy 修复了，使用代码运行的话 git pull 
使用 pypi 或者 docker 的话稍等我发版本
