### ISSUE TITLE
'str' object has no attribute 'choices'

### ISSUE THREAD

**Issue by qiqiandfei** [yihong0618/xiaogpt#386]
问题描述：
配置文件中我删除了proxy的设置，因为如果不删除，会提示“Unknown scheme for proxy URL URL('')”，删除proxy配置后可以正常运行和正常提问。提问后的报错见log，s12和LX05的音箱都遇到了同样的问题。apikey是从水龙头白嫖的，不知道是否有影响？

日志:
Running xiaogpt now, 用请问开头来提问
或用开始持续对话开始持续对话
问题：中国什么时候能捧起大力神杯？
以下是小爱的回答: 问题太有水平了，待我去学习一下
以下是 CHATGPTAPI 的回答: CHATGPTAPI 回答出错 'str' object has no attribute 'choices'

配置：
{
"hardware": "s12",
"account": "xxxxxx",
"password": "xxxxx",
"openai_key": "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"glm_key": "",
"bard_token": "",
"serpapi_api_key": "",
"cookie": "",
"mi_did": "84416281",
"use_command": true,
"mute_xiaoai": true,
"verbose": false,
"bot": "chatgptapi",
"tts": "mi",
"edge_tts_voice": "zh-CN-XiaoxiaoNeural",
"prompt": "请用100字以内回答",
"keyword": ["请问"],
"change_prompt_keyword": ["更改提示词"],
"start_conversation": "开始持续对话",
"end_conversation": "结束持续对话",
"stream": false,
"gpt_options": {},
"bing_cookie_path": "",
"bing_cookies": {},
"api_base": "https://openkey.cloud/",
"deployment_id": "",
"localhost": true
}

mcli list：
"name": "小米AI音箱",
"model": "xiaomi.wifispeaker.s12",
"did": "xxxxxx",
"token": "xxxxxxx"

**Comment by yihong0618** [comment]
pip install -U openai

**Comment by qiqiandfei** [comment]
感谢回复 晚上回去试试！

**Comment by qiqiandfei** [comment]
> pip install -U openai

请问这个命令是要在容器里运行的吧？

**Comment by yihong0618** [comment]
容器？那应该不是
"api_base": "https://openkey.cloud/", 你看看这个 是不是后面需要有个 v1
"api_base": "https://openkey.cloud/v1"

**Comment by qiqiandfei** [comment]
我用的是从[](https://faucet.openkey.cloud/)申请的apikey，api_base应该是对的
![image](https://github.com/yihong0618/xiaogpt/assets/31001002/9ae62aed-75a0-45f7-a20c-7123caefb0ce)
“pip install -U openai”这个命令看上去像是安装一个openai的第三方库，我应该在哪里执行呢？群晖上执行？还是docker exec -it xxx bash进入到容器里再执行？

**Comment by yihong0618** [comment]
> 我用的是从https://faucet.openkey.cloud/申请的apikey，api_base应该是对的 ![image](https://private-user-images.githubusercontent.com/31001002/286859331-9ae62aed-75a0-45f7-a20c-7123caefb0ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzI4NTIsIm5iZiI6MTcwMTMzMjU1MiwicGF0aCI6Ii8zMTAwMTAwMi8yODY4NTkzMzEtOWFlNjJhZWQtNzVhMC00NWY3LWEyMGMtNzEyM2NhZWZiMGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4MjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YmEyNWVlMDI3NzdkZTFkNDNjOWYxYWU4MzBmMDMyNmQ2M2FkNGZkNGY4ZGE2MTZiMWZlZGRkZjNjMjU4OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ugNyD3oTpUluaBRFznmkOMCEsaEA_wr1Se3nKml9GkQ) “pip install -U openai”这个命令看上去像是安装一个openai的第三方库，我应该在哪里执行呢？群晖上执行？还是docker exec -it xxx bash进入到容器里再执行？

你可以先确认下这个可用么？这个 key

**Comment by yihong0618** [comment]
@qiqiandfei 或者拉下最新镜像试试

**Comment by qiqiandfei** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/31001002/379bd938-4012-4e63-8990-cac56c401e2d)
![image](https://github.com/yihong0618/xiaogpt/assets/31001002/b135490b-90e3-43fa-8393-4feb5e3fa9e7)
![image](https://github.com/yihong0618/xiaogpt/assets/31001002/7488dd40-eb7c-4f1d-b9b0-b1ff38f153d8)
我确认了这个可以是可用的，然而还是有同样的错误~
![image](https://github.com/yihong0618/xiaogpt/assets/31001002/940226e3-c21f-4bd7-97fc-238cb8a355c1)

**Comment by yihong0618** [comment]
@qiqiandfei 你需要确认程序调用可用。。。
利用 openai 这个库

**Comment by qiqiandfei** [comment]
这个要如何确认呢？

**Comment by yihong0618** [comment]
https://github.com/openai/openai-python

参考 readme

**Comment by qiqiandfei** [comment]
<img width="662" alt="9e5a7d855a7ccca871131bf182413fb" src="https://github.com/yihong0618/xiaogpt/assets/31001002/74f3ecf4-df8c-4b49-99d2-9c8f5b70293d">
两个问题
1、换了原版的key和api地址
2、添加了对s12型号的支持。
现在问题应该已经解决了！

**Comment by qiqiandfei** [comment]
经测试 实际上白嫖的key也是能用的 要在api_base后面加上“/v1”  比如 “https://openkey.cloud” => "https://openkey.cloud/v1"

**Comment by yihong0618** [comment]
> 经测试 实际上白嫖的key也是能用的 要在api_base后面加上“/v1” 比如 “[https://openkey.cloud”](https://openkey.cloud%E2%80%9D) => "https://openkey.cloud/v1"

我不是回过了么。。。你不信我

![image](https://github.com/yihong0618/xiaogpt/assets/15976103/797530fb-3045-4b73-beea-ffdeee6bf690)
