### ISSUE TITLE
requirements.txt is empty

### ISSUE THREAD

**Issue by Annabelle0726** [yihong0618/xiaogpt#391]
after I entered the command: "pip install -r requirements.txt"
![image](https://github.com/yihong0618/xiaogpt/assets/97329962/11ff319f-a83b-4843-bed4-d3c93a67b364)
![image](https://github.com/yihong0618/xiaogpt/assets/97329962/af19fe10-2799-43c7-b756-7754e6d7bb9c)
it shows nothing, is it normal?

**Comment by yihong0618** [comment]
no…
can you try pip install xiaogpt?

**Comment by Annabelle0726** [comment]
yes, 
![image](https://github.com/yihong0618/xiaogpt/assets/97329962/9931bb15-34e6-4ccc-ac46-ee6eaba46673)

**Comment by yihong0618** [comment]
no idea why, you can check the file on web, its not empty

**Comment by frostming** [comment]
something on your machine unexpectedly overwrites the file, you should start from a brand new clone and try again, maybe without pycharm

**Comment by Annabelle0726** [comment]
ok got it, I use VS code instead. 
![image](https://github.com/yihong0618/xiaogpt/assets/97329962/200ec3cd-31a8-4d65-b57b-7c4f48219fcc)

**Comment by frostming** [comment]
@Annabelle0726 That's fine, so does it work?
