### ISSUE TITLE
接入Bard，以下是Bard的回答SNlM0e value not found in response. Check __Secure-1PSID value.

### ISSUE THREAD

**Issue by gaidan1983** [yihong0618/xiaogpt#393]
每次回答返回以下两行：
以下是Bard的回答SNlM0e value not found in response. Check __Secure-1PSID value.
Bard回答出错 local variable 'r' referenced before assignment

Bard的token是从网页cookie中拿到的

**Comment by yihong0618** [comment]
@gaidan1983 可能是上游问题，我今天查下。

**Comment by gaidan1983** [comment]
大佬，是否可以接入GPT4-Turbo，感觉3.5还是有点不够聪明

**Comment by yihong0618** [comment]
> 大佬，是否可以接入GPT4-Turbo，感觉3.5还是有点不够聪明

直接改 model 就行啊

**Comment by gaidan1983** [comment]
请问如何修改 --use_gpt4？

**Comment by yihong0618** [comment]
> 请问如何修改 --use_gpt4？

https://github.com/yihong0618/xiaogpt/blob/main/xiaogpt/bot/chatgptapi_bot.py#L17

**Comment by gaidan1983** [comment]
> > 请问如何修改 --use_gpt4？
> 
> https://github.com/yihong0618/xiaogpt/blob/main/xiaogpt/bot/chatgptapi_bot.py#L17

谢谢，已改 gpt-4-1106-preview

**Comment by yihong0618** [comment]
不客气。

**Comment by gaidan1983** [comment]
> Owner

4的费用比之前3.5几天的和还高，几何增加呀。大佬，空了时再看看Bard

**Comment by yihong0618** [comment]
支持了gemini
