### ISSUE TITLE
型号：LX04  提问后总是小爱回答才开始问GPT

### ISSUE THREAD

**Issue by cheungchazz** [yihong0618/xiaogpt#394]
情况如题，配置了mute_xiaoai也不管用，看输出好像是在提问的时候程序没有及时捕获到，有延迟，请问这个应该是在哪里优化？跟网络有关系吗？

**Comment by yihong0618** [comment]
LX04 无法 mute

**Comment by chazzjimel** [comment]
好的谢谢宏大，请问是除了：LX04 和 L05B L05C 就可以mute吗，还有就是我没怎么看代码，这个项目可以云端部署不，还是得和小爱音箱同局域网，感激

**Comment by yihong0618** [comment]
1. 可以云端部署
2. 上README 必须用 use_command 的都不能 mute

**Comment by nanweiqing** [comment]
你好，我的型号也是LX04，为什么在调用最近对话记录，我这边会报这个错，Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8

**Comment by yihong0618** [comment]
> 你好，我的型号也是LX04，为什么在调用最近对话记录，我这边会报这个错，Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8

你先跟他（小爱）聊两句别的并确定 app 能连上

**Comment by nanweiqing** [comment]
谢谢宏大，就是很奇怪，app上都是连着的，对话也没问题，对话记录在app上也能看到，但代码获取时都报这个错<ClientResponse(https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware=L09A&timestamp=1703159053523&limit=2) [401 None]>

**Comment by yihong0618** [comment]
@nanweiqing 你确认下 device_id 是不是一个。。。

**Comment by muzizongheng** [comment]
> @nanweiqing 你确认下 device_id 是不是一个。。。

我是小爱音响pro， lx06， 我发现刚开始gpt控制台有回复但小爱没声音， 改了use command后可以有声音了，但是会出现先小爱回答再“正在问chatgpt，请稍后”

**Comment by yihong0618** [comment]
> > @nanweiqing 你确认下 device_id 是不是一个。。。
> 
> 我是小爱音响pro， lx06， 我发现刚开始gpt控制台有回复但小爱没声音， 改了use command后可以有声音了，但是会出现先小爱回答再“正在问chatgpt，请稍后”

lx06 理论不会用 edge-tts 试试？

**Comment by muzizongheng** [comment]
> > > @nanweiqing 你确认下 device_id 是不是一个。。。
> > 
> > 
> > 我是小爱音响pro， lx06， 我发现刚开始gpt控制台有回复但小爱没声音， 改了use command后可以有声音了，但是会出现先小爱回答再“正在问chatgpt，请稍后”
> 
> lx06 理论不会用 edge-tts 试试？

ok， 谢啦， 晚上回去我试试。
