### ISSUE TITLE
L05B edge-tts 没有声音

### ISSUE THREAD

**Issue by Everestlion** [yihong0618/xiaogpt#398]
{
  "hardware": "L05B",
  "account": "xxx",
  "password": "xxx",
  "openai_key": "xxxxxx",
  "glm_key": "",
  "bard_token": "",
  "serpapi_api_key": "",
  "cookie": "",
  "mi_did": "xxxxx",
  "use_command": true,
  "mute_xiaoai": true,
  "verbose": true,
  "bot": "chatgptapi",
  "tts": "edge",
  "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
  "prompt": "请用100字以内回答",
  "keyword": ["请", "帮我"],
  "change_prompt_keyword": ["更改提示词"],
  "start_conversation": "开始持续对话",
  "end_conversation": "结束持续对话",
  "stream": true,
  "proxy": "xxxxxx",
  "gpt_options": {},
  "bing_cookie_path": "",
  "bing_cookies": {},
  "api_base": "xxxx",
  "deployment_id": ""
}
切换成edge-tts小爱同学不播放声音，后台有输出内容, 启动记录也显示edge-tts服务端也启动了
打印了下日志显示
{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}
求解答，谢谢

**Comment by yihong0618** [comment]
@Everestlion 这个型号只支持小爱原本的 tts

**Comment by Everestlion** [comment]
@yihong0618 好的，谢谢

**Comment by yihong0618** [comment]
不客气，关了哈！
