### ISSUE TITLE
Ubuntu 下运行正常，docker下运行GPT回答：connection error.

### ISSUE THREAD

**Issue by gaidan1983** [yihong0618/xiaogpt#399]
因为有3个不同型号小爱，希望可以docker方式同时给3个小爱赋能。
先是在V2rayA下用tproxy代理方式，docker下运行GPT回答：connection error.
后改为在V2rayA下用rediect代理方式（说明中支持docker），docker run 后提示 api1.mina.mi.com...Login failed，看说明是要拿到cookie，请问在Ubuntu下怎么拿cookie，是配置在本地挂载的config.json里即可吗？另外，为啥本地开着代理直接运行没有触发小米的异地登录安全警告呢。

**Comment by yihong0618** [comment]
不好意思我不太懂 v2ray

**Comment by gaidan1983** [comment]
> 不好意思我不太懂 v2ray

通过网页抓cookie的方法有吗，谢谢

**Comment by yihong0618** [comment]
没有。。

**Comment by yihong0618** [comment]
@我觉得可以支持多个 xiaoai....我想想办法

**Comment by gaidan1983** [comment]
> @我觉得可以支持多个 xiaoai....我想想办法

太棒了，我本想起3个容器哈。

**Comment by yihong0618** [comment]
> > @我觉得可以支持多个 xiaoai....我想想办法
> 
> 太棒了，我本想起3个容器哈。

这个比较难实现，暂时还没精力做，如果做完了我在这里回复
