### ISSUE TITLE
Exception: we have no hardware: xiaomi.wifispeaker please check

### ISSUE THREAD

**Issue by daf3707** [yihong0618/xiaogpt#4]
你好，我设置好了openGPT了，可以 回答了。
 另外micli list 获取了以下信息 
    "name": "小米AI音箱",
    "model": "xiaomi.wifispeaker.s12",
    "did": "151653888"
我摸索出了这些命令：
micli.py 3-1=0   #麦克风禁用，须手动开启
micli.py 5  “内容” 播放声音，不能有空格
micli.py 2=40 设置音量40%
micli.py action '{"did":"设置DID","miid":0,"siid":5,"aiid":5,"in":["天气怎么样", 0]}'  查询询问的内容。
我运行了xiaogpt.py 出现了以下提示。因为我不知道我的小米智能音箱，hardware填 什么 ，它的铭牌上就是一个型号MDZ-25-DA，和一个SN号，是数字型的。
Exception: we have no hardware: xiaomi.wifispeaker.s12 please check 
请大神解答一下，小白不太懂。

**Comment by yihong0618** [comment]
s12 “—hardware s12”

**Comment by yihong0618** [comment]
s 可能需要大写

**Comment by daf3707** [comment]
大小写我都试了，错误一样。

**Comment by yihong0618** [comment]
--hardware S12A

**Comment by yihong0618** [comment]
试试这个

`micli nina` 会打印出来一堆东西，找到你的 hardware 名

**Comment by wutaijieing** [comment]
> 试试这个
> 
> `micli nina` 会打印出来一堆东西，找到你的 hardware 名

 micli nina
[
  "NULL"
]

**Comment by wutaijieing** [comment]
> s 可能需要大写

python3 xiaogpt.py --hardware S12
Traceback (most recent call last):
  File "/home/taijie/Desktop/xiaogpt/xiaogpt.py", line 170, in <module>
    miboy._init_all_data()
  File "/home/taijie/Desktop/xiaogpt/xiaogpt.py", line 68, in _init_all_data
    self._init_first_data_and_chatbot()
  File "/home/taijie/Desktop/xiaogpt/xiaogpt.py", line 88, in _init_first_data_and_chatbot
    self.last_timestamp, self.last_record = self.get_last_timestamp_and_record(data)
  File "/home/taijie/Desktop/xiaogpt/xiaogpt.py", line 102, in get_last_timestamp_and_record
    last_record = records[0]
IndexError: list index out of range
救救

**Comment by yihong0618** [comment]
@wutaijieing  先聊会儿试试？
另外你是不是有两个型号一样的小爱？

**Comment by wutaijieing** [comment]
> @wutaijieing 先和小爱聊会儿试试？ 另外你是不是有两个型号一样的小爱？

是有两个小爱，只不过一个在老家的不在同一个网络下，而且型号也不同，一个是ai一个是遥控版本

**Comment by yihong0618** [comment]
log 理论正常，我晚上更新下让它没 log

**Comment by zlc000190** [comment]
借楼问下   miservice的 export MI_USER=<Username>,
    export MI_PASS=<Password>,   export MI_DID=<Device ID|Name>  这些在哪里配置啊，一头雾水啊啊啊

**Comment by yihong0618** [comment]
你现在直接用 `--account` `--password` 不配置可能也行
