### ISSUE TITLE
'activate' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by devbzwlyukfkz5t** [yihong0618/xiaogpt#400]
Windows平台下的one_click.bat运行出错，百度谷歌了一圈没发现问题的答案，这个activate需要安装什么环境？多谢各位。

**Comment by yihong0618** [comment]
需要建一个虚拟环境，可以搜索 python venv windows

**Comment by frostming** [comment]
one_click.bat 脚本有问题，考虑移除 @yihong0618 ，请按README的说明使用

**Comment by yihong0618** [comment]
好我删一下
