### ISSUE TITLE
ChatGPT 回答出错 Using SOCKS proxy, but the 'socksio' package is not installed

### ISSUE THREAD

**Issue by nanweiqing** [yihong0618/xiaogpt#406]
问题：写一份年终总结？
以下是小爱的回答:  怎么写呢
以下是 ChatGPT 的回答: ChatGPT 回答出错 Using SOCKS proxy, but the 'socksio' package is not installed. 
Make sure to install httpx using `pip install httpx`.

**Comment by yihong0618** [comment]
pip install -U httpx socksio
