### ISSUE TITLE
L05C 小爱音箱 使用ChatGLM API时，mute_xiaoai 快速停掉小爱自己的回答 设置失效

### ISSUE THREAD

**Issue by superwiboy** [yihong0618/xiaogpt#408]
L05C 小爱音箱 使用ChatGLM API时，mute_xiaoai 快速停掉小爱自己的回答 设置失效

**Comment by yihong0618** [comment]
L05C 不能使用这个功能，README 里有写

**Comment by superwiboy** [comment]
bard API是可以正常触发mute_xiaoai，触发时有语音∶我在问bard

**Comment by yihong0618** [comment]
我可能之后会看一下，目前有些事儿不在家（没有小爱测试）
如果你研究明白为什么 PR welcome

**Comment by doddodod** [comment]
我是L05B，mute掉以后小爱不念openai的回答。有人遇到这个问题吗？

**Comment by yihong0618** [comment]
我晚上看看。。。

**Comment by xjblszyy** [comment]
> 我晚上看看。。。

有结果了嘛

**Comment by yihong0618** [comment]
> > 我晚上看看。。。
> 
> 有结果了嘛

你指的是哪个

**Comment by wiboy** [comment]
> > 我晚上看看。。。
> 
> 有结果了嘛

转转换了个音箱😂😂😂
