### ISSUE TITLE
micli list  提示登录 ssl证书有误

### ISSUE THREAD

**Issue by zlc000190** [yihong0618/xiaogpt#41]
Cannot connect to host account.xiaomi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')]

**Comment by yihong0618** [comment]
check your network it should not include `proxy`

**Comment by zlc000190** [comment]
vpn关闭了  还是不行

**Comment by zlc000190** [comment]
代理都关闭也不行，查了很多，说是Charles 关闭。 我都没开Charles  还有代理检查已经 查出没用代理了。还是不行。 证书问题吗？ 这个就不知道怎么弄了

**Comment by pjq** [comment]
本地命令行能打开吗 
```
curl -vv account.xiaomi.com
```

**Comment by pjq** [comment]
这个提示就是MITM， 中间证书被拦截了，  CERTIFICATE_VERIFY_FAILED， 如果Mac的, 看一下设置
<img width="668" alt="image" src="https://user-images.githubusercontent.com/87846/222632199-0f7fa881-7498-40c2-b359-d58c0451f563.png">

**Comment by zlc000190** [comment]
@pjq  好的，非常感谢，mac  我试一下

**Comment by zlc000190** [comment]
这是代理的设置

![image](https://user-images.githubusercontent.com/8969941/222662762-8a15e1fc-3c41-4748-bb80-716489a80e75.png)

**Comment by zlc000190** [comment]
@pjq  是啊，我检查了但是就是一直报这个错

**Comment by joe12801** [comment]
我根你一样，都有这个问题

**Comment by zlc000190** [comment]
我解决了这个，但是ChatGPT那个又有问题

**Comment by greatbody** [comment]
> 我解决了这个，但是ChatGPT那个又有问题

求教如何解决的。

**Comment by zlc000190** [comment]
@greatbody  解决ssl 997错误
您可以尝试安装 certifi 库。
你可以像这样用 pip 安装它。
pip install certifi
安装后你可以使用这个命令
/Applications/Python\ 3.10/install\ Certificates.command
只需将 python 版本更改为您在环境中使用的版本
并尝试再次运行您的程序。

这对我有用。

**Comment by zlc000190** [comment]
@Thxonly 你这种思路解决了吗 运行成功没

**Comment by white586** [comment]
我使用了最新的容器，还是报错登录失败。
对于容器使用，有什么建议吗？

Exception on login xxxxxxxxxxxx: Cannot connect to host account.xiaomi.com:443 ssl:False [Connect call failed ('xxxxxxxxxxx', 443)]
xiaogpt  | Traceback (most recent call last):
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
xiaogpt  |     sock = await aiohappyeyeballs.start_connection(
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
xiaogpt  |     raise first_exception
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection
xiaogpt  |     sock = await _connect_sock(
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 166, in _connect_sock
xiaogpt  |     await loop.sock_connect(sock, address)
xiaogpt  |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
xiaogpt  |     return await fut
xiaogpt  |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
xiaogpt  |     raise OSError(err, f'Connect call failed {address}')
xiaogpt  | ConnectionRefusedError: [Errno 111] Connect call failed ('xxxxxxxxxxxx', 443)
xiaogpt  | 
xiaogpt  | The above exception was the direct cause of the following exception:
xiaogpt  | 
xiaogpt  | Traceback (most recent call last):
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 56, in login
xiaogpt  |     resp = await self._serviceLogin(f"serviceLogin?sid={sid}&_json=true")
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 98, in _serviceLogin
xiaogpt  |     async with self.session.request(
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1359, in __aenter__
xiaogpt  |     self._resp: _RetType = await self._coro
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 663, in _request
xiaogpt  |     conn = await self._connector.connect(
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 563, in connect
xiaogpt  |     proto = await self._create_connection(req, traces, timeout)
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1032, in _create_connection
xiaogpt  |     _, proto = await self._create_direct_connection(req, traces, timeout)
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
xiaogpt  |     raise last_exc
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
xiaogpt  |     transp, proto = await self._wrap_create_connection(
xiaogpt  |   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
xiaogpt  |     raise client_error(req.connection_key, exc) from exc
xiaogpt  | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host account.xiaomi.com:443 ssl:False [Connect call failed ('39.156.81.45', 443)]

**Comment by yihong0618** [comment]
> > fixed run:
> > ```
> > pip3 install -U git+https://github.com/yihong0618/MiService
> > ```
> 
> 这个只是pip安装适用吧 我使用了最新的容器，还是报错登录失败。 对于容器使用，有什么建议吗？
> 
> Exception on login xxxxxxxxxxxx: Cannot connect to host account.xiaomi.com:443 ssl:False [Connect call failed ('xxxxxxxxxxx', 443)] xiaogpt | Traceback (most recent call last): xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection xiaogpt | sock = await aiohappyeyeballs.start_connection( xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection xiaogpt | raise first_exception xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection xiaogpt | sock = await _connect_sock( xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 166, in _connect_sock xiaogpt | await loop.sock_connect(sock, address) xiaogpt | File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect xiaogpt | return await fut xiaogpt | File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb xiaogpt | raise OSError(err, f'Connect call failed {address}') xiaogpt | ConnectionRefusedError: [Errno 111] Connect call failed ('xxxxxxxxxxxx', 443) xiaogpt | xiaogpt | The above exception was the direct cause of the following exception: xiaogpt | xiaogpt | Traceback (most recent call last): xiaogpt | File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 56, in login xiaogpt | resp = await self._serviceLogin(f"serviceLogin?sid={sid}&_json=true") xiaogpt | File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 98, in _serviceLogin xiaogpt | async with self.session.request( xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1359, in aenter xiaogpt | self._resp: _RetType = await self._coro xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 663, in _request xiaogpt | conn = await self._connector.connect( xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 563, in connect xiaogpt | proto = await self._create_connection(req, traces, timeout) xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1032, in _create_connection xiaogpt | _, proto = await self._create_direct_connection(req, traces, timeout) xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection xiaogpt | raise last_exc xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection xiaogpt | transp, proto = await self._wrap_create_connection( xiaogpt | File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection xiaogpt | raise client_error(req.connection_key, exc) from exc xiaogpt | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host account.xiaomi.com:443 ssl:False [Connect call failed ('xxxxxxxxx', 443)]

换个网络试试
