### ISSUE TITLE
可以把gpt相关调用，换成自己服务端的api么

### ISSUE THREAD

**Issue by NeoXu954** [yihong0618/xiaogpt#410]

**Comment by yihong0618** [comment]
可以，改 api base

**Comment by NeoXu954** [comment]
好的 谢谢大佬，再请问下已经将xiao_config.json.example复制为xiao_config.json，并将keyword更换了，为什么运行还是显示之前得Running xiaogpt now, 用帮我/请开头来提问
或用开始持续对话开始持续对话
