### ISSUE TITLE
为什么调用glm的api 并没有显示回复

### ISSUE THREAD

**Issue by NeoXu954** [yihong0618/xiaogpt#415]
<img width="869" alt="issue" src="https://github.com/yihong0618/xiaogpt/assets/75052481/abe0f437-6bbb-458a-bdb8-b2ba288c2b00">

**Comment by yihong0618** [comment]
可能得关掉 proxy

**Comment by NeoXu954** [comment]
好的 谢谢 目前换成lx06了 一切正常

**Comment by yihong0618** [comment]
好的，先关了哈
