### ISSUE TITLE
关于唤醒词和关键词的一些问题

### ISSUE THREAD

**Issue by NeoXu954** [yihong0618/xiaogpt#416]
1.WAKEUP_KEYWORD =""  请问直接在config.py中修改这个是否可以直接替换小爱同学的唤醒？
2.KEY_WORD = ("请")，如何不需要关键词，直接像小爱同学发问？
感谢解答

**Comment by frostming** [comment]
做不到，这个项目本质上是在小爱同学之上做的应用
不能把小爱本身内部机制换掉

**Comment by NeoXu954** [comment]
好的 明白 感谢~
<img width="268" alt="issue2" src="https://github.com/yihong0618/xiaogpt/assets/75052481/a148e569-d284-4d7e-aa9d-1730c23e28ae">
那这个开头可以弄掉么

**Comment by yihong0618** [comment]
哈？弄掉你指的是？

**Comment by NeoXu954** [comment]
就是用***开头来提问，这个***可以为空么

**Comment by yihong0618** [comment]
可以你config 设置成空就行

**Comment by NeoXu954** [comment]
<img width="151" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/75052481/1d91b06d-76ee-482f-b78e-36a65a06baaa">
 我是在config.py这个位置设置的，然后使用这个命令启动python3 xiaogpt.py --hardware LX06  --mute_xiaoai --use_glm --glm_key ，但没有触发项目
<img width="266" alt="image" src="https://github.com/yihong0618/xiaogpt/assets/75052481/1763b4ac-e289-4cd7-82c7-d60decd9b28b">

**Comment by NeoXu954** [comment]
我改了need_ask_gpt，成功了~

**Comment by yihong0618** [comment]
好的我们先关了哈
enjoy it
