### ISSUE TITLE
> LX04 加上 --use_command 也是只打印gpt回答内容，没有语音

### ISSUE THREAD

**Issue by doddodod** [yihong0618/xiaogpt#418]
是把--enable_edge_tts设置为true吗

**Comment by doddodod** [comment]
关于为什么chatgpt部分答案小米无法回答：是因为需要把tts设置为mi。只有mi.py里的synthesize函数是全的，edge和其他tts模式的synthesize函数没有补全。所以只有mi模式小米可以把文字转化为语音念完。

**Comment by yihong0618** [comment]
啊，这块我们接下来改好点，谢谢
