### ISSUE TITLE
LangChainDeprecationWarning: Importing chat models from langchain is deprecated.提示请问如何处理？

### ISSUE THREAD

**Issue by sontjer** [yihong0618/xiaogpt#422]
如何处理以下提示：/usr/local/lib/python3.11/dist-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. I

mporting from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

from langchain_community.chat_models import ChatOpenAI.

To install langchain-community run pip install -U langchain-community.

warnings.warn(

/usr/local/lib/python3.11/dist-packages/langchain/utilities/__init__.py:24: LangChainDeprecationWarning: Importing this utility from langchain is deprecated. Im

porting it from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

from langchain_community.utilities import SerpAPIWrapper.

To install langchain-community run pip install -U langchain-community.

**Comment by yihong0618** [comment]
warning 可以先忽略我们后面更新下版本

**Comment by sontjer** [comment]
谢谢，辛苦了🤟
