### ISSUE TITLE
用config.json启动后，小爱音响可以正常唤醒，并进入gpt问答模式，但是提示 Connection error.

### ISSUE THREAD

**Issue by lbl1120** [yihong0618/xiaogpt#424]
![屏幕截图 2024-01-11 204623](https://github.com/yihong0618/xiaogpt/assets/152936427/bd8e4684-7f68-45e5-8ef8-6fa2d596120c)

**Comment by yihong0618** [comment]
ctrl + c 会弹出错误。
你看看是不是梯子问题。（可以先本地确认下

**Comment by yihong0618** [comment]
理论是梯子问题，欢迎随时 open
