### ISSUE TITLE
能修改唤醒词吗？

### ISSUE THREAD

**Issue by Moonlit7** [yihong0618/xiaogpt#427]
修改了WEAKUP_WORD，但没有生效，readme里的写的有能力可以修改唤醒词，有没有什么修改思路跟方向，我研究研究提个PR

**Comment by yihong0618** [comment]
能啊，生效的啊。。。。

**Comment by frostming** [comment]
不能修改，WAKEUP_KEYWORD 是个常量，不是变量（你看它都没有允许在config.json里面）

**Comment by frostming** [comment]
> 你只的生效是什么效果？修改完新的唤醒词，还是得喊小爱同学才会答应

指的是GPT触发词「请」，这个能改，「小爱同学」唤醒不能改。

**Comment by Moonlit7** [comment]
> > 你只的生效是什么效果？修改完新的唤醒词，还是得喊小爱同学才会答应
> 
> 指的是GPT触发词「请」，这个能改，「小爱同学」唤醒不能改。

了解了
