### ISSUE TITLE
请教一下, 有的型号是不支持吗? (型号S12)

### ISSUE THREAD

**Issue by jglwiz** [yihong0618/xiaogpt#428]
通过命令micli mina无法查询到型号. micli list 中可以看到是 xiaomi.wifispeaker.s12. 请问这个型号是不支持吗? 谢谢各位.

**Comment by yihong0618** [comment]
S12 是支持的
https://github.com/yihong0618/xiaogpt/blob/2258b8825f9fee659eaafbae1e13530c81ddf9cb/xiaogpt/config.py#L19

**Comment by jglwiz** [comment]
> S12 是支持的
> 
> https://github.com/yihong0618/xiaogpt/blob/2258b8825f9fee659eaafbae1e13530c81ddf9cb/xiaogpt/config.py#L19

xiaogpt --config config.josn 报错: 

config:
"hardware":"S12",

Exception: we have no hardware: S12 please use `micli mina` to check.

micli list return: 
  {
    "name": "小米AI音箱",
    "model": "xiaomi.wifispeaker.s12",
    "did": "xxx",
    "token": "xxx"
  },

目前还是运行不了, 是需要在同一个内网吗?

**Comment by yihong0618** [comment]
不需要，你可能得升级一下
pip install -U xiaogpt
或者试试 s12A

**Comment by jglwiz** [comment]
> 不需要，你可能得升级一下 pip install -U xiaogpt 或者试试 s12A

两个方法都测过了. 直接clone 的仓库代码, 运行, 还是不行. 
micli mina是找不到型号的.

**Comment by yihong0618** [comment]
关了哈
