### ISSUE TITLE
docker部署出现:GPT3 回答出错'GPT3Bot' object has no attribute 'config'

### ISSUE THREAD

**Issue by tianxi2023** [yihong0618/xiaogpt#433]
docker容器部署出现这种错误是什么原因，哪位大佬给看看。如果需要映射config文件的话，config.json里面的内容应该怎么配置？麻烦指点一下啊，感谢了。
![image](https://github.com/yihong0618/xiaogpt/assets/122082064/34bae139-2aab-41eb-a03b-2e5ab93f2c6e)

**Comment by LinJia21** [comment]
我git clone的也不行，不知道是不是gpt3 api的问题。以下是 GPT3 的回答: GPT3 回答出错 'GPT3Bot' object has no attribute 'config'。通义千问api就可以。= =

**Comment by yihong0618** [comment]
用 chatgptapi

**Comment by yihong0618** [comment]
其余的我们这周看看

**Comment by LinJia21** [comment]
> 用 chatgptapi

这个可以用，谢谢
