### ISSUE TITLE
在WINDOWS10下使用WSL部署好项目，设备使用LX04，启动后未报错，跟小爱同学说话，终端无显示，无反馈

### ISSUE THREAD

**Issue by kyeo-hub** [yihong0618/xiaogpt#437]
![1706113627117](https://github.com/yihong0618/xiaogpt/assets/44312958/f1b4c2d3-3056-464f-8f83-b3095043a542)
![1706113849913](https://github.com/yihong0618/xiaogpt/assets/44312958/c7ae83c9-6811-4247-b8a4-1cdb153378f8)

**Comment by yihong0618** [comment]
把 verbose 设置成 true看看 log

**Comment by kyeo-hub** [comment]
> 把 verbose 设置成 true看看 log

谢谢，已经看到了，应该是我的网络问题，访问 Gemini 超时了，所以没有回复，中间偶然回复过一次，应该就是没超时的时候。
准备抽时间换千问试试，家里用的群晖，看能不能 docker 部署到群晖上。

**Comment by yihong0618** [comment]
好的，先关了哈

**Comment by kyeo-hub** [comment]
好的，反馈一下，已测试千问，未用特殊网络，反应灵敏。有问有答。
