### ISSUE TITLE
群晖nas的docker运行

### ISSUE THREAD

**Issue by gaidan1983** [yihong0618/xiaogpt#442]
已成功运行在群晖nas的docker里，并通过另一个clash的docker实现科学上网。
运行1-2天后会一直提示以信息。
WARING Execotion when get lastest ask from xiaogpt.py 210
xiaoai:Cannot connect to host\
userprofile.mina.mi.com:443
ssl:default [Temporary failure in name resolution]

此时docker 还在正常运行，但已经没有“正在问GPT”了

另外，大佬是否可考虑在config.json里加一个模型参数。比如我可以设置成一个运行 gpt-3.5-turbo-1106，另一个运行 gpt-4-0125-previw

**Comment by yihong0618** [comment]
@gaidan1983 第一个我会研究下
第二个这几天我加一下。

**Comment by frostming** [comment]
第二个已经支持啊，gpt_options 是一个字典，可以指定所有 OpenAI api 支持的参数

**Comment by yihong0618** [comment]
> 第二个已经支持啊，gpt_options 是一个字典，可以指定所有 OpenAI api 支持的参数

对，我傻了，这个你放上就行

**Comment by gaidan1983** [comment]
> 第二个已经支持啊，gpt_options 是一个字典，可以指定所有 OpenAI api 支持的参数

可否给示例。或者在说明中写个示例，谢谢！

**Comment by frostming** [comment]
> 可否给示例。或者在说明中写个示例，谢谢！

```json
gpt_options = {
    "model": "gpt-3.5-turbo-1106",
}
```

所有 [API 文档](https://platform.openai.com/docs/api-reference/chat) 中支持的参数都可以放里面。

**Comment by yihong0618** [comment]
关了哈
