### ISSUE TITLE
openai的tts突然不读了

### ISSUE THREAD

**Issue by sweetowen** [yihong0618/xiaogpt#444]
选择openai的tts，昨天还好用的，今天突然就只有答案但不读了。
看过mp3已经生成在本地，也可以拿别的播放成功。
语音换edge也不行。不知道是不是ubus有问题？看日志是mina_service.play_by_url出的问题。
只有语音换成mi才能读出来。

**Comment by superwiboy** [comment]
是不是api key到期了

**Comment by sweetowen** [comment]
是说openai吗？不是，答案都生成的，日志里看得到。调用tts也生成了音频文件了。就是调小米播音频不行。
ubus也有api key？这个我不清楚。
用的是小爱ai二代，L15A

**Comment by yihong0618** [comment]
突然不读了可能是 bug....
我们看一下，你重启应该就行了。

**Comment by yihong0618** [comment]
> 突然不读了可能是 bug.... 我们看一下，你重启应该就行了。

@frostming 我也遇到过这个 bug..

**Comment by sweetowen** [comment]
> 突然不读了可能是 bug.... 我们看一下，你重启应该就行了。

找到原因了。我把音箱从一个家带到了另一个家，这样服务器就跨网了，所以没法读到音频文件。昨天忘了这个事。我把音箱带回原来家里，就又好用了。

**Comment by sweetowen** [comment]
那先关闭了，不好意思打扰大家了。

**Comment by yihong0618** [comment]
好的。
