### ISSUE TITLE
chatgpt回答有多段落，多空格的时候，空格会被解析，导致语音停顿过久

### ISSUE THREAD

**Issue by imhut** [yihong0618/xiaogpt#446]
`问题：用专家的口吻介绍一下新冠病毒？
以下是小爱的回答:  问题太有水平了，待我去学习一下
以下是 ChatGPT 的回答: 新冠病毒，正式称为2019年新型冠状病毒疾病（COVID-19），是一种由新型冠状病毒引起的感染疾病。这种新型冠状病毒（SARS-CoV-2）属于冠状病毒家族中的一种，其病毒载体为单链式RNA。此类病毒通常可以从动植物和人类导致疾病。

COVID-19病毒最早在2019年中国武汉市爆发，并迅速传播至世界各地。症状包括咳嗽、感冒、高烧、喘息、咳痰等，严重时可能导致肺炎、呼吸困难、多器官损伤甚至死亡。虽然年轻人和健康人群对COVID-19的危害相对较小，但老年人和具有基础疾病的人群可能面临更高的危险。

为了控制疫情，世界卫生组织（WHO）和各国政府推行了多种措施，如社交距离、佩戴口罩、定期洗手等。研究人员也在全球合作下开发了多种疫苗，以促进人口免疫并减缓病毒传播。`

这是一段示例，第一段读完后，会停顿很久，应该是在解析空格，然后开始第二段，然后没有读完应该有设置超时时间吧，就。。。。建议能否针对chatgpt或者其他AI的答案进行格式的处理，紧凑丢给小爱同学。。。

**Comment by imhut** [comment]
`问题：问武汉在中？
以下是小爱的回答:  问题很有水平，容我先去补补课
以下是 ChatGPT 的回答: 武汉是中国中部的一个大城市，属于湖北省的主要城市之一。武汉位于长江三角洲的东南部，是中国的重要经济、文化、科技和交通中心。这座城市拥有丰富的历史和文化，也是中国现代化发展的一部分。

武汉的地理位置优越，使得它成为了中国内地的重要交通枢纽。武汉有一系列高速公路、铁路和航空交通设施，连接了中国其他主要城市。武汉也是中国科技产业的重点发展区，拥有大量的科研机构和高科技企业。

在文化方面，武汉拥有丰富的历史和传统，有许多著名的景点和文化活动。例如，武汉黄陂湖、东湖和岳麓山等自然景观，以及武汉大学、中央民族大学等著名的高校。武汉还拥有丰富的美食文化，如热门的火锅、拌饭、沙拉等。

总之，武汉是一个充满活力、发展迅速的城市，在经济、科技、文化等方面都发挥着重要作用。`

再一个示例，貌似稍微长一点的回答都是默认这种格式。。。正在发帖，发现这个不一样了，就第一段第二段停留较长时间，后面的2-3-4段衔接很好，基本上没有中间的停顿，奇怪。。。

**Comment by yihong0618** [comment]
如果是支持的型号，可以用 --tts edge 来避免这个问题

**Comment by imhut** [comment]
> 如果是支持的型号，可以用 --tts edge 来避免这个问题

可能是非支持型号，L05C 无法使用edge语音吧。。。。

**Comment by yihong0618** [comment]
对。。。l05C 这个问题暂时没太好的办法。（衔接问题是计算比较困难

**Comment by imhut** [comment]
> 对。。。l05C 这个问题暂时没太好的办法。（衔接问题是计算比较困难

嗯，我发现有的空格没有被解析，暂时找不到其中原因，我到时候试试看打开所有日志或者抓包看看，看是否能给tts mi的时候过滤掉或者想办法正则替换掉吧。。。

**Comment by yihong0618** [comment]
> > 对。。。l05C 这个问题暂时没太好的办法。（衔接问题是计算比较困难
> 
> 嗯，我发现有的空格没有被解析，暂时找不到其中原因，我到时候试试看打开所有日志或者抓包看看，看是否能给tts mi的时候过滤掉或者想办法正则替换掉吧。。。

如果解决了 PR welcome

**Comment by hz109919** [comment]
请问各位大神，是怎么解决小米音响接入GPT后回答问题不联网的，有办法调用插件吗

**Comment by yihong0618** [comment]
> 请问各位大神，是怎么解决小米音响接入GPT后回答问题不联网的，有办法调用插件吗

现在支持的 langchain 是联网的，可以参考 README

**Comment by hz109919** [comment]
> > 请问各位大神，是怎么解决小米音响接入GPT后回答问题不联网的，有办法调用插件吗
> 
> 现在支持的 langchain 是联网的，可以参考 README

大佬，能否再详细点说明，我是小白

**Comment by hz109919** [comment]
> > > 请问各位大神，是怎么解决小米音响接入GPT后回答问题不联网的，有办法调用插件吗
> > 
> > 
> > 现在支持的 langchain 是联网的，可以参考 README
> 
> 大佬，能否再详细点说明，我是小白
![微信图片_20240325191654](https://github.com/yihong0618/xiaogpt/assets/138859400/e9d6db9b-e764-4f3f-ac0a-06338f659dd1)

**Comment by yihong0618** [comment]
> 能否再详细点说明，我是小白

开通你会有个 key, 然后 set 那个 key 和 set 其它 key 一样。。目前这个有困难的话我们未来可能考虑支持其它联网模型，但精力不在这上这段时间，抱歉。

**Comment by hz109919** [comment]
> > 能否再详细点说明，我是小白
> 
> 开通你会有个 key, 然后 set 那个 key 和 set 其它 key 一样。。目前这个有困难的话我们未来可能考虑支持其它联网模型，但精力不在这上这段时间，抱歉。

感谢大佬回复，serpapi我已经设置好key了，但好像并没有生效，因为小爱同学不能联网搜索信息回答，并不够智能哦
