### ISSUE TITLE
使用中转api报错

### ISSUE THREAD

**Issue by Hello-Linux** [yihong0618/xiaogpt#448]
xiaogpt增加运行参数--api_base='https://sapi.onechat.fun' 中转api版本为chatgpt 3.5
然后对小爱音响提问:
```
Running xiaogpt now, 用帮我/请开头来提问
或用开始持续对话开始持续对话
--------------------
问题：问中国足球队如何获得大力神杯？
以下是小爱的回答:  好问题，容我再去补补课
以下是 ChatGPT 的回答: ChatGPT 回答出错 'str' object has no attribute 'choices'
^CTraceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 204, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```
报错 'str' object has no attribute 'choices'

**Comment by yihong0618** [comment]
pip install -U openai

**Comment by Hello-Linux** [comment]
@yihong0618  我试试

**Comment by Hello-Linux** [comment]
@yihong0618 不行还是这个错误，目前版本是openai==1.12.0

**Comment by Hello-Linux** [comment]
docker run -e OPENAI_API_KEY=xxxxxxxxxxxxxxxx yihong0618/xiaogpt --account=xxxxxx --password='xxxxxx' --hardware=LX06 --use_chatgpt_api --mute_xiaoai --api_base='https://sapi.onechat.fun'

**Comment by Hello-Linux** [comment]
中转api从这个地方购买的(https://mvtw4457uos.feishu.cn/docx/HxB6dqzPDozjE8xribScGUtGnBh),我使用chatgpt gui客户端，然后加上中转ip跟key是可以正常使用的

**Comment by Hello-Linux** [comment]
方便的话加下vx，我可以私聊发你我购买的chatgpt的中转接口地址跟key，你本地可以调试试试

**Comment by Hello-Linux** [comment]
这个是chatgpt的gui截图，使用是正常的
<img width="800" alt="test" src="https://github.com/yihong0618/xiaogpt/assets/17851645/b121c41f-1fcf-4eda-94da-583b8d2b2f87">

**Comment by Hello-Linux** [comment]
@yihong0618  目前正常了，为啥需要加v1呢？

**Comment by yihong0618** [comment]
因为本来就有 v1
不能，除非用开启持续回答

**Comment by hlming09** [comment]
> docker run -e OPENAI_API_KEY=xxxxxxxxxxxxxxxx yihong0618/xiaogpt --account=xxxxxx --password='xxxxxx' --hardware=LX06 --use_chatgpt_api --mute_xiaoai --api_base='https://sapi.onechat.fun'

我在用这个后，还是会出现 str has no attribute choices

**Comment by yihong0618** [comment]
https://sapi.onechat.fun/v1

**Comment by hz109919** [comment]
请问各位大神，是怎么解决小米音响接入GPT后回答问题不联网的，有办法调用插件吗

**Comment by liguobao** [comment]
> 请问各位大神，是怎么解决小米音响接入GPT后回答问题不联网的，有办法调用插件吗
不联网只能用本地的LLM，本地LLM启动之后变成一个兼容openai的接口也是可以的。
