### ISSUE TITLE
控制台看到的回答是很长的代码，小爱同学没有说完正在问chatgpt就没有反应了

### ISSUE THREAD

**Issue by hlming09** [yihong0618/xiaogpt#449]
![错误](https://github.com/yihong0618/xiaogpt/assets/96968093/8ff3878b-b318-402d-bf73-159d81f1be12)

**Comment by hlming09** [comment]
问了chatgpt，这个是cloudflare的challenge页面，后来换了api_base，出现了如下报错：
![2](https://github.com/yihong0618/xiaogpt/assets/96968093/26484dc9-cda1-4471-bf09-06496e540e56)

我的电脑是win11的操作系统，不是mac的

**Comment by hlming09** [comment]
后来又试了docker的，也是报错str has no attribute choices

**Comment by yihong0618** [comment]
apikey 后面有个 /v1 请参考 README

**Comment by hlming09** [comment]
[](url)> apikey 后面有个 /v1 请参考 README

感谢大佬回答。
但是我加了v1似乎还是不行：
这是加v1又加引号
![11](https://github.com/yihong0618/xiaogpt/assets/96968093/024fceef-9c29-43ee-81b3-00cf0f5b516b)
这是加v1不加引号：
![22](https://github.com/yihong0618/xiaogpt/assets/96968093/820b2ccd-2ab1-4825-95e0-98ab60f42a6c)

**Comment by yihong0618** [comment]
应该是 proxy 的问题
