### ISSUE TITLE
[bug] 'MiNAService' object has no attribute 'player_get_status'

### ISSUE THREAD

**Issue by keac** [yihong0618/xiaogpt#45]
小爱音响art
python xiaogpt.py --mute_xiaoai --hardware L09A

AttributeError: 'MiNAService' object has no attribute 'player_get_status'

**Comment by yihong0618** [comment]
@keac 安装我 fork 的。
1. pip uninstall miservice
2. pip install -r requirements.txt

**Comment by keac** [comment]
解决了 thanks

**Comment by yihong0618** [comment]
客气了 enjoy it
