### ISSUE TITLE
接入xiaogpt之后，  小爱的播放音频的能力失效

### ISSUE THREAD

**Issue by kingszhe9664** [yihong0618/xiaogpt#452]
提示 无法连接网络。但是chatgpt可以正常使用，

**Comment by kingszhe9664** [comment]
btw   我这边可以同时使用xiaogpt  +xiaomusic 吗？

**Comment by yihong0618** [comment]
> 提示 无法连接网络。但是chatgpt可以正常使用，

需要同一个网络

**Comment by yihong0618** [comment]
> btw 我这边可以同时使用xiaogpt +xiaomusic 吗？

不知道。。。有时间我看看

**Comment by kingszhe9664** [comment]
网络问题自己恢复了，也不知道啥情况

**Comment by yihong0618** [comment]
好，我先关了。。
