### ISSUE TITLE
xiaogpt正常触发并回答问题后会自动播放音乐，而且蓝色灯光常亮不灭(正常呼叫小爱唤醒后的那种灯光)

### ISSUE THREAD

**Issue by ZHAOZ1491** [yihong0618/xiaogpt#458]

**Comment by yihong0618** [comment]
重启。。。

**Comment by yihong0618** [comment]
fix 了请更新

**Comment by hanxi** [comment]
@yihong0618 这个问题是如何修复的呢？

**Comment by yihong0618** [comment]
> @yihong0618 这个问题是如何修复的呢？

重启然后升级到 miservice_fork 最新版

**Comment by yihong0618** [comment]
> @yihong0618 这个问题是如何修复的呢？

root cause 是一个参数，你可以看 commit

**Comment by hanxi** [comment]
> > @yihong0618 这个问题是如何修复的呢？
> 
> root cause 是一个参数，你可以看 commit

是这个吗？ https://github.com/yihong0618/MiService/commit/1291da6d998bba2fc75dc0903d8410f3de2a664e

**Comment by yihong0618** [comment]
> > > @yihong0618 这个问题是如何修复的呢？
> 
> > 
> 
> > root cause 是一个参数，你可以看 commit
> 
> 
> 
> 是这个吗？ https://github.com/yihong0618/MiService/commit/1291da6d998bba2fc75dc0903d8410f3de2a664e

yep
