### ISSUE TITLE
小白问题，win11下无法获取音箱did

### ISSUE THREAD

**Issue by iqking613** [yihong0618/xiaogpt#461]
![微信图片_20240401124150](https://github.com/yihong0618/xiaogpt/assets/45193700/c162e6ab-5a43-459c-9170-4e2b9fffff05)
不会代码，跟着瞎搞，如图，不知道什么原因。

**Comment by yihong0618** [comment]
python -m pip install miservice_fork

**Comment by iqking613** [comment]
> python -m pip install miservice_fork

![1](https://github.com/yihong0618/xiaogpt/assets/45193700/f23977e3-68b6-4981-a99a-1ce8d8612564)
可能是我哪里操作不对，还是提示一样的错误。
我找了太mac，能执行micli list命令了，但是提示
Exception on login 281976853: Cannot connect to host sts.api.io.mi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

**Comment by yihong0618** [comment]
> > python -m pip install miservice_fork
> 
> ![1](https://private-user-images.githubusercontent.com/45193700/318348679-f23977e3-68b6-4981-a99a-1ce8d8612564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTE3MTIsIm5iZiI6MTcxMTk1MTQxMiwicGF0aCI6Ii80NTE5MzcwMC8zMTgzNDg2NzktZjIzOTc3ZTMtNjhiNi00OTgxLWE5OWEtMWNlOGQ4NjEyNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MWRkOWU1ODY4OWI5OWJkNGI1ZjM3ZDhhYjEzNmQzNTgwMDRhYjM4YjQwNDU2MWI5OTk4YzJiMGI5YTFjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YT_3_umCB-PxSIRYihVPjmZ5IjtJb5syiU2JtdWC-w) 可能是我哪里操作不对，还是提示一样的错误。 我找了太mac，能执行micli list命令了，但是提示 Exception on login 281976853: Cannot connect to host sts.api.io.mi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

这个有点麻烦，你在 issue 里搜索 ssl 里面其它人遇到过，解决的方式不同。
