### ISSUE TITLE
有好心人总结下小米音箱什么型号可以兼容使用吗，不想买错了

### ISSUE THREAD

**Issue by SedateC** [yihong0618/xiaogpt#462]
有好心人总结下小米音箱什么型号可以兼容使用吗，不想买错了。

**Comment by yihong0618** [comment]
我的是那个 pro lx06

**Comment by SedateC** [comment]
感谢

**Comment by yihong0618** [comment]
客气了～

**Comment by frostming** [comment]
https://github.com/yihong0618/xiaogpt/blob/5ed01bd3a6890b9d0f99de5a64aca57dc3d1e19e/xiaogpt/config.py#L15-L34
