### ISSUE TITLE
下载xiaogpt出现问题ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Duuckjing** [yihong0618/xiaogpt#463]
这是完整的错误日志，在Windows上也会出现

error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [241 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Collecting setuptools
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/92/e1/1c8bb3420105e70bdf357d57dd5567202b4ef8d27f810e98bb962d950834/setuptools-69.2.0-py3-none-any.whl (821 kB)
      Collecting wheel
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl (65 kB)
      Collecting oldest-supported-numpy
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/dc/5c/e3c84cfdd488701aa074b22cf5bd227fb15d26e1d55a66d9088c39afa123/oldest_supported_numpy-2023.12.21-py3-none-any.whl (4.9 kB)
      Collecting numpy==1.23.2 (from oldest-supported-numpy)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f4/66/17b8e95770478436bf968353c89683ce6f9e14d92e0d4fb3111c09ba18d2/numpy-1.23.2.tar.gz (10.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [212 lines of output]
            setup.py:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
              warnings.warn(
            Running from numpy source directory.
            setup.py:86: DeprecationWarning:

              `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
              of the deprecation of `distutils` itself. It will be removed for
              Python >= 3.12. For older Python versions it will remain present.
              It is recommended to use `setuptools < 60.0` for those Python versions.
              For more details, see:
                https://numpy.org/devdocs/reference/distutils_status_migration.html

              import numpy.distutils.command.sdist
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_common.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/mtrand.pyx
            Cythonizing sources
            INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data
            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data
            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data/com.termux/files/usr/tmp/tmpiou1j_nx
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/data/data/com.termux/files/usr/tmp/tmpiou1j_nx/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmpiou1j_nx/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:
            INFO: lapack_armpl_info:
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_lapack_info:
            INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data
            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data
            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data/com.termux/files/usr/tmp/tmptgielauf
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmptgielauf/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmptgielauf/data/data/com.termux/files/usr/tmp/tmptgielauf/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmptgielauf/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            Warning: attempted relative import with no known parent package
            /data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            INFO: build_src
            INFO: building py_modules sources
            creating build
            creating build/src.linux-aarch64-3.11
            creating build/src.linux-aarch64-3.11/numpy
            creating build/src.linux-aarch64-3.11/numpy/distutils
            INFO: building library "npymath" sources
            WARN: Could not locate executable armflang
            WARN: Could not locate executable gfortran
            WARN: Could not locate executable f95
            WARN: Could not locate executable ifort
            WARN: Could not locate executable ifc
            WARN: Could not locate executable lf95
            WARN: Could not locate executable pgfortran
            WARN: Could not locate executable nvfortran
            WARN: Could not locate executable f90
            WARN: Could not locate executable f77
            WARN: Could not locate executable fort
            WARN: Could not locate executable efort
            WARN: Could not locate executable efc
            WARN: Could not locate executable g77
            WARN: Could not locate executable g95
            WARN: Could not locate executable pathf95
            WARN: Could not locate executable nagfor
            WARN: Could not locate executable frt
            WARN: don't know how to compile Fortran code on platform 'posix'
            creating build/src.linux-aarch64-3.11/numpy/core
            creating build/src.linux-aarch64-3.11/numpy/core/src
            creating build/src.linux-aarch64-3.11/numpy/core/src/npymath
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h
            INFO:   adding 'build/src.linux-aarch64-3.11/numpy/core/src/npymath' to include_dirs.
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/ieee754.c
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c
            INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h']
            INFO: building library "npyrandom" sources
            INFO: building extension "numpy.core._multiarray_tests" sources
            creating build/src.linux-aarch64-3.11/numpy/core/src/multiarray
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/multiarray/_multiarray_tests.c
            INFO: building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
                self).run_setup(setup_script=setup_script)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 493, in <module>
                setup_package()
              File "setup.py", line 485, in setup_package
                setup(**metadata)
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/distutils/command/build.py", line 62, in run
                old_build.run(self)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-7ou1geud/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/distutils/command/build_src.py", line 161, in build_sources
                self.build_extension_sources(ext)
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
                sources = self.generate_sources(sources, ext)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/core/setup.py", line 513, in generate_config_h
                check_math_capabilities(config_cmd, ext, moredefs, mathlibs)
              File "/data/data/com.termux/files/usr/tmp/pip-install-sgduklf1/numpy_3faa7a80818a45b993aa97cbb84e24a9/numpy/core/setup.py", line 176, in check_math_capabilities
                raise SystemError("One of the required function to build numpy is not"
            SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yihong0618** [comment]
pip install numpy 试试？

**Comment by Duuckjing** [comment]
> pip install numpy 试试？

numpy有的，还是会有pyproject.toml的问题
最近装了个jupyter notebook里面有很多pyproject.toml, building wheel 倒是都成功了

后来移动端装了个Debian环境，直接安装好了，部分安装过程：

Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB) Building wheels for collected packages: google-search-results                                               Building wheel for google-search-results (setup.py) ... done                                              Created wheel for google-search-results: filename=google_search_results-2.4.2-py3-none-any.whl size=32003 sha256=78b93dc041f368400520576304006e66cba7e9fb88ceb1fa2cb3c2e3f037db11                                   Stored in directory: /root/.cache/pip/wheels/68/8e/73/744b7d9d7ac618849d93081a20e1c0deccd2aef90901c9f5a9Successfully built google-search-results             Installing collected packages: typing-extensions, pyasn1, urllib3, sniffio, rsa, pydantic-core, pyasn1-modules, protobuf, idna, h11, exceptiongroup, charset-normalizer, certifi, cachetools, annotated-types, requests, pydantic, proto-plus, packaging, orjson, mypy-extensions, multidict, jsonpointer, hyperframe, httpcore, hpack, grpcio, googleapis-common-protos, google-auth, frozenlist, anyio, yarl, typing-inspect, tenacity, PyYAML, pycryptodomex, mdurl, marshmallow, lz4, langsmith, jsonpatch, jeepney, httpx, h2, grpcio-status, greenlet, google-api-core, attrs, async-timeout, aiosignal, wcwidth, SQLAlchemy, regex, pygments, numpy, markdown-it-py, loguru, langchain-core, dataclasses-json, browser-cookie3, aiohttp, websockets, tqdm, soupsieve, rich, python-gemini-api, pyjwt, prompt-toolkit, mutagen, langchain-text-splitters, langchain-community, google-ai-generativelanguage, distro, colorama, BingImageCreator, zhipuai, openai, numexpr, miservice-fork, langchain, google-search-results, google-generativeai, EdgeGPT, edge-tts, dashscope, beautifulsoup4, bardapi, xiaogpt                                     Attempting uninstall: urllib3                          Found existing installation: urllib3 1.26.5          Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr                      Can't uninstall 'urllib3'. No files were found to uninstall.                                            Attempting uninstall: numpy                            Found existing installation: numpy 1.26.4            Uninstalling numpy-1.26.4:                             Successfully uninstalled numpy-1.26.4          Successfully installed BingImageCreator-0.5.0 EdgeGPT-0.1.26 PyYAML-6.0.1 SQLAlchemy-2.0.29 aiohttp-3.9.3 aiosignal-1.3.1 annotated-types-0.6.0 anyio-4.3.0 async-timeout-4.0.3 attrs-23.2.0 bardapi-1.0.0 beautifulsoup4-4.12.3 browser-cookie3-0.19.1 cachetools-5.3.3 certifi-2024.2.2 charset-normalizer-3.3.2 colorama-0.4.6 dashscope-1.10.0 dataclasses-json-0.6.4 distro-1.9.0 edge-tts-6.1.10 exceptiongroup-1.2.0 frozenlist-1.4.1 google-ai-generativelanguage-0.4.0 google-api-core-2.18.0 google-auth-2.29.0 google-generativeai-0.4.1 google-search-results-2.4.2 googleapis-common-protos-1.63.0 greenlet-3.0.3 grpcio-1.62.1 grpcio-status-1.62.1 h11-0.14.0 h2-4.1.0 hpack-4.0.0 httpcore-1.0.5 httpx-0.27.0 hyperframe-6.0.1 idna-3.6 jeepney-0.8.0 jsonpatch-1.33 jsonpointer-2.4 langchain-0.1.14 langchain-community-0.0.31 langchain-core-0.1.39 langchain-text-splitters-0.0.1 langsmith-0.1.38 loguru-0.7.2 lz4-4.3.3 markdown-it-py-3.0.0 marshmallow-3.21.1 mdurl-0.1.2 miservice-fork-2.4.1 multidict-6.0.5 mutagen-1.47.0 mypy-extensions-1.0.0 numexpr-2.10.0 numpy-1.26.4 openai-1.16.1 orjson-3.10.0 packaging-23.2 prompt-toolkit-3.0.43 proto-plus-1.23.0 protobuf-4.25.3 pyasn1-0.6.0 pyasn1-modules-0.4.0 pycryptodomex-3.20.0 pydantic-2.6.4 pydantic-core-2.16.3 pygments-2.17.2 pyjwt-2.8.0 python-gemini-api-2.4.1 regex-2023.12.25 requests-2.31.0 rich-13.7.1 rsa-4.9 sniffio-1.3.1 soupsieve-2.5 tenacity-8.2.3 tqdm-4.66.2 typing-extensions-4.10.0 typing-inspect-0.9.0 urllib3-2.2.1 wcwidth-0.2.13 websockets-12.0 xiaogpt-2.26 yarl-1.9.4 zhipuai-2.0.1

**Comment by Duuckjing** [comment]
后来用`LDFLAGS="-lppython3.11" pip install numpy --no-build-isolation --no-cache-dir`解决了numpy依赖
