### ISSUE TITLE
小米账号登录不了

### ISSUE THREAD

**Issue by Enchner** [yihong0618/xiaogpt#464]
Exception on login 861066059: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "C:\Artificial_Intelligence\xiaogpt\venv\lib\site-packages\miservice\miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Error https://api.io.mi.com/app/home/device_list: Login failed

**Comment by Enchner** [comment]
是本机使用，连到同一个路由器上的。用谷歌浏览器登陆过小米云了

**Comment by yihong0618** [comment]
https://github.com/yihong0618/xiaogpt/issues/469

**Comment by firstuanl** [comment]
> cloud.mi.com

您的小米账号没有在生态云系统（北京 - 金山云）注册，请联系小米生态云团队

这样是不是没得搞了，

**Comment by justin0127** [comment]
> > cloud.mi.com
> 
> 您的小米账号没有在生态云系统（北京 - 金山云）注册，请联系小米生态云团队
> 
> 这样是不是没得搞了，

我也一样是这个问题，有大佬知道怎么办吗？

**Comment by isKEKE** [comment]
同样遇到这个问题
