### ISSUE TITLE
md文件造成新手困扰。可能是登录失败的源头之一。

### ISSUE THREAD

**Issue by Chigogo** [yihong0618/xiaogpt#467]
```
pip install miservice_fork
set MI_USER=xxxx
set MI_PASS=xxx
micli list 得到did
set MI_DID=xxxx
```

md文件是新用户学习项目的首要阅读材料，本md文件不应采用 ```set...```的写法，set命令是设置bash 配置的命令，此处，md 的写法容易被新手误认为是命令行命令。

建议写法：
```
# 1、安装模块
pip install miservice_fork

# 2、设置环境用户参数
export MI_USER=xxxx
export MI_PASS=xxx

# 3、使用micli list 得到did
micli list

# 4、根据did设置环境DID参数
export MI_DID=xxxx
```

**Comment by yihong0618** [comment]
上面写着 windows 用户用 set 呀。。。

**Comment by Chigogo** [comment]
@yihong0618 抱歉，在你fork 的miservice 的原项目中，[md处指示：可能不支持Windows](https://github.com/Yonsm/MiService?tab=readme-ov-file#%E5%A5%97%E8%B7%AF%E4%BE%8B%E5%AD%90) ，然后我在参看你的md 文档的时候，忽略了Windows的指示。（使用Windows Subsystem for Linux）

不知道其他人会不会犯这种错误。如果作者觉得必要的话，也可以改成如下：

### Windows
```cmd
pip install miservice_fork
set MI_USER=xxxx
set MI_PASS=xxx
micli list 得到did
set MI_DID=xxxx
```

### Linux
```bash
# 1、安装模块
pip install miservice_fork

# 2、设置环境用户参数
export MI_USER=xxxx
export MI_PASS=xxx

# 3、使用micli list 得到did
micli list

# 4、根据did设置环境DID参数
export MI_DID=xxxx
```

**Comment by yihong0618** [comment]
> @yihong0618 抱歉，在你fork 的miservice 的原项目中，[md处指示：可能不支持Windows](https://github.com/Yonsm/MiService?tab=readme-ov-file#%E5%A5%97%E8%B7%AF%E4%BE%8B%E5%AD%90) ，然后我在参看你的md 文档的时候，忽略了Windows的指示。（使用Windows Subsystem for Linux）
> 
> 不知道其他人会不会犯这种错误。如果作者觉得必要的话，也可以改成如下：
> 
> ### Windows
> ```batchfile
> pip install miservice_fork
> set MI_USER=xxxx
> set MI_PASS=xxx
> micli list 得到did
> set MI_DID=xxxx
> ```
> 
> ### Linux
> ```shell
> # 1、安装模块
> pip install miservice_fork
> 
> # 2、设置环境用户参数
> export MI_USER=xxxx
> export MI_PASS=xxx
> 
> # 3、使用micli list 得到did
> micli list
> 
> # 4、根据did设置环境DID参数
> export MI_DID=xxxx
> ```

可以。但感觉 readme 可以调整下
你有兴趣把这个改动提个 pr 么？
miservice 那边我去改下支持 windows

**Comment by Chigogo** [comment]
我提交一个pull request，然后你通过就行了是吧？我没有试过，我试试吧。

**Comment by yihong0618** [comment]
> 我提交一个pull request，然后你通过就行了是吧？我没有试过，我试试吧。

谢谢
