### ISSUE TITLE
 我的一直提示error code 401  incorrect api key provider  chatgpt的api都生成了好几个，还是不行，有遇到这种情况的吗 ？

### ISSUE THREAD

**Issue by ghksuper** [yihong0618/xiaogpt#473]
![b6407aa4962ee302f4c8ced4762aa3a7](https://github.com/yihong0618/xiaogpt/assets/153808136/f96a1bf0-5ff8-482a-af25-af56c362c619)

**Comment by yihong0618** [comment]
确保你的key正确如果是第三方的需要指定 api base

**Comment by ghksuper** [comment]
是openai生成的，是否需要指定api source?

**Comment by yihong0618** [comment]
@ghksuper 报错是你的key不对。。

**Comment by liguobao** [comment]
> 是openai生成的，是否需要指定api base?

感觉你是不是买了中转key之类的...

**Comment by Tigores** [comment]
python3 xiaogpt.py --hardware LX06  --mute_xiaoai --use_glm --glm_key ${glm_key}
以上面的命令为例，把${glm_key}换成你的key而不是glm_key换成你的key
试一试，我犯了这个低级的错误
如python3 xiaogpt.py --hardware LX06  --mute_xiaoai --use_glm --glm_key 123456
