### ISSUE TITLE
能添加适配Skylark-chat大模型吗？该模型是跟进豆包

### ISSUE THREAD

**Issue by kidxiang** [yihong0618/xiaogpt#481]
希望大佬能添加适配Skylark-chat，具体的API调用说明如下
https://www.volcengine.com/docs/82379/1133387

最近把大佬提供的几个模型都试了一遍，个人感觉对于中文来说，还是豆包最厉害，希望大佬能适配，谢谢。

**Comment by yihong0618** [comment]
#480 is working on it...
豆包这么火呀。

**Comment by sundy-li** [comment]
Skylark-chat 我打算下个版本支持。

我其实很希望 豆包训练的语音 能在火山引擎中调用。

问了下， 火山引擎那边说是这个活不关他们事，而是豆包那边的， 豆包那边又说是火山那边的问题

**Comment by yihong0618** [comment]
Done

**Comment by frostming** [comment]
This is different from TTS, reopen
