### ISSUE TITLE
可以连接微软的azure AI模型吗？

### ISSUE THREAD

**Issue by Saintoliver** [yihong0618/xiaogpt#482]
全局梯子我用的不太好，可能梯子不太稳定。

所以用docker连了通义千问，通义千问回答老是被儿子挑刺，的确物理知识回答的都比较错误。所以还是想接入一些优秀的大模型，azure国内访问好像不要梯子，大佬会在今后加上Azure AI API Key吗？

**Comment by yihong0618** [comment]
现在就可以啊。。。README 里有

**Comment by Saintoliver** [comment]
> 现在就可以啊。。。README 里有

感谢回答，我仔细看看
