### ISSUE TITLE
使用Gemini模型一直不成功

### ISSUE THREAD

**Issue by flyfish321** [yihong0618/xiaogpt#483]
前2天买了一个小米音箱PRO，刚好一直有关注yihong大哥的这个项目，电脑小白，用的Windows电脑，最近连续研究了2个晚上，上网搜了很多教程，总算看到一点胜利曙光了。目前通义千问模型学会使用了，chatgpt因为免费额度过期了，也不想再费时间研究了，就想用Gemini模型，开了全局代理，浏览器网页也可以正常打开Gemini网页版，但是项目测试起来就一直报错，不知道什么原因，如图所示。

另外，xiao_config.json配置文件里有2个不明白的地方，麻烦yihong大哥帮忙解答下，谢啦。

1.proxy选项是必填的，还是根据情况填就行？
2."api_base": "https://generativelanguage.googleapis.com/v1", 最后的【/v1】是需要删掉的吗？

![1](https://github.com/yihong0618/xiaogpt/assets/119868298/a47e79d3-420b-45c0-9eca-4c9829173d7a)

![2](https://github.com/yihong0618/xiaogpt/assets/119868298/999e180d-3b7f-4928-adb1-120eded05d8f)

**Comment by yihong0618** [comment]
对。最后的 api base 删掉试试

**Comment by flyfish321** [comment]
删掉还是不行，报错和不删一样

**Comment by yihong0618** [comment]
我今天确定下

**Comment by flyfish321** [comment]
嘿嘿，这么快就回复了，辛苦yihong哥

**Comment by flyfish321** [comment]
哈哈，不着急，有空的时候看下就行，能用通义千问也很好了

**Comment by yihong0618** [comment]
我这里没问题，可能是你全局代理的问题，请确保你的 terminal 能访问 gemini

curl google.com

**Comment by flyfish321** [comment]
果然还是全局代理的问题，刚已经解决了，太感谢了

**Comment by iazrael** [comment]
搭一个不需要梯子的代理吧 #485

**Comment by flyfish321** [comment]
感谢感谢，找时间研究一下
