### ISSUE TITLE
tts_options	参数能否给个样例

### ISSUE THREAD

**Issue by superwiboy** [yihong0618/xiaogpt#489]
配置了几次都不成功

**Comment by superwiboy** [comment]
"tts_options:":{volc[access_key:"",secret_key:"",app_key:""]},这样设吗？

**Comment by superwiboy** [comment]
后面要收费，算了。。。

**Comment by yihong0618** [comment]
> 后面要收费，算了。。。

edge_tts 是免费的

**Comment by frostming** [comment]
后面会把配置文件改成 yaml，可以包含注释
