### ISSUE TITLE
不明白怎么操作，能不能详细说说

### ISSUE THREAD

**Issue by xgd561** [yihong0618/xiaogpt#49]
2. 参考 [MiService](https://github.com/Yonsm/MiService) 项目 README 并在本地 terminal 跑 `micli list` 拿到你音响的 DID 成功 **别忘了设置 export MI_DID=xxx** 这个 MI_DID 用 
3. 参考 [revChatGPT](https://github.com/acheong08/ChatGPT) 项目 README 配置 chatGPT 的 config

这两步，不知道怎么操作？怎么拿音响的 DID， MI_DID用来做什么？能不能详细说说

**Comment by edchina1980** [comment]
调通MiService，然后micli list就可以获得一大堆列表。找到你的音箱的DID

**Comment by yihong0618** [comment]
参考 README 里的视频教程
