### ISSUE TITLE
在windows power shell下 管理员模式安装 L50C 或者S12A 2台中的一台都不行

### ISSUE THREAD

**Issue by zxhans** [yihong0618/xiaogpt#491]
执行到这个命令的时候，报错：
 xiaogpt --hardware L50C --mute_xiaoai --stream

File "c:\program files\python\lib\site-packages\bardapi\core.py", line 12, in <module>
    from gemini.src.model.parser.response_parser import ResponseParser
ModuleNotFoundError: No module named 'gemini.src'

**Comment by yihong0618** [comment]
pip uninstall bardapi

**Comment by zxhans** [comment]
这个组件不能删除 
![image](https://github.com/yihong0618/xiaogpt/assets/52526052/1f2b46fb-5fd3-47d6-a75c-5d3eda92c7e1)

**Comment by yihong0618** [comment]
用最新的xiaogpt bard 已经去掉了

**Comment by zxhans** [comment]
好的，谢谢了

**Comment by zxhans** [comment]
主要是python需要升级到3.10以上版本就可以了。
