### ISSUE TITLE
使用mi tss 经常提示内含敏感信息，换用edge tss 没有声音

### ISSUE THREAD

**Issue by flyfish321** [yihong0618/xiaogpt#492]
确实很好玩的一个项目，但是遇到一点小问题，我用的Windows电脑，使用Gemini 数据模型：

1.使用mi tss 声音，问完问题，Gemini正常显示答案后，小米音箱经常提示内含敏感信息，然后就无法播报显示的内容，其实问题也都很正常啊（像请介绍一下新西兰？类似这样的问题都不行，但是同样的问题，Gemini回答的如果是英文内容，就不会被拦截，可以正常播报，中文就经常被拦截，感觉这点体验很差）

2.使用edge tss声音，基本上就无法正常播报，输入命令后，会多一行提示信息：INFO     Serving on 10.211.1.103:8072       base.py:140    
在浏览器打开这个地址，有时是生成完好的Gemini回答内容的音频文件，有时是生成失败的音频文件（内容完全听不懂）

有什么办法可以解决这个问题吗？
盼大佬指点一下，感谢

使用edge tss 问题图片如下：                  

![a](https://github.com/yihong0618/xiaogpt/assets/119868298/1b26f365-7507-47d8-b691-56ab686a0b1a)

![b](https://github.com/yihong0618/xiaogpt/assets/119868298/cacedaf3-1ca3-4816-bfc9-efaf0b0c937e)

![c](https://github.com/yihong0618/xiaogpt/assets/119868298/6c307d1e-4450-40bf-94df-e60e6aea2d06)

**Comment by yihong0618** [comment]
不太知道，我们看看

**Comment by frostming** [comment]
TTS 没声音和音频文件乱码通常是自动选择的音色不支持指定的语言，遇到这种情况可以换音色试试

**Comment by flyfish321** [comment]
收到收到，感谢大佬。
