### ISSUE TITLE
docker运行，会创建非常多的container？ 但是只有一个是running状态。 是正常的吗？ 其他的containers可以删除不？感觉非常乱，和其他docker服务不一样

### ISSUE THREAD

**Issue by dota2heqiuzhi** [yihong0618/xiaogpt#495]
![image](https://github.com/yihong0618/xiaogpt/assets/36252196/84ce44cf-f2ec-448a-8e88-14bdb712dfa8)

**Comment by frostming** [comment]
退出的 container 可以删除。docker 容器退出后默认都会保留，不明白你说的和其他docker服务不一样是什么情况。如果需要用完自动删除， 需要在 docker run 命令后加上 `--rm` 选项

**Comment by dota2heqiuzhi** [comment]
> 退出的 container 可以删除。docker 容器退出后默认都会保留，不明白你说的和其他docker服务不一样是什么情况。如果需要用完自动删除， 需要在 docker run 命令后加上 `--rm` 选项

谢谢。 可能是我对docker的理解不够。  因为之前跑其他服务，最后都只剩一个。
