### ISSUE TITLE
代码有错

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#51]
![image](https://user-images.githubusercontent.com/70465495/222781800-82a3c7c9-469a-48ac-9393-8de8d3b3769f.png)

**Comment by jtc1246** [comment]
获取MI_DID不能用requirements.txt中的miservice。
pip3 uninstall miservice
pip3 install miservice
但是获取到MI_DID之后，运行时必须使用requirements.txt里的miservice。
pip3 uninstall miservice
pip3 install -r requirements.txt

**Comment by yihong0618** [comment]
@jtc1246 我晚上改下

**Comment by yihong0618** [comment]
其实现在用后面不在，可以不获取 mi_did 我感觉
