### ISSUE TITLE
[2.80容器版本报错]：AttributeError: 'MiNAService' object has no attribute 'player_stop'. Did you mean: 'player_play'?

### ISSUE THREAD

**Issue by DenneyTang** [yihong0618/xiaogpt#511]
这个报错怎么解决：

stderr: Traceback (most recent call last):
stderr:   File "/app/xiaogpt.py", line 5, in <module>
stderr:     main()
stderr:   File "/app/xiaogpt/cli.py", line 233, in main
stderr:     loop.run_until_complete(main(config))
stderr:   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
stderr:     return future.result()
stderr:   File "/app/xiaogpt/cli.py", line 228, in main
stderr:     await miboy.run_forever()
stderr:   File "/app/xiaogpt/xiaogpt.py", line 399, in run_forever
stderr:     await self.stop_if_xiaoai_is_playing()
stderr:   File "/app/xiaogpt/xiaogpt.py", line 336, in stop_if_xiaoai_is_playing
stderr:     await self.mina_service.player_stop(self.device_id)
stderr: AttributeError: 'MiNAService' object has no attribute 'player_stop'. Did you mean: 'player_play'?
stderr: Task exception was never retrieved
stderr: future: <Task finished name='Task-7' coro=<MiGPT.poll_latest_ask() done, defined at /app/xiaogpt/xiaogpt.py:58> exception=AttributeError("'MiNAService' object has no attribute 'player_stop'")>
stderr: Traceback (most recent call last):
stderr:   File "/app/xiaogpt/xiaogpt.py", line 76, in poll_latest_ask
stderr:     await self.stop_if_xiaoai_is_playing()
stderr:   File "/app/xiaogpt/xiaogpt.py", line 336, in stop_if_xiaoai_is_playing
stderr:     await self.mina_service.player_stop(self.device_id)
stderr: AttributeError: 'MiNAService' object has no attribute 'player_stop'. Did you mean: 'player_play'?

**Comment by yihong0618** [comment]
卧槽我忘更新容器的 requirements 了。下午到家我更新下

**Comment by VectorZhao** [comment]
更新之后确实报这个错误。。。。。。。

**Comment by yihong0618** [comment]
@all

更新了，升级 2.81 试试。

**Comment by yihong0618** [comment]
@VectorZhao @DenneyTang 现在好了么？

**Comment by VectorZhao** [comment]
> @VectorZhao @DenneyTang 现在好了么？

好了
