### ISSUE TITLE
只朗读一句

### ISSUE THREAD

**Issue by VectorZhao** [yihong0618/xiaogpt#514]
问:
来一首五言绝句
回答时：一句过后就会停止，再次唤醒后再朗读一句，再唤醒，再朗读一句。。。。

这个bug。。。

**Comment by yihong0618** [comment]
用的什么 tts 以及什么 bot?

**Comment by VectorZhao** [comment]
azure，gpt

自从上次更新完，今天测试发现的

**Comment by VectorZhao** [comment]
你那里没问题？

**Comment by yihong0618** [comment]
修复了，一会儿请更新到最新的代码
