### ISSUE TITLE
部署在docker中后报错

### ISSUE THREAD

**Issue by 2000PJL** [yihong0618/xiaogpt#524]
这些是错误信息，有大佬能帮忙解答一下吗？这是缺少配置文件吗？
stderr:     main()
stderr:   File "/app/xiaogpt/cli.py", line 223, in main
stderr:     config = Config.from_options(options)
stderr:   File "/app/xiaogpt/config.py", line 120, in from_options
stderr:     config = cls.read_from_file(options.config)
stderr:   File "/app/xiaogpt/config.py", line 138, in read_from_file
stderr:     config = json.load(f)
stderr:   File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
stderr:     return loads(fp.read(),
stderr:   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
stderr:     return _default_decoder.decode(s)
stderr:   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
stderr:   File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
stderr:     obj, end = self.scan_once(s, idx)
stderr: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 3 (char 27)

**Comment by yihong0618** [comment]
json 的格式不对。

**Comment by 2000PJL** [comment]
Hi Developer.
好的，非常感谢你的解答。但是我还有一些疑问：
1、由于其他model比较贵，我想要指定model，请问这样配置参数可以吗？"gpt_options": {"model":"qwen-long"}。
2、由于我是部署在软路由上，这个软路由是完全开放在公网上的，有点担心账号密码泄露，所以想使用cookie的方式登录，请问这个cookie如何去获取呀？mina.mi.com这个链接貌似没法调用登录接口，好像没法获取cookie
3、我发现部署在远程的软路由上的docker中 比部署在本地PC上 貌似要慢一些，部署在软路由器的docker中后很容易出现小爱抢答的情况，请问这是因为软路由算力不足吗？还是因为软路由距离我的小爱音箱太远呀？
以上，谢谢

**Comment by yihong0618** [comment]
1. 可以
2. 不会泄漏
3. 盒距离无关，网络问题 docker 会慢一些
