### ISSUE TITLE
 Model gpt-4o-2024-05-13 这个是什么意思？

### ISSUE THREAD

**Issue by binghan2000** [yihong0618/xiaogpt#532]
以下是 ChatGPT 的回答: Error code: 503 - {'error': {'err_code': -10008, 'message': 'No Channels 
Available For Model gpt-4o-2024-05-13 Under The Current Group Default.', 'type':
'api_error'}}
ChatGPT 回答出错

**Comment by yihong0618** [comment]
模型名，你这个应该是用的第三方吧？
没这个模型

**Comment by binghan2000** [comment]
我用了自己的key，也是这样的，怎么指定什么模型？
