### ISSUE TITLE
指定chatgpt的model名出错

### ISSUE THREAD

**Issue by siknet** [yihong0618/xiaogpt#536]
本身是火山方舟模型通过simple-one-api转换成的openAI格式的API，别的地方可以正常使用。
xiao_config.yaml里面写了2个参数：
model: "ep-20240628082110-t92g4"
OPENAI_MODEL: "ep-20240628082110-t92g4"
都没用，提示
问题：鲁迅要打周树人怎么办？
以下是小爱的回答:  问题很有水平，容我先去补补课
以下是 ChatGPT 的回答: Error code: 400 - {'error': 'model gpt-4o-2024-05-13 not found in the configuration'}
看起来是没有指定模型调用了默认的GPT-4O

**Comment by siknet** [comment]
搞定了，手动修改了bot\chatgptapi_bot.py文件里面的模型名字

**Comment by frostming** [comment]
https://github.com/yihong0618/xiaogpt/blob/011637e32a0ed39233e414884a7e6734e789853d/xiao_config.yaml.example#L40-L41
