### ISSUE TITLE
作者考虑config加个model版本参数，让自己填写model版本？比如GLM-4-Flash 已经了0.0001 元 / 千tokens

### ISSUE THREAD

**Issue by JianGangLi** [yihong0618/xiaogpt#543]

**Comment by yihong0618** [comment]
可以，有兴趣来个 PR 么？

**Comment by kingwu8** [comment]
现在flash是免费的了，准备说就看到了，加油添加进去，那就很无敌了

**Comment by frostming** [comment]
一直都可以啊：
https://github.com/yihong0618/xiaogpt/blob/011637e32a0ed39233e414884a7e6734e789853d/xiao_config.yaml.example#L39-L41

**Comment by kingwu8** [comment]
# 传给 Chatbot completion 接口的参数，比如要使用自定义模型：
gpt_options:
  model: glm-4-flash
gpt_options: {}

我这样好像不太行，是哪里有问题的吗

**Comment by frostming** [comment]
把下面那行删了啊

**Comment by kingwu8** [comment]
删了也不行，我还改了glm_bot的model，也不行，直接使用api选的model就没问题，不知道哪里要调整

**Comment by frostming** [comment]
嗯，存在问题导致option不生效 #547
