### ISSUE TITLE
小爱音箱语音回答，命令行没有反应

### ISSUE THREAD

**Issue by Lxhnnn** [yihong0618/xiaogpt#545]
(lxhndh) lh@SRVV2:/data/lxh/xiaogpt-main$ python xiaogpt.py --hardware 23948/C4QT52981 --mute_xiaoai --stream  --use_chatgpt_api
Running xiaogpt now, 用帮我/请开头来提问
或用开始持续对话开始持续对话

和小爱同学对话，上面没任何反应！！！

**Comment by Lxhnnn** [comment]
能帮我解答一下吗

**Comment by yihong0618** [comment]
你得用请开头

**Comment by Lxhnnn** [comment]
我问：小爱同学请你吃饭
命令行还是没反应。

**Comment by yihong0618** [comment]
小爱同学请你吃饭, 这个是 小字开头

要用请字开头，你也可以自己设置开头的词

**Comment by Lxhnnn** [comment]
我先要说 小爱同学  才能唤醒

**Comment by yihong0618** [comment]
唤醒之后用请字开头问

**Comment by Lxhnnn** [comment]
没反应额，我用"小爱同学"唤醒之后，无论问 "帮我打扫卫生", "请你吃饭"，命令行都没反应额

**Comment by scsfwgy** [comment]
我这也是这个问题。mac都测试成功了，部署到debain上先叫：小爱同学，然后：请xxx，日志没任何反应。
