### ISSUE TITLE
请问可以增加对MiniMax AI大模型的支持吗？

### ISSUE THREAD

**Issue by dludream** [yihong0618/xiaogpt#550]
# ===== 对话 AI 设置 =====
# 使用的 bot 类型，目前支持 chatgptapi, glm, gemini, langchain, qwen, doubao, moonshot, yi, llama,
bot: chatgptapi

官网的调用参考如下：
from openai import OpenAI

client = OpenAI(
    api_key="",  # <--在这里使用MiniMax账户管理-接口密钥中API KEY进行接入
    base_url="https://api.minimax.chat/v1",
)

completion = client.chat.completions.create(
  model="abab6.5s-chat",
  messages=[
    {"role": "system", "content": "MM智能助理是一款由MiniMax自研的，没有调用其他产品的接口的大型语言模型。MiniMax是一家中国科技公司，一直致力于进行大模型相关的研究。"},
    {"role": "user", "content": "你好"}
  ]
)

print(completion)
print("Trace-ID:", completion.id)

**Comment by yihong0618** [comment]
你可以直接用啊，更高 api_key 和 api_base 用 chatgpt bot 方式就行
