### ISSUE TITLE
llama是不是崩了？

### ISSUE THREAD

**Issue by superwiboy** [yihong0618/xiaogpt#551]
前两天还好用的

**Comment by yihong0618** [comment]
看看是不是网不通或者额度不够了

**Comment by superwiboy** [comment]
this page came up and the Cloudflare Ray ID found at the bottom of this 
2024/10/02 20:58:28	stdout	owner to let them know you were blocked. Please include what you were doing when
2024/10/02 20:58:28	stdout	            <p data-translate="blocked_resolve_detail">You can email the site 
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	resolve this?</h2>
2024/10/02 20:58:28	stdout	            <h2 data-translate="blocked_resolve_headline">What can I do to 
2024/10/02 20:58:28	stdout	          <div class="cf-column">
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	          </div>
2024/10/02 20:58:28	stdout	or malformed data.</p>
2024/10/02 20:58:28	stdout	trigger this block including submitting a certain word or phrase, a SQL command 
2024/10/02 20:58:28	stdout	performed triggered the security solution. There are several actions that could 
2024/10/02 20:58:28	stdout	security service to protect itself from online attacks. The action you just 
2024/10/02 20:58:28	stdout	            <p data-translate="blocked_why_detail">This website is using a 
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	blocked?</h2>
2024/10/02 20:58:28	stdout	            <h2 data-translate="blocked_why_headline">Why have I been 
2024/10/02 20:58:28	stdout	          <div class="cf-column">
2024/10/02 20:58:28	stdout	        <div class="cf-columns two">
2024/10/02 20:58:28	stdout	      <div class="cf-section cf-wrapper">
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	      </div>
2024/10/02 20:58:28	stdout	        </div>
2024/10/02 20:58:28	stdout	          </div>
2024/10/02 20:58:28	stdout	            
2024/10/02 20:58:28	stdout	              <span class="cf-no-screenshot error"></span>
2024/10/02 20:58:28	stdout	            
2024/10/02 20:58:28	stdout	          <div class="cf-screenshot-container cf-screenshot-full">
2024/10/02 20:58:28	stdout	        <div class="cf-wrapper">
2024/10/02 20:58:28	stdout	      <div class="cf-section cf-highlight">
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	      </div>
2024/10/02 20:58:28	stdout	are unable to access</span> groq.com</h2>
2024/10/02 20:58:28	stdout	        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You 
2024/10/02 20:58:28	stdout	        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
2024/10/02 20:58:28	stdout	      <div class="cf-wrapper cf-header cf-error-overview">
2024/10/02 20:58:28	stdout	    <div id="cf-error-details" class="cf-error-details-wrapper">
2024/10/02 20:58:28	stdout	data-translate="enable_cookies">Please enable cookies.</div>
2024/10/02 20:58:28	stdout	    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" 
2024/10/02 20:58:28	stdout	  <div id="cf-wrapper">
2024/10/02 20:58:28	stdout	<body>
2024/10/02 20:58:28	stdout	</head>
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	</script>
2024/10/02 20:58:28	stdout	  }
2024/10/02 20:58:28	stdout	    })
2024/10/02 20:58:28	stdout	      cookieEl.style.display = 'block';
2024/10/02 20:58:28	stdout	      var cookieEl = document.getElementById('cookie-alert');
2024/10/02 20:58:28	stdout	    window.addEventListener('DOMContentLoaded', function () {
2024/10/02 20:58:28	stdout	  if (!navigator.cookieEnabled) {
2024/10/02 20:58:28	stdout	<script>
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	<style>body{margin:0;padding:0}</style>
2024/10/02 20:58:28	stdout	href="/cdn-cgi/styles/cf.errors.ie.css" /><link rel="stylesheet" id='cf_styles-ie-css' 
2024/10/02 20:58:28	stdout	/>
2024/10/02 20:58:28	stdout	<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" 
2024/10/02 20:58:28	stdout	<meta name="viewport" content="width=device-width,initial-scale=1" />
2024/10/02 20:58:28	stdout	<meta name="robots" content="noindex, nofollow" />
2024/10/02 20:58:28	stdout	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
2024/10/02 20:58:28	stdout	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
2024/10/02 20:58:28	stdout	<meta charset="UTF-8" />
2024/10/02 20:58:28	stdout	<title>Attention Required! | Cloudflare</title>
2024/10/02 20:58:28	stdout	<head>
2024/10/02 20:58:28	stdout	 <html class="no-js" lang="en-US"> 
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	
2024/10/02 20:58:28	stdout	以下是 llama 的回答: <!DOCTYPE html>

**Comment by superwiboy** [comment]
Cloudflare？
