### ISSUE TITLE
如何调用Ollama的模型

### ISSUE THREAD

**Issue by github0hello** [yihong0618/xiaogpt#553]
我在Ollama安装一个Qwen, 调用后
问题：你好？
以下是小爱的回答:  你好呀，我看看是谁在和我打招呼~
以下是 Qian Wen 的回答: Request id: 328317b0-a54f-9b07-9887-836a8bc1065c, Status code: 401, error code: InvalidApiKey, error message: Invalid
API-key provided.
Will pop the wrong question 你好，以下请用300字以内回答，请只回答文字不要带链接
回答完毕
继续对话, 或用`结束持续对话`结束对话

**Comment by mykun123** [comment]
可以继续使用openai的框架，把文档中下面两个参数这样设置，openai_key选"ollama"，api_base填写你本地生成的监听地址和端口，后面/v1
openai_key: "ollama"
api_base: "http://192.168.31.96:1234/v1"

**Comment by github0hello** [comment]
可以， 谢谢

**Comment by rty813** [comment]
> 可以继续使用openai的框架，把文档中下面两个参数这样设置，openai_key选"ollama"，api_base填写你本地生成的监听地址和端口，后面/v1 openai_key: "ollama" api_base: "http://192.168.31.96:1234/v1"

@mykun123 这样如何选用ollama中的模型？
