### ISSUE TITLE
启动就直接退出了

### ISSUE THREAD

**Issue by nibaijing** [yihong0618/xiaogpt#63]
Windows环境，按照视频全部配置完成，执行python3 xiaogpt.py --config xiao_config.json，什么都没有发生，直接退出了。

**Comment by yihong0618** [comment]
确保本地有 python3 

输入 python3 试试进入 repl 不

windows 可能是 python

**Comment by nibaijing** [comment]
用python解决了。谢谢

**Comment by nibaijing** [comment]
用python

**Comment by brryaa** [comment]
昨天碰到同样问题。后来费老大劲在路由器部署了。
