### ISSUE TITLE
micli.py在window下如何用的呢

### ISSUE THREAD

**Issue by laihongzhu** [yihong0618/xiaogpt#64]
PS F:\xiaochat\m\miservice> .\micli.py
MiService 2.0.1 - XiaoMi Cloud Service

Usage: The following variables must be set:
           set MI_USER=<Username>
           set MI_PASS=<Password>
           set MI_DID=<Device ID|Name>

Get Props: F:\xiaochat\m\miservice\micli.py <siid[-piid]>[,...]
           F:\xiaochat\m\miservice\micli.py 1,1-2,1-3,1-4,2-1,2-2,3
Set Props: F:\xiaochat\m\miservice\micli.py <siid[-piid]=[#]value>[,...]
           F:\xiaochat\m\miservice\micli.py 2=#60,2-2=#false,3=test
Do Action: F:\xiaochat\m\miservice\micli.py <siid[-piid]> <arg1|#NA> [...]
           F:\xiaochat\m\miservice\micli.py 2 #NA
           F:\xiaochat\m\miservice\micli.py 5 Hello
           F:\xiaochat\m\miservice\micli.py 5-4 Hello #1

Call MIoT: F:\xiaochat\m\miservice\micli.py <cmd=prop/get|/prop/set|action> <params>
           F:\xiaochat\m\miservice\micli.py action '{"did":"267090026","siid":5,"aiid":1,"in":["Hello"]}'

Call MiIO: F:\xiaochat\m\miservice\micli.py /<uri> <data>
           F:\xiaochat\m\miservice\micli.py /home/device_list '{"getVirtualModel":false,"getHuamiDevices":1}'

Devs List: F:\xiaochat\m\miservice\micli.py list [name=full|name_keyword] [getVirtualModel=false|true] [getHuamiDevices=0|1]
           F:\xiaochat\m\miservice\micli.py list Light true 0

MIoT Spec: F:\xiaochat\m\miservice\micli.py spec [model_keyword|type_urn] [format=text|python|json]
           F:\xiaochat\m\miservice\micli.py spec
           F:\xiaochat\m\miservice\micli.py spec speaker
           F:\xiaochat\m\miservice\micli.py spec xiaomi.wifispeaker.lx04
           F:\xiaochat\m\miservice\micli.py spec urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx04:1

MIoT Decode: F:\xiaochat\m\miservice\micli.py decode <ssecurity> <nonce> <data> [gzip]

PS F:\xiaochat\m\miservice> .\micli.py list
Exception on login None: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "F:\xiaochat\m\miservice\miservice\miaccount.py", line 65, in login
    'hash': hashlib.md5(self.password.encode()).hexdigest().upper()
AttributeError: 'NoneType' object has no attribute 'encode'
Error https://api.io.mi.com/app/home/device_list: Login failed
PS F:\xiaochat\m\miservice>

**Comment by yihong0618** [comment]
不用 micli 直接使用步骤 11 试试？

**Comment by like3ong** [comment]
![image](https://user-images.githubusercontent.com/62214064/223433521-31cd0320-b8d7-475f-9f9f-d9aef8534ff3.png)

直接运行这个脚本，用vscode或者其他IDE软件打开就行
