### ISSUE TITLE
小爱同学没有播放GPT的回答

### ISSUE THREAD

**Issue by nibaijing** [yihong0618/xiaogpt#65]
Running xiaogpt now, 用`帮我`开头来提问
以下是小爱的回答:  答案是二
以下是GPT的回答: 
，，一加一等于二。这是基本的数学运算，即简单的加法。在十进制中，一加一的结果是两个单位。这是最简单的算术运算之一，几乎每个人都可以轻松地回答这个问题。此外，在计算机编程中，运算符“+”被用于执行加法运算，一加一
的结果也是二。

小爱音箱没有播放GPT的回答，这是什么原因?

**Comment by yihong0618** [comment]
先根据 micli 确保 tts 可用。/

**Comment by pjq** [comment]
这个问题我之前也遇到过，后面好像自己就好了。

**Comment by wsjq5477** [comment]
> Running xiaogpt now, 用`帮我`开头来提问 以下是小爱的回答: 答案是二 以下是GPT的回答: ，，一加一等于二。这是基本的数学运算，即简单的加法。在十进制中，一加一的结果是两个单位。这是最简单的算术运算之一，几乎每个人都可以轻松地回答这个问题。此外，在计算机编程中，运算符“+”被用于执行加法运算，一加一 的结果也是二。
> 
> 小爱音箱没有播放GPT的回答，这是什么原因?

刚遇到这个问题，在@yihong0618的帮助下解决了
1、试下小爱能不能正常播报
micli 5 test
micli 5-4 查询天气 
2、增加下--use_command试试呢

**Comment by yihong0618** [comment]
@nibaijing 参考 70
