### ISSUE TITLE
gpt在终端中正常显示，但是小爱音响无法播放gpt的回复

### ISSUE THREAD

**Issue by wsjq5477** [yihong0618/xiaogpt#70]
python3 xiaogpt.py --hardware LX04 --use_chatgpt_api --mute_xiaoai

![image](https://user-images.githubusercontent.com/34412208/222940571-cd4f9b8a-b23a-4185-a41f-1c116e77d46c.png)

**Comment by yihong0618** [comment]
“—use_command” 试试

**Comment by wsjq5477** [comment]
硬件是触屏音响，LX04，好像还是不行，日志如下。
python3 xiaogpt.py --hardware LX04 --use_chatgpt_api --mute_xiaoai --use_command
Running xiaogpt now, 用`帮我`开头来提问
以下是小爱的回答:  答案是二千五百
以下是GPT的回答:
，，五十乘五十等于两千五百。这是因为，我们可以将五十表示为50，那么50乘50就是50×50=2500，再将该数字中的两个0去掉，就得到最终答案2500去掉两个0
50，再除以10就得到两千五百。

**Comment by yihong0618** [comment]
试试 micli call tts 可以么
看到 issue 里确实说触屏音响，LX04 不行，你搜下

**Comment by wsjq5477** [comment]
直接micli是没问题的，试了播报和执行文本都可以
micli 5 test
0
micli 5-4 查询天气 \#1
0

**Comment by yihong0618** [comment]
cool 5-1 test 呢？

**Comment by yihong0618** [comment]
micli 5-1 查询哈哈哈哈

**Comment by wsjq5477** [comment]
micli 5-1 查询哈哈哈哈
0
micli 5-1 test
0

**Comment by yihong0618** [comment]
--mute_xiaoai  这句去掉试试

**Comment by wsjq5477** [comment]
> --mute_xiaoai 这句去掉试试

还是只播报小爱的答案不播报gpt的答案，我加了句日志应该也走到了gpt的条件里
python3 xiaogpt.py --use_chatgpt_api --hardware LX04
Running xiaogpt now, 用`帮我`开头来提问
find key_word success
以下是小爱的回答:  答案是二
以下是GPT的回答:
，，一加一等于二，这是最基本的数学概念和规则。它表示将一个物品或数字与另一个相同的物品或数字结合时
，总数将增加一个单位。无论是否涉及到具体的数字或数量，一加一的结果始终相等。这个简单的问题和答案在
日常生活和各种数学应用程序中都有重要的作用，如计算、测量、估算和解决问题。

**Comment by yihong0618** [comment]
@wsjq5477 好嘞，我来研究下。

**Comment by yihong0618** [comment]
@wsjq5477 
这样
你进入 python repl 
python3 

```
import subprocess
subprocess.check_output(["micli", "5-1", "查询哈哈哈哈"])
```

试试有声音没

**Comment by yihong0618** [comment]
我这边刚测没问题。

**Comment by wsjq5477** [comment]
我在do_tts里加了日志发现根本没有调用到这个函数
await self.do_tts("正在问GPT请耐心等待")
await self.do_tts(message)
删除 await之后能调用到了，但是会有报错
![image](https://user-images.githubusercontent.com/34412208/222950343-943883d2-7375-44a2-bc45-33770ebc8189.png)

**Comment by wsjq5477** [comment]
有声音的

![image](https://user-images.githubusercontent.com/34412208/222950390-4c1c763e-9306-4c5b-8009-d55365ce4899.png)

**Comment by yihong0618** [comment]
python3 xiaogpt.py --use_chatgpt_api --hardware LX04 --use_command

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/222950449-60b72391-ed4c-4210-b441-4c542522d5ae.png)
你这块没加  --use_command

**Comment by wsjq5477** [comment]
> --use_command

感谢，加了use_command解决了。
之前不知道为啥加了没起作用，可能哪里写错了~

**Comment by yihong0618** [comment]
有几个 lx04 的 issue 也可以解决了

**Comment by slwl** [comment]
> 

和你一样的，你解决了吗

**Comment by yihong0618** [comment]
上面写着解决了呀/

**Comment by fengwch** [comment]
micli call tts 是没有声音

Error /home/rpc/529747306: {'code': 0, 'error': {'code': -9999, 'message': 'user ack timeout'}, 'exe_time': 0, 'id': 401245, 'message': 'ok', 'net_cost': 0, 'ot_cost': 0, 'otlocalts': 1679940106523176}
这个什么问题
