### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by LonePheasantWarrior** [yihong0618/xiaogpt#71]
执行`python3 xiaogpt.py --hardware L07A --use_chatgpt_api --mute_xiaoai`后发生错误:

Traceback (most recent call last):
  File "/usr/local/share/chatGPT/xiaogpt/xiaogpt.py", line 12, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by yihong0618** [comment]
pip install openai

**Comment by LonePheasantWarrior** [comment]
> pip install openai

谢谢,问题解决了
