### ISSUE TITLE
使用--mute_xiaoai 无法禁止小爱本身的回答。并且chatgpt的回答只会打印在控制台无法语音播报

### ISSUE THREAD

**Issue by 1500256797** [yihong0618/xiaogpt#73]
我的型号：
L05C

**Comment by yihong0618** [comment]
这个型号可能无法 mute-xiaomi

试试 --use_command

**Comment by pjq** [comment]
@1500256797 
"只会打印在控制台无法语音播报"
可以参考我这个改动，你试一下
<img width="729" alt="image" src="https://user-images.githubusercontent.com/87846/222968666-dd98b7a9-fac3-4387-bd3d-703cf8761ced.png">

- https://github.com/pjq/ChatGPT-MiSpeaker/commit/9001b8b256fed09f0cf1652727541bf9769e1abb

**Comment by pjq** [comment]
@1500256797  命令行可以播放吗
micli 5-1 "Hello"

**Comment by 1500256797** [comment]
我的设备型号是L05C 使用 micli 5-3 可以播放声音

**Comment by 1500256797** [comment]
2023-03-06 00:19:13 Running xiaogpt now, 用`帮我`开头来提问
2023-03-06 00:19:31 以下是小爱的回答:  我帮你做饭
2023-03-06 00:19:33 以下是GPT的回答: ，，好的，我来！

 我的参数是这样的。 gpt的回复能在控制台打印，但是无法播放
    "cookie": "",
    "use_command": true,
    "mute_xiaoai": false,
    "verbose": false,
    "use_gpt3": false,
    "use_chatgpt_api": true

**Comment by imherro** [comment]
我的设备也是L50C, 也是无法静音小爱，也无法播放GPT的声音。你们解决了吗？
python xiaogpt.py --hardware L05C --use_chatgpt_api --mute_xiaoai
Running xiaogpt now, 用`帮我`开头来提问
以下是小爱的回答:  七点起床
以下是GPT的回答:
，，抱歉，作为一名AI语言模型，....。感谢您的提问！

**Comment by 1500256797** [comment]
我曾经有一次 L05C能播放 之后就再也不行了 之后就只能播放小爱官网的回答

**Comment by imherro** [comment]
如果能播一次，应该就有办法。sleep_time=len(message)，回头试试把这个时间弄长点。

**Comment by 1500256797** [comment]
这个原理好像是，调用官方的api，把chatgpt返回的结果发给官方服务器，在由官方服务器发给你的音箱设备。  

昨晚看了下小爱音箱app的对话功能，发现里面由chatgpt回复的结果。不过只出现了一条，之后就一直是官方的回复了。

有没有一种办法，用hook的方式来让小爱音箱念东西。

**Comment by wuwu20048** [comment]
一样的问题，有人解决了吗

**Comment by coressss** [comment]
同样的问题

**Comment by lmlotwtoo** [comment]
同样的问题，请问有人解决了吗？

**Comment by yihong0618** [comment]
参考这个 https://github.com/yihong0618/MiService README 确定 tts 好用

有的型号需要加上 --use_command

**Comment by 412498569** [comment]
LX04    加上 --use_command 也是只打印gpt回答内容，没有语音

**Comment by qq87234770** [comment]
python3 xiaogpt.py --use_chatgpt_api --use_command --mute_xiaoai 也无效，依旧只是小爱回答，gpt打印，小爱音箱10尝试

**Comment by yihong0618** [comment]
@qq87234770 参考https://github.com/yihong0618/MiService README 确定 tts 可用

**Comment by qq87234770** [comment]
已解决。
小米音箱10的hardware为X10A，按照https://zhuanlan.zhihu.com/p/616720165操作找到我的播放文本内容为7-3，在miservice中
python3 micli.py 7-3 123123
可执行，但查看config.py没有对于X10A的相关，可以自己手动按照里面添加一个。之后可运行。

**Comment by yihong0618** [comment]
我之后加上，谢谢分享

**Comment by 412498569** [comment]
> LX04 加上 --use_command 也是只打印gpt回答内容，没有语音

解决了，去掉 --enable_edge_tts就可以正常播放了，我的是这样

**Comment by TyTheLoser** [comment]
L05B 能用micli 5-3 "hello"发声，但是xiaogpt --hardware 5-3 --use_command --mute_xiaoai --use_gpt3
Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
之后再唤醒并且说开始持续对话后没有任何反应

**Comment by Phillweston** [comment]
> 已解决。 小米音箱10的hardware为X10A，按照[https://zhuanlan.zhihu.com/p/616720165操作找到我的播放文本内容为7-3，在miservice中](https://zhuanlan.zhihu.com/p/616720165%E6%93%8D%E4%BD%9C%E6%89%BE%E5%88%B0%E6%88%91%E7%9A%84%E6%92%AD%E6%94%BE%E6%96%87%E6%9C%AC%E5%86%85%E5%AE%B9%E4%B8%BA7-3%EF%BC%8C%E5%9C%A8miservice%E4%B8%AD) python3 micli.py 7-3 123123 可执行，但查看config.py没有对于X10A的相关，可以自己手动按照里面添加一个。之后可运行。

X10A型号没有在config.py中添加支持，我这边添加了列表并且merge进main branch了。有需要的话你们更新一下源码就行

**Comment by yihong0618** [comment]
谢谢～

**Comment by bestcomy-duplicate** [comment]
我的设备S12A，总是要先播放小爱的回答然后播放chatGPT的回答，无法mute小爱的回答
