### ISSUE TITLE
更改chatgpt的apiBaseUrl参数实现国内访问不被墙

### ISSUE THREAD

**Issue by pengmaochang** [yihong0618/xiaogpt#74]
从3/3晚8点开始，GPT3.5的API被墙，导致国内各种项目都使用不了。但是更改chatgpt的API参数，可以避免被墙。具体如下：
apiBaseUrl: 'https://openapi.ssiic.com',

**Comment by yihong0618** [comment]
谢谢，稍后实现。我在 https://github.com/yihong0618/bilingual_book_maker/pull/44 昨天做完了。/
