### ISSUE TITLE
Redmi小爱触屏音箱Pro 8英寸 无法播放声音

### ISSUE THREAD

**Issue by LonglegsP** [yihong0618/xiaogpt#76]
Redmi小爱触屏音箱Pro 8英寸，代号X08E。
7-3可以发出声音
![image](https://user-images.githubusercontent.com/38206253/223050182-8a8b3c9a-a472-4659-97cd-182fec224d43.png)

在xiaogpt.py里添加了型号和字典，还是无法输出声音。
![image](https://user-images.githubusercontent.com/38206253/223050424-9f8d025d-5e56-4e43-a843-a6a382ff0354.png)

希望哪位大佬能帮忙看看
![image](https://user-images.githubusercontent.com/38206253/223050550-598d9f11-ae78-494c-bc33-0b65a9062eba.png)

**Comment by 1500256797** [comment]
一样的，你遇到的这个问题，我昨天就遇到了，卡了一天没解决。

**Comment by yihong0618** [comment]
试试#70

**Comment by LonglegsP** [comment]
> 试试#70

大佬我用输入 micli 7-3 哈哈哈 测试 弹出一堆提示，是不是哪个地方没配置正确，正常情况是不是应该直接能播放声音。
![image](https://user-images.githubusercontent.com/38206253/223061322-625334b5-9992-4e63-acb1-5389478edec4.png)

**Comment by yihong0618** [comment]
@LonglegsP 你先看看 spec 可能不是  7-3

**Comment by LonglegsP** [comment]
> @LonglegsP 你先看看 spec 可能不是 7-3

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rwn

Play_Control = 3
    Playing_State = 1  # uint8  # rn
    _Seek_Time = 2  # int16
    Play_Loop_Mode = 3  # uint8  # rwn

    _Seek = 1
    _Play = 2
    _Pause = 3
    _Stop = 4
    _Previous = 5
    _Next = 6

Microphone = 4
    Mute = 1  # bool  # rwn

Clock = 6
    Switch_Status = 1  # bool  # rwn
    Status = 2  # uint8  # rn
    Device_Fault = 3  # uint8  # rn
    Ringtone = 4  # uint8  # rwn

    _Stop_Alarm = 1

Intelligent_Speaker = 7
    _Text_Content = 1
    _Silent_Execution = 2  # bool
    Sleep_Mode = 3  # bool  # rwn
    Audio_Id = 4  # rn

    _Wake_Up = 1
    _Play_Radio = 2
    _Play_Text = 3  # in=[1]
    _Execute_Text_Directive = 4  # in=[1, 2]

tv-switch = 8

    _tv = 1  # -switchon

no-disturb = 9
    no = 1  # -disturb  # bool  # rwn
    enable = 2  # -time-period  # rnw

Speaker_Volume
    MIN = 0
    MAX = 100

Play_Control_Playing_State
    Playing = 1
    Stop = 0
    Pause = 2

Play_Control_Seek_Time
    MIN = -30000
    MAX = 30000
    STEP = 10

Play_Control_Play_Loop_Mode
    Single_Cycle = 1

Clock_Status
    Idle = 1
    Busy = 2

Clock_Device_Fault
    No_Faults = 0

Clock_Ringtone
    MIN = 1
    MAX = 5

**Comment by LonglegsP** [comment]
用windows又试了一下，还是不行，好像是micli调用问题，实在是不会了。没加 --use_command 没有声音，加了--use_command 就报错。求大佬指点指点..
![image](https://user-images.githubusercontent.com/38206253/223232377-cccfc9a9-7dc2-4c8e-afe5-ca078e1e586d.png)

**Comment by yihong0618** [comment]
我之后想办法看看 windows....
你试试 micli list 有东西没

**Comment by LonglegsP** [comment]
> 我之后想办法看看 windows.... 你试试 micli list 有东西没

- 没有东西 windows 好像无法调用这个

- ![image](https://user-images.githubusercontent.com/38206253/223353129-0c65efbf-f39a-4442-9fa8-0076a1062305.png)

今天用 Ubuntu 虚拟机测试成功了，不折腾了。。

测试出来我的_Redmi小爱触屏音箱Pro 8英寸_对应的值是：

`"X08E":"7-3"`

感谢大佬耐心回复

**Comment by gygy** [comment]
> Redmi小爱触屏音箱Pro 8英寸，代号X08E。
> 7-3可以发出声音
> ![image](https://user-images.githubusercontent.com/38206253/223050182-8a8b3c9a-a472-4659-97cd-182fec224d43.png)
> 
> 在xiaogpt.py里添加了型号和字典，还是无法输出声音。
> ![image](https://user-images.githubusercontent.com/38206253/223050424-9f8d025d-5e56-4e43-a843-a6a382ff0354.png)
> 
> 希望哪位大佬能帮忙看看
> ![image](https://user-images.githubusercontent.com/38206253/223050550-598d9f11-ae78-494c-bc33-0b65a9062eba.png)
> 
> 

触摸屏版本会将回答显示在屏幕上面吗？

**Comment by yihong0618** [comment]
使用 —use_command

**Comment by yihong0618** [comment]
@gygy 不能，不能显示在屏幕上。
