### ISSUE TITLE
L05B设备，无法mute

### ISSUE THREAD

**Issue by slwl** [yihong0618/xiaogpt#77]
控制台能正常显示，使用命令python3 xiaogpt.py --hardware L05B --use_chatgpt_api --mute_xiaoai
只有小爱自己的回答进行播报，无法播报gpt的内容

**Comment by yihong0618** [comment]
Readme 我一会儿加一下谢谢

**Comment by slwl** [comment]
> Readme 我一会儿加一下谢谢

好的，等你

**Comment by yihong0618** [comment]
你得加上 `--use_command` README 加上了谢谢。

**Comment by slwl** [comment]
> python3 xiaogpt.py --hardware L05B --use_chatgpt_api --mute_xiaoai

python3 xiaogpt.py --hardware L05B --use_chatgpt_api --mute_xiaoai --use_command 
还是
python3 xiaogpt.py --hardware L05B --use_chatgpt_api --use_command

**Comment by yihong0618** [comment]
python3 xiaogpt.py --hardware L05B --use_chatgpt_api --use_command

**Comment by slwl** [comment]
root@debian:~/xiaogpt/xiaogpt# python3 xiaogpt.py --hardware L05B --use_chatgpt_api --use_command
Running xiaogpt now, 用`帮我`开头来提问
以下是小爱的回答:  您的设备还不支持打电话的功能哦
以下是GPT的回答: ，，非常抱歉，本人是AI语言模型，没有办法回答此问题。需要更具体的问题或任务来进行回答。

还是回答的小爱的。GPT的没有说

**Comment by yihong0618** [comment]
确保你能用 
micli tts
参考 #70

**Comment by slwl** [comment]
micli 5-3 哈哈哈，正常使用
oot@debian:~/xiaogpt/MiService# micli 5-3 哈哈哈
0

**Comment by 1500256797** [comment]
解决了吗？

**Comment by yihong0618** [comment]
应该就是无法 mute 的

**Comment by cmhello88** [comment]
我也是L05B的设备，也是遇到了无法mute_xiaoai
