### ISSUE TITLE
未配置代理，处理失败，可以忽略证书效验吗？

### ISSUE THREAD

**Issue by coder-user** [yihong0618/xiaogpt#81]
Cannot connect to host account.xiaomi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')]

**Comment by coder-user** [comment]
@yihong0618

**Comment by yihong0618** [comment]
我找时间看看，我感觉是代理的问题

**Comment by coder-user** [comment]
> 我找时间看看，我感觉是代理的问题

基于 docker 正常使用，可以先不着急处理，谢谢作者

**Comment by yolain** [comment]
在几个请求的地方加上 ssl=False 就可以绕过

**Comment by yihong0618** [comment]
我们今天加一下

**Comment by greatbody** [comment]
同样的问题。

**Comment by joe12801** [comment]
在哪里加SSL=FALSE

**Comment by yihong0618** [comment]
@all 我晚上加个命令试试

**Comment by blueteen** [comment]
请问这个问题解决了吗

**Comment by yihong0618** [comment]
fixed
run:
```console
pip3 install -U git+https://github.com/yihong0618/MiService
```
