### ISSUE TITLE
我使用腾讯云 广州的轻量服务器，有报错 没有使有代理

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#82]
![image](https://user-images.githubusercontent.com/70465495/223203951-de5a5366-d4a7-471a-8814-c4dcc704d7b7.png)

**Comment by yihong0618** [comment]
export name 和 password 了没？

**Comment by yihong0618** [comment]
服务器大多会触发验证（之前有人遇到过，所以可能不行
