### ISSUE TITLE
LX5A不支持有办法吗

### ISSUE THREAD

**Issue by wangrui1573** [yihong0618/xiaogpt#84]
LX5A不支持有办法吗？ --use_command也不行
micli正常

![image](https://user-images.githubusercontent.com/42831156/223350760-d44476ab-607c-4664-bbe0-785a70250b1e.png)

![image](https://user-images.githubusercontent.com/42831156/223350977-9d62dc92-8af6-4cd4-877f-a6b44d363798.png)

**Comment by yihong0618** [comment]
micli 看看 spec

**Comment by wangrui1573** [comment]
![image](https://user-images.githubusercontent.com/42831156/223355736-45964748-5513-48b5-99e1-8dc08c0ea0df.png)

**Comment by yihong0618** [comment]
micli   spec xiaomi.wifispeaker.lx5a

**Comment by wangrui1573** [comment]
# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx5a:2

Device_Information = 1
    Device_Manufacturer = 1
    Device_Model = 2
    Device_Serial_Number = 3
    Current_Firmware_Version = 4

Speaker = 2
    Volume = 1  # uint8  # rw
    Mute = 2  # bool  # rw

Play_Control = 3
    Playing_State = 1  # uint8

    _Play = 1
    _Pause = 2
    _Next = 3
    _Previous = 4

Microphone = 4
    Mute = 1  # bool  # rw

Intelligent_Speaker = 5
    _Text_Content = 1
    _Silent_Execution = 2  # bool
    Sleep_Mode = 3  # bool  # rwn

    _Play_Text = 1  # in=[1]
    _Play_Music = 2
    _Wake_Up = 3
    _Play_Radio = 4
    _Execute_Text_Directive = 5  # in=[1, 2]

Clock = 6

    _Stop_Alarm = 1

Speaker_Volume
    MIN = 12
    MAX = 100

Play_Control_Playing_State
    Pause = 0
    Playing = 1

**Comment by wangrui1573** [comment]
这样吗，还是不行
![image](https://user-images.githubusercontent.com/42831156/223358001-5a41f8a3-ff57-40db-956a-98b9132bb4a0.png)
![image](https://user-images.githubusercontent.com/42831156/223358090-a20f1560-d972-479c-953f-315382b2fa13.png)

**Comment by yihong0618** [comment]
micli mina 看看 这个的 hardware 是叫 LX5A 么

**Comment by wangrui1573** [comment]
大佬威武，可以了！
![image](https://user-images.githubusercontent.com/42831156/223358981-d752609e-8feb-45dc-a19b-7afc5e65fde8.png)
![image](https://user-images.githubusercontent.com/42831156/223359107-9491b07a-f5c8-4570-a6ed-5a2264ec711f.png)

**Comment by yihong0618** [comment]
提个 PR 把这个加上？

**Comment by wangrui1573** [comment]
已提交
