### ISSUE TITLE
开启小爱同学的蓝牙是必须的吗？蓝牙在这个过程中的作用是什么？蓝牙要和哪个设备配对？

### ISSUE THREAD

**Issue by xgd561** [yihong0618/xiaogpt#87]
注意
请开启小爱同学的蓝牙
如果要更改提示词和 PROMPT 在代码最上面自行更改
目前已知 LX04 和 L05B L05C 可能需要使用 --use_command
QA

**Comment by yihong0618** [comment]
因为用了 ubus
