### ISSUE TITLE
docker没法使用

### ISSUE THREAD

**Issue by zjulihao** [yihong0618/xiaogpt#88]
出现如下错误信息：
Unable to find image 'yihong0618/xiaogpt:latest' locally
docker: Error response from daemon: pull access denied for yihong0618/xiaogpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
请问怎么解决，谢谢

**Comment by coder-user** [comment]
自己构建一个 docker 吧
```bash
docker build -t  chatgpt:v1 .
```

**Comment by pjq** [comment]
上传了一个image, 测了下可以跑起来
```
docker run -e OPENAI_API_KEY=sk-xxxxxx pengjianqing/xiaogpt:0.1 --account=xxxxx --password=xxxxxx --hardware=xxx --use_chatgpt_api

Running xiaogpt now, 用`帮我`开头来提问
```

**Comment by pjq** [comment]
Docker Image
- https://hub.docker.com/repository/docker/pengjianqing/xiaogpt/general
