### ISSUE TITLE
如何让小爱持续对话呢？

### ISSUE THREAD

**Issue by xiagw** [yihong0618/xiaogpt#89]
每次都要重新唤醒，
这个有办法解决吗？

**Comment by joe12801** [comment]
可以参考siri 接入chatgpt 脚本

**Comment by yihong0618** [comment]
@joe12801 现在是支持持续对话的，这里面说的持续对话指的是不用持续呼唤小爱

**Comment by yihong0618** [comment]
可能有办法，我们在播放完时候隔 1s 唤醒一次小爱总共唤醒 10 次。。。@pjq 不确定完能实现么。

**Comment by Sleaf** [comment]
@yihong0618 
https://www.zhihu.com/answer/1222190124
看起来使用 “闲聊” 可以实现

手机上升级3.0之后是可以直接默认开启连续对话的，但据说只有redmi音响之后的机型才默认配置3.0

**Comment by Sleaf** [comment]
https://m.jb51.net/hardware/zonghe/826343.html
附一个有连续兑换开关的说明![2022050914380985.jpg](https://user-images.githubusercontent.com/23637144/225046359-fc11a04f-c36f-4c14-9d1e-2f7bd4008521.jpg)

**Comment by yihong0618** [comment]
@Sleaf @all
目前可以了 感谢 @frostming
