### ISSUE TITLE
we have no hardware: S12 please check

### ISSUE THREAD

**Issue by yuyongID** [yihong0618/xiaogpt#9]
操作：配置好MI_USER、MI_PASS和MI_DID之后，执行 `python3 xiaogpt.py --hardware S12`
现象：提示`we have no hardware: S12 please check`
排查：
1. 使用micli的命令，可以正常让小爱同学说话。
2. 执行命令 `micli mina` 返回空数组 `[]`
3. 执行命令 `micli list`，只返回两个路由器的信息，没有小爱音箱。（MI_DID的值是通过homeassistant 小米插件获取的）
4. 手动修改脚本`_init_data_hardware`函数，直接指定 `decive_id`。执行命令后提示，获取小爱聊天记录接口“越界”（盲猜是从小米服务器读取不到账号下的小爱同学聊天记录）

**Comment by yihong0618** [comment]
@yuyongID 

1. 手机下载小爱音箱 app 看看能找到聊天记录么
2. 尝试抓包看看 https://userprofile.mina.mi.com/device_profile/v2/conversation... 这个接口的 cookie 是什么

**Comment by yuyongID** [comment]
> 

1. 手机上的小爱app正常展示聊天记录，米家app上的设备也不只有两个路由器；
2. 抓包是手机上抓包吗？抓cookie出来之后跟在哪里使用呢？

**Comment by yihong0618** [comment]
是的，在手机上，抓出 cookie 和 url 你脱敏后贴在这我看看～

**Comment by yuyongID** [comment]
> 
URL:
`https://userprofile.mina.mi.com/device_profile/v2/conversation?source=dialogu&hardware=S12A&timestamp=1676880703473&limit=10`
cookies:
```bash
deviceId=a6d2****-90f1-****-****-****7fed5b77
serviceToken=sX****Q+aGYx****HI/d/Dge****fW//cytPp****Nz+OF****Ef/mhn1krm****M8vVBzj+wb81B****CzA==
userId=56****65
```

**Comment by yihong0618** [comment]
@yuyongID 增加了直接用 cookie 

可以加上 --cookie ${你上面的cookie} 参考 README 来尝试

**Comment by yuyongID** [comment]
> @yuyongID 增加了直接用 cookie
> 
> 拉一下最新代码。
> 
> 可以加上 --cookie ${你上面的cookie} 参考 README 来尝试

使用新代码，再填入cookie确实可以使用了。建议再README里提示一下，cookie需要用“引号”来包裹cookie字符串
