### ISSUE TITLE
能否创建X86的docker image，或者有高手能否指导一下如何创建image。

### ISSUE THREAD

**Issue by wgjwillis** [yihong0618/xiaogpt#91]
0.1的是arm的，x86平台运行不了。

**Comment by pjq** [comment]
@wgjwillis  这个我倒没注意，对的，我的电脑是Apple M1
 可以自己本地编译一个
```
  docker build -t pengjianqing/xiaogpt . 
```

**Comment by pjq** [comment]
@yihong0618  你电脑是X86还是Arm的

**Comment by pjq** [comment]
我研究一下 怎么编译X86的

**Comment by pjq** [comment]
正在编译中
```
docker buildx build --platform=linux/amd64 -t pengjianqing/xiaogpt-x86 .
```

**Comment by pjq** [comment]
All right, it's uploaded
- https://hub.docker.com/repository/docker/pengjianqing/xiaogpt-x86/general

**Comment by wangrui1573** [comment]
整了个X86 群晖可以跑：
docker pull realwang/xiaoaigpt:latest

docker run -d -name xiaoaogpt -e MI_DID=替换音响DID -e OPENAI_API_KEY=替换key  realwang/xiaoaigpt:latest --account=小米账户 --password=小米密码 --hardware=型号 --use_chatgpt_api

![image](https://user-images.githubusercontent.com/42831156/223609065-3eb35219-90cf-4fa6-bce6-8522ef3a92b9.png)

**Comment by yihong0618** [comment]
@wangrui1573 帅啊

**Comment by pjq** [comment]
等下我也在上面跑一下试试

**Comment by pjq** [comment]
我现在跑在树莓派上

**Comment by openkava** [comment]
怎么支持小米电视里面的小爱啊？

**Comment by wgjwillis** [comment]
谢谢大家！！！速度真快！！！

**Comment by brryaa** [comment]
赞，就等arm64了

**Comment by pjq** [comment]
> 赞，就等arm64了

arm已经有了
···
X86: pengjianqing/xiaogpt-x86
ARM: pengjianqing/xiaogpt
···

**Comment by pjq** [comment]
> 

这种属于一个APP性质 估计不行

**Comment by ofbillow** [comment]
> 

这个真好，不过我是小白，群晖也是刚入手，都不会弄，能不能有详细的一步步的教程啊，好想学

**Comment by brryaa** [comment]
> 

哈哈，没注意看发布者，直接用一楼的realwang，折腾半天装完才提示 WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by brryaa** [comment]
> > 赞，就等arm64了
> 
> arm已经有了 ··· X86: pengjianqing/xiaogpt-x86 ARM: pengjianqing/xiaogpt ···

Pull不下来，是啥问题呢

**Comment by wangrui1573** [comment]
--name 试试
