### ISSUE TITLE
多个小爱音箱能否指定多个MI_DID值呢？

### ISSUE THREAD

**Issue by wangrui1573** [yihong0618/xiaogpt#93]
MI_DID是通过读取环境变量，如果家里有多台小爱音箱，怎么办呢，多个环境变量？
MI_DID1=xxx MI_DID2=xxx
还是配置文件可以直接指定MI_DID值？

**Comment by pjq** [comment]
做两个alias, 放到 .bashrc or .zshrc
chatgpt_bedroom_speaker='export MI_DID="xxxx" && cd ~/chatgpt-mispeaker/ && python3 xiaogpt.py --config  myconfig_bedroom.json'
chatgpt_livingroom_speaker='export MI_DID="xxxx" && cd  ~/chatgpt-mispeaker/ && python3 xiaogpt.py --config  myconfig_livingroom.json'

**Comment by wangrui1573** [comment]
感觉不太行，两个音响同步了，无法独立工作，你那测试可以吗？

**Comment by pjq** [comment]
我可以两个音箱独立工作 没问题

**Comment by wangrui1573** [comment]
晚上由测试了一下，跟DID无关，两个小爱音箱且设备型号一致，就会只有第一个有用

**Comment by ChaimHong** [comment]
> 晚上由测试了一下，跟DID无关，两个小爱音箱且设备型号一致，就会只有第一个有用

确实是，解绑第一个就正常了
