### ISSUE TITLE
小爱音箱Play增强版支持问题

### ISSUE THREAD

**Issue by kergee** [yihong0618/xiaogpt#94]
具体表现回答时--mute_xiaoai不起作用，GPT回答不能播报
查型号接口http://[miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05c:2](http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05c:2)
和实际micli指令不一致，现在能测出来的：
micli 5-4 明天天气 0
micli 5-3 朗读文本

**Comment by yolain** [comment]
可以参考下我fork的我的L05C也是监听不到播放状态，我让强制停止播放了。

**Comment by yolain** [comment]
可以参考下我fork的
我的L05C也是监听不到播放状态，我尝试让它直接暂停播放，是可行的
然后用 5-4 指令持续唤醒小爱同学，感觉上像在持续性对话，哈哈！不知道还有没有更完善的办法

**Comment by 1500256797** [comment]
L05C确实比较变态

**Comment by kergee** [comment]
> 可以参考下我fork的 我的L05C也是监听不到播放状态，我尝试让它直接暂停播放，是可行的 然后用 5-4 指令持续唤醒小爱同学，感觉上像在持续性对话，哈哈！不知道还有没有更完善的办法

请问如何直接暂停播放？用指令、语音还是米家App？

**Comment by sanzhier82** [comment]
> 可以参考下我fork的 我的L05C也是监听不到播放状态，我尝试让它直接暂停播放，是可行的 然后用 5-4 指令持续唤醒小爱同学，感觉上像在持续性对话，哈哈！不知道还有没有更完善的办法

您好，我是个菜鸟，我卡在读DID那里了，您弄通了能帮我看下吗，有偿求助。

**Comment by sanzhier82** [comment]
> 可以参考下我fork的 我的L05C也是监听不到播放状态，我尝试让它直接暂停播放，是可行的 然后用 5-4 指令持续唤醒小爱同学，感觉上像在持续性对话，哈哈！不知道还有没有更完善的办法

@yolain 您好，我卡在读DID了，您弄通了能帮我看下吗，有偿求助。

**Comment by yihong0618** [comment]
@yolain 我感觉你的方案特别棒，你有兴趣整理下通用的代码提个 PR 么？

**Comment by yolain** [comment]
> @yolain 我感觉你的方案特别棒，你有兴趣整理下通用的代码提个 PR 么？

😭手头突然开始忙碌了，估计得过一两周才有时间。大佬要觉得这个方案可行，可以按这个思路延展下去看看。有几个问题我没解决。1. chatgpt回答后 5-4 呼出小爱同学 它还会播放回复词（没法mute掉，不太清楚其他型号的设备能否mute掉）, 2.说到有些关键词，小爱会去播音乐了 😂

**Comment by yolain** [comment]
> > 可以参考下我fork的 我的L05C也是监听不到播放状态，我尝试让它直接暂停播放，是可行的 然后用 5-4 指令持续唤醒小爱同学，感觉上像在持续性对话，哈哈！不知道还有没有更完善的办法
> 
> @yolain 您好，我卡在读DID了，您弄通了能帮我看下吗，有偿求助。

有报错吗？

**Comment by yihong0618** [comment]
> 

不用 mute 啊，他不就说个“在”么？

**Comment by yolain** [comment]
> > 
> 
> 不用 mute 啊，他不就说个“在”么？

对！它会说个 在吗？或者干嘛呀！ 我想说能不能只留那个噔的声音。😂

**Comment by yihong0618** [comment]
除了 README 里特定型号应该都能，参考我之前 mute 他的方式

**Comment by ydbdyds** [comment]
试了一下大佬的fork，感觉还是有点问题，该没播报还是没播报

**Comment by yihong0618** [comment]
看一下型号，然后 issue 试着搜索下？
大部分型号最后都成功了

**Comment by sanzhier82** [comment]
> 

@yolain 获取到DID了，设置DID了，蓝牙连接上了，就是尝试操作音箱，都没用。跟音箱型号有关吗，我的是PLAY增强版ll05c

nielei@nieleideMini miservice % python3 micli.py 2  
[
  null
]
nielei@nieleideMini miservice % python3 micli.py 2=#60
[
  -704042011
]
nielei@nieleideMini miservice % python3 micli.py 5 您好
-704220025

**Comment by yihong0618** [comment]
先看 spec

**Comment by sanzhier82** [comment]
> 
我看了spec了，除了1-系列的几个命令有用，其他的要么就返回null， 要么就这种数字报错。

**Comment by yolain** [comment]
> > 
> 
> 我看了spec了，除了1-系列的几个命令有用，其他的要么就返回null， 要么就这种数字报错。

l05c的tts功能只有 5-3 跟 5-4 的指令能用，你需要这样子：   python3 micli.py 5-3 你好

**Comment by sanzhier82** [comment]
> 
谢谢大神，我又试了下，发现是连了音箱通过蓝牙连接了电脑后，就没有连接Wi-Fi，连接了米家后就可以了。
还有，家里lx06和l05c都试过，lx06是早买的，一直没试通。新买的l05c可以操作。

**Comment by sanzhier82** [comment]
> 
@yolain 大神，最后这步报这样的错误，是不是用了代理后ssl验证又报错了呢

nielei@nieleideMini xiaogpt % python3 xiaogpt.py --hardware L05c --use_chatgpt_api --mute_xiaoa
Running xiaogpt now, 用`帮我`开头来提问
Exception on login 1231108757: Cannot connect to host account.xiaomi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)')]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)

The above exception was the direct cause of the following exception:

**Comment by sanzhier82** [comment]
@yolain 大神，再请教下，到最后这步了，报了这个错误。

nielei@nieleideMini xiaogpt % python3 xiaogpt.py --hardware L05c --use_chatgpt_api --mute_xiaoai 
Running xiaogpt now, 用`帮我`开头来提问
Traceback (most recent call last):
  File "/Users/nielei/Documents/xiaomi/xiaogpt/xiaogpt.py", line 495, in <module>
    asyncio.run(miboy.run_forever())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nielei/Documents/xiaomi/xiaogpt/xiaogpt.py", line 326, in run_forever
    await self.init_all_data(session)
  File "/Users/nielei/Documents/xiaomi/xiaogpt/xiaogpt.py", line 150, in init_all_data
    await self._init_data_hardware()
  File "/Users/nielei/Documents/xiaomi/xiaogpt/xiaogpt.py", line 180, in _init_data_hardware
    raise Exception(f"we have no hardware: {self.hardware} please check")
Exception: we have no hardware: L05c please check

**Comment by yolain** [comment]
> @yolain 大神，再请教下，到最后这步了，报了这个错误。
> 
> Exception: we have no hardware: L05c please check

L05C是大写，你打错了😂

**Comment by yolain** [comment]
我去试了Afool4U fork的 流式对话，在L05C设备上表现不太好，感觉主要问题还是因为监听不到是否正在播放状态，导致它没办法停顿，还没播完前一段就开始下一段了。😔哎，建议大家有其他设备还是用其他设备吧。

**Comment by yihong0618** [comment]
> 我去试了Afool4U fork的 流式对话，在L05C设备上表现不太好，感觉主要问题还是因为监听不到是否正在播放状态，导致它没办法停顿，还没播完前一段就开始下一段了。😔哎，建议大家有其他设备还是用其他设备吧。

在没有蓝牙通信设备不太能 mute

**Comment by afan1123** [comment]
> 
![cf1ed8eab9f8e505fcbcb8b1889ed19](https://github.com/yihong0618/xiaogpt/assets/66288342/3c8db6ff-a7e6-4fb5-8c7d-4f8feb9f5998)
![8fd88f0c0f0427b7cd4b40bb97b1cab](https://github.com/yihong0618/xiaogpt/assets/66288342/4649bb90-2c97-448e-b23b-c34f57274758)

大佬，你咋弄的啊，我卡在这了
