### ISSUE TITLE
有人知道一代小米音箱型号吗？

### ISSUE THREAD

**Issue by palemoky** [yihong0618/xiaogpt#95]
我看一代机身只有一个 SN 号，包装早就扔了，翻遍互联网都没找到一代是什么型号，迫不得已在此开个 issues，请问有人知道吗？

**Comment by yihong0618** [comment]
micli mina 看看？

**Comment by yihong0618** [comment]
试试 S12A？ https://github.com/yihong0618/xiaogpt/issues/55

**Comment by brryaa** [comment]
S12

**Comment by palemoky** [comment]
> 试试 S12A？ #55

S12A 提示 `Exception: we have no hardware: S12A please check`，@brryaa 的 S12 能正常启动，但询问提问小爱后没有走 chatgpt，日志也没有任何的输出。我已经打开蓝牙了，加不加 `--use_command ` 都一样
```
$ python3 xiaogpt.py --use_command --mute_xiaoai --use_chatgpt_api --hardware S12   
Running xiaogpt now, 用`帮我`开头来提问
```
我用 `micli.py 5 你好` 是能语音播报的，但 `micli.py 5-4 查询天气 #1` 就会报错 `-704220025` ，我翻了这个仓库和MiService的仓库，都没有找到解决办法，请问大佬知道怎么解决吗？不行我再去MiService开个 issues :(

**Comment by yihong0618** [comment]
把后面那个 #1 去掉

**Comment by palemoky** [comment]
试过了，也是不行的，可能这款音箱不支持？

**Comment by palemoky** [comment]
我翻了所有 S12 相关的 issues，发现用 https://github.com/yihong0618/xiaogpt/issues/4 里边的`micli.py action '{"did":"设置 DID","miid":0,"siid":5,"aiid":5,"in":["天气怎么样", 0]}'`能正常向小爱发送指令，小爱有正常回应。但日志一直没有刷新，我即使用 `--api_base` 换了 API，日志也不刷新。试了和小爱聊了别的也没日志。
<img width="923" alt="image" src="https://user-images.githubusercontent.com/21208635/224366219-948b4f61-84f1-49af-8fb2-c82c82e52dad.png">

我有两个同型号的 S12 音箱，不过一个在老家，这个应该没有影响吧？还有小爱只要开启蓝牙，还需要电脑蓝牙连接音箱吗？

**Comment by roostinghawk** [comment]
我的小爱接口返回"model": "xiaomi.wifispeaker.s12", 把硬件设置为 “S12A” 是可以的 @palemoky

**Comment by palemoky** [comment]
@roostinghawk 我设置成 S12A 报错 Exception: we have no hardware: S12A please check，只有 S12 没报错，但也没有任何日志和响应

**Comment by roostinghawk** [comment]
小米音箱底座的序列号，最后几位就是型号，你拍个照片发下 @palemoky

**Comment by palemoky** [comment]
![image](https://user-images.githubusercontent.com/21208635/225086223-6b3cf001-59ad-47d5-835a-0f0c0ecd6e81.png)
@roostinghawk 我看 SN 码全是数字，型号中也没有任何 S12 或 S12A 的标识

**Comment by roostinghawk** [comment]
@palemoky 你的micli 返回的数据是什么，我的是这样格式（结尾有个 s12）
`  {
    "name": "小米AI音箱",
    "model": "xiaomi.wifispeaker.s12",
...`

**Comment by palemoky** [comment]
> > micli mina 看看？
> 
> @yihong0618 请问 mina 是什么命令？我看 micli 支持的命令列表中没有这个选项，我用 list 只获取到一个 model ，看起来还不对
> 
> <img alt="image" width="433" src="https://user-images.githubusercontent.com/21208635/223960159-0e694c6c-395a-4cc8-98dd-e4040c2ff0db.png">

@roostinghawk micli 返回的数据如上图。我刚刚拉取最新代码后，分别用 S12A 和 S12 启动如下：
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/21208635/225195323-5bf2751e-5f4f-4deb-b4a3-a4892fa17cb2.png">

**Comment by yihong0618** [comment]
micli mina 这么打就行

**Comment by roostinghawk** [comment]
S12 看起来启动没报错，交流时报错吗？

**Comment by palemoky** [comment]
@roostinghawk 无论怎么和小爱交流，都没有日志输出，不知道怎么调试

**Comment by roostinghawk** [comment]
那问题应该出在没有查到最近的小爱聊天记录上，请求这个时有问题 LATEST_ASK_API

**Comment by yihong0618** [comment]
S12 or S12A

可以用 --use_command 试试

**Comment by gaidan1983** [comment]
> ![image](https://user-images.githubusercontent.com/21208635/225086223-6b3cf001-59ad-47d5-835a-0f0c0ecd6e81.png) @roostinghawk 我看 SN 码全是数字，型号中也没有任何 S12 或 S12A 的标识

与你照片里一样，同为第一代小爱，屁股上MDZ-25-DA，在config.py 中加入 S12 可以正常使用GPT回答

**Comment by yihong0618** [comment]
@gaidan1983 感谢我加一下
