### ISSUE TITLE
Dokcer 镜像报错 ARM架构

### ISSUE THREAD

**Issue by joe12801** [yihong0618/xiaogpt#99]
*** System restart required ***
Last login: Wed Mar  8 16:05:36 2023 from 104.28.201.73
root@instance-20230128-2240:~# docker run -e OPENAI_API_KEY=sk-Vx5g9444H6RqiZAXQT3BlbkF pengjianqing/xiaogpt --account=15 --password=a --hardware=LX06 --use_chatgpt_api
Unable to find image 'pengjianqing/xiaogpt:latest' locally
docker: Error response from daemon: manifest for pengjianqing/xiaogpt:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

**Comment by brryaa** [comment]
一样。

**Comment by pjq** [comment]
@joe12801 把密码删掉哦

**Comment by kvenLin** [comment]
作者打的镜像tag只有0.1没有latest
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/30554496/224566897-afecba12-03f5-4c8e-b36d-728a6fe2239f.png">
提问把密码删了,别人能直接用你账号了
`docker run --name mi-chatgpt -e OPENAI_API_KEY=xxxx -v your_path:/config -d pengjianqing/xiaogpt:0.1 --account=xxxx --password=xxxx --hardware=L15A --mute_xiaoai --use_chatgpt_api --config=/config/config.json`

**Comment by pjq** [comment]
对的 我只上传了0.1版本 @joe12801 快把密码删除

**Comment by joe12801** [comment]
我的那手机和密码，我都故意写错了，没事

**Comment by joe12801** [comment]
@pjq

**Comment by pjq** [comment]
没问题 这个
